'use strict';
(() => {
 const safely=fn=>async event=>{event?.preventDefault?.();try{await fn(event);}catch(e){toast(e.message,true);}};
 const opts=(items,wanted)=>items.map(([id,name])=>'<option value="'+esc(id)+'" '+(id===wanted?'selected':'')+'>'+esc(name)+'</option>').join('');
 const field=(name,id,value,type='text')=>'<label>'+name+'<input id="'+id+'" type="'+type+'" value="'+esc(value??'')+'"></label>';
 const choice=(name,id,items,value)=>'<label>'+name+'<select id="'+id+'">'+opts(items,value)+'</select></label>';
 const check=(label,id,value)=>'<label class="check"><input id="'+id+'" type="checkbox" '+(value?'checked':'')+'>'+label+'</label>';
 const chainList=()=> (S.config.actionChains||[]).map(x=>[x.id,x.name]);
 const modifierNames=new Set(['ctrl','control','strg','alt','shift','umschalt','win','windows','super','meta','commandorcontrol']);
 function requireCombination(value){
  const text=String(value||'').trim(),parts=text.split('+').map(x=>x.trim()).filter(Boolean);
  if(!parts.length)throw Error('Bitte zuerst eine Kombination eingeben oder aufnehmen, zum Beispiel F8.');
  if(parts.every(x=>modifierNames.has(x.toLowerCase())))throw Error('Zu Strg, Alt, Umschalt oder Windows gehört noch eine Taste oder Maustaste, zum Beispiel Control+F8.');
  return text;
 }
 let captureSession=null;
 function cancelRecording(){
  const active=captureSession;if(active){active.cancelled=true;active.status.textContent='Aufnahme beendet. Die vorherige Kombination bleibt erhalten.';}
  return api.hotkeyCancelCapture?.().catch(()=>{});
 }
 async function recordCombination(field,status,scope,accept){
  if(captureSession)throw Error('Bitte die laufende Aufnahme zuerst beenden.');
  if(outputSaving||outputTesting||keySaving)throw Error('Bitte den laufenden Vorgang zuerst abschließen lassen.');
  const active={field,status,cancelled:false};captureSession=active;
  const controls=[...scope.querySelectorAll('input,select,textarea,button')].filter(x=>!x.hasAttribute('data-cancel-record'));
  const previous=controls.map(x=>[x,x.disabled]);for(const [x] of previous)x.disabled=true;
  status.textContent='Gewünschte Tasten gleichzeitig halten und dann loslassen … (15 Sekunden)';
  try{
   const r=await api.hotkeyCapture();
   // A click on "Aufnahme beenden" can also be observed by the native mouse hook.
   // Give that DOM click time to cancel before accepting its capture response.
   await new Promise(resolve=>setTimeout(resolve,80));
   if(active.cancelled||!field.isConnected)return;
   if(!r||r.ok===false)throw Error(r?.error||'Die Aufnahme hat keine Kombination geliefert.');
   const accelerator=requireCombination((r.result||r).accelerator);
   field.value=accelerator;accept();status.textContent='Erkannt: '+accelerator;
  }catch(error){if(!active.cancelled&&field.isConnected){status.textContent=error.message;throw error;}}
  finally{for(const [x,disabled] of previous)if(x.isConnected)x.disabled=disabled;if(captureSession===active)captureSession=null;}
 }
 function requireRecordingFinished(){if(captureSession)throw Error('Bitte die Aufnahme zuerst beenden und die erkannte Kombination prüfen.');}
 const keyActions=()=>S.config.keyActions||[];
 const keyActionOptions=()=>[['','Tastenkombination auswählen'],...keyActions().map(x=>[x.id,x.name+(x.enabled===false?' (Aus)':'')])];
 const outputMouseOptions=[['','Bitte wählen'],['LButton','Linke Maustaste'],['RButton','Rechte Maustaste'],['MButton','Mittlere Maustaste'],['XButton1','Seitliche Maustaste 1'],['XButton2','Seitliche Maustaste 2'],['WheelUp','Mausrad nach oben'],['WheelDown','Mausrad nach unten'],['WheelLeft','Mausrad nach links'],['WheelRight','Mausrad nach rechts']];
 const humanError=error=>String(error?.message||error).replace(/^Error invoking remote method '[^']+':\s*(?:Error:\s*)?/,'');
 const newOutput=()=>({id:null,name:'',process:'',keys:'',keyFormat:'chord',holdMs:100,enabled:true});
 let outputDraft=null,outputDirty=false,outputSaving=false,outputTesting=false;
 function renderKeyActions(root=$('#hotkeysModule')){
  if(!root)return;$('#keyActionsEditor')?.remove();const d=outputDraft||newOutput(),box=document.createElement('section');box.id='keyActionsEditor';box.className='panel-section';root.prepend(box);
  box.innerHTML='<h3>Tastenkombinationen für Events und Stream Deck</h3><p>Speichere, welche Tasten Batto in einem Zielprogramm drücken soll. Danach kannst du dieselbe Kombination in Events, Aktionsketten und auf dem Stream Deck auswählen.</p><div class="form-grid">'+field('Name','outputKeyName',d.name)+field('Zielprogramm / Prozessname','outputKeyProcess',d.process)+field('Tastenkombination','outputKeys',d.keys)+field('Tastendauer (ms)','outputKeyHold',d.holdMs,'number')+'</div><p>Beispiel: K+LButton für K und linke Maustaste. Gib den Prozessnamen des geöffneten Programms an, zum Beispiel Spiel.exe.</p><div class="toolbar">'+choice('Maustaste zur Kombination hinzufügen','outputMouse',outputMouseOptions,'')+'<button type="button" id="outputAddMouse">Maustaste hinzufügen</button></div><div class="toolbar"><button type="button" id="outputRecord">Kombination aufnehmen</button><button type="button" id="outputCancelRecord" data-cancel-record>Aufnahme beenden</button></div><p id="outputRecordStatus" role="status"></p>'+check('Tastenkombination aktiv','outputKeyEnabled',d.enabled!==false)+'<div class="toolbar"><button type="button" id="outputKeySave" class="primary">Tastenkombination speichern</button><button type="button" id="outputKeyNew">Neue Tastenkombination</button><button type="button" id="outputKeyTest">Gespeicherte Kombination jetzt ausführen</button></div><p id="outputKeyStatus" role="status">'+(outputDirty?'Ungespeicherter Entwurf':d.id?'Gespeicherte Tastenkombination ausgewählt.':'Zielprogramm und Kombination eintragen, dann speichern.')+'</p><h4>Gespeicherte Tastenkombinationen</h4>'+(keyActions().length?keyActions().map(x=>'<div class="list-row"><span><b>'+esc(x.name)+'</b> · '+esc(x.keys)+' · '+esc(x.process)+' · '+(x.enabled!==false?'Aktiv':'Aus')+'</span><button type="button" data-output-key-edit="'+esc(x.id)+'">Bearbeiten</button></div>').join(''):'<p>Noch keine Tastenkombination gespeichert.</p>');
  const read=()=>({...d,name:$('#outputKeyName').value.trim(),process:$('#outputKeyProcess').value.trim(),keys:$('#outputKeys').value.trim(),keyFormat:'chord',holdMs:Number($('#outputKeyHold').value),enabled:$('#outputKeyEnabled').checked});
  const remember=()=>{outputDraft=read();outputDirty=true;$('#outputKeyStatus').textContent='Ungespeicherter Entwurf';};
  const status=message=>{if($('#outputKeyStatus'))$('#outputKeyStatus').textContent=message;};
  const lock=()=>{for(const el of box.querySelectorAll('input,select,button'))el.disabled=outputSaving||outputTesting;};
  $('#outputKeyHold').min='10';$('#outputKeyHold').max='3000';$('#outputKeyHold').step='1';$('#outputKeys').placeholder='K+LButton oder Control+F8';$('#outputKeyProcess').placeholder='Spiel.exe';
  box.querySelectorAll('input,select').forEach(el=>{el.oninput=remember;el.onchange=remember;});
  $('#outputAddMouse').onclick=()=>{const mouse=$('#outputMouse').value;if(!mouse)return;const parts=$('#outputKeys').value.split('+').map(x=>x.trim()).filter(Boolean);if(!parts.some(x=>x.toLowerCase()===mouse.toLowerCase()))parts.push(mouse);$('#outputKeys').value=parts.join('+');remember();};
  $('#outputRecord').onclick=safely(()=>recordCombination($('#outputKeys'),$('#outputRecordStatus'),root,remember));
  $('#outputCancelRecord').onpointerdown=cancelRecording;$('#outputCancelRecord').onclick=cancelRecording;
  $('#outputKeySave').onclick=safely(async()=>{
   if(outputSaving||outputTesting)return;requireRecordingFinished();const item={...read(),id:d.id||cryptoId()};outputDraft=item;
   try{if(!item.name||item.name.length>100){$('#outputKeyName').focus();throw Error('Bitte einen Namen mit 1 bis 100 Zeichen eingeben.');}if(!item.process){$('#outputKeyProcess').focus();throw Error('Bitte das Zielprogramm als Prozessnamen angeben, zum Beispiel Spiel.exe.');}item.keys=requireCombination(item.keys);if(!Number.isInteger(item.holdMs)||item.holdMs<10||item.holdMs>3000){$('#outputKeyHold').focus();throw Error('Tastendauer: 10 bis 3000 Millisekunden.');}}
   catch(error){status(error.message);throw error;}
   outputSaving=true;lock();
   try{const all=[...keyActions()],i=all.findIndex(x=>x.id===item.id);if(i<0)all.push(item);else all[i]=item;await saveAndSync({keyActions:all},'Tastenkombination gespeichert.');outputDraft=structuredClone(keyActions().find(x=>x.id===item.id)||item);outputDirty=false;renderKeyActions(root);status('Gespeichert: '+outputDraft.name+'. Jetzt in Events, Aktionsketten und Stream Deck auswählbar.');}
   catch(error){const message=humanError(error);status(message);throw Error(message);}
   finally{outputSaving=false;const current=$('#keyActionsEditor');if(current)for(const el of current.querySelectorAll('input,select,button'))el.disabled=outputTesting;}
  });
  $('#outputKeyNew').onclick=()=>{if(outputSaving||outputTesting)return;cancelRecording();if(outputDirty&&!confirm('Ungespeicherten Tastenkombinationsentwurf verwerfen?'))return;outputDraft=newOutput();outputDirty=false;renderKeyActions(root);};
  $('#outputKeyTest').onclick=safely(async()=>{
   if(outputSaving||outputTesting)return;requireRecordingFinished();const item=read(),saved=keyActions().find(x=>x.id===item.id);
   if(!saved||['name','process','keys','holdMs','enabled'].some(k=>item[k]!==saved[k])){status('Bitte die Tastenkombination zuerst speichern.');throw Error('Bitte die Tastenkombination zuerst speichern.');}
   if(saved.enabled===false){status('Diese Tastenkombination ist deaktiviert.');throw Error('Diese Tastenkombination ist deaktiviert.');}
   outputTesting=true;lock();status('Tastenkombination wird an das Zielprogramm übergeben …');
   try{const result=await api.testAutomationAction({type:'key-action',keyActionId:saved.id});if(result?.ok!==true)throw Error(result?.error||'Tastenkombination wurde nicht ausgeführt.');status('Eingabe an Windows übergeben. Bitte das Ergebnis im Zielprogramm prüfen.');}
   catch(error){const message=humanError(error);status(message);throw Error(message);}
   finally{outputTesting=false;const current=$('#keyActionsEditor');if(current)for(const el of current.querySelectorAll('input,select,button'))el.disabled=outputSaving;}
  });
  box.querySelectorAll('[data-output-key-edit]').forEach(button=>button.onclick=()=>{if(outputSaving||outputTesting)return;requireRecordingFinished();if(outputDirty&&!confirm('Ungespeicherten Tastenkombinationsentwurf verwerfen?'))return;const item=keyActions().find(x=>x.id===button.dataset.outputKeyEdit);if(!item)return;outputDraft=structuredClone(item);outputDirty=false;renderKeyActions(root);});lock();
 }
 function prefillKeyAction(binding){
  if(outputSaving||outputTesting)return;requireRecordingFinished();if(outputDirty&&!confirm('Ungespeicherten Tastenkombinationsentwurf verwerfen?'))return;
  outputDraft={...newOutput(),name:binding.name||binding.accelerator||'',keys:binding.accelerator||''};outputDirty=true;renderKeyActions();$('#keyActionsEditor')?.scrollIntoView({block:'start'});if($('#outputKeyStatus'))$('#outputKeyStatus').textContent='Kombination übernommen. Bitte Zielprogramm eintragen und speichern.';
 }
 window.BattoKeyActionsEditor={render:renderKeyActions,prefill:prefillKeyAction};
 const TEMPLATE='using System;\nusing Newtonsoft.Json;\npublic class CPHInline {\n public bool Execute() {\n  string message;\n  if (!CPH.TryGetArg("message", out message) || String.IsNullOrWhiteSpace(message)) return false;\n  CPH.WebsocketBroadcastJson(JsonConvert.SerializeObject(new {\n   action = "sendChatbotMessage", args = new { message = message }\n  }));\n  return true;\n }\n}\n';
 const baseSettings=renderSettingsModule;renderSettingsModule=function(){baseSettings();const box=document.createElement('section');box.className='panel-section';box.innerHTML='<h3>Stream Deck verbinden</h3><p>Einmal im Stream-Deck-Plugin einfügen. Damit steuerst und testest du deine gespeicherten Aktionen und Events.</p><button id="deckCopy">Verbindungscode kopieren</button>';$('#settingsModule').append(box);$('#deckCopy').onclick=safely(async()=>{await api.copyNavigationConnection();toast('Verbindungscode kopiert.');});};
 window.renderStreamerbotModule=function(){
  const box=$('#streamerbotModule');if(!box)return;const c=S.config.streamerbot||{};
  box.innerHTML='<section class="panel-section"><h3>Streamer.bot verbinden</h3><p>Eine Verbindung für Events, Commands, Hotkeys und Auto-Broadcast. <a href="https://streamer.bot/downloads" target="_blank" rel="noopener noreferrer">Offizieller Download ↗</a></p><div class="form-grid">'+field('WebSocket-Adresse','sbUrl',c.url)+field('Server-Passwort (nur bei Änderung)','sbPassword','','password')+'</div>'+check('Beim Programmstart verbinden','sbAuto',c.autoConnect)+choice('TikTok-Ereignisse','sbTikEvents',[['direct','TikFinity direkt'],['bridge','Streamer.bot-Bridge']],c.tiktokEvents)+choice('Spendenanbieter','sbProvider',[['none','Keiner'],['streamlabs','Streamlabs'],['streamelements','StreamElements']],c.tipProvider)+'<div class="toolbar"><button id="sbConnect" class="primary">Speichern & verbinden</button><button id="sbDisconnect">Trennen</button><button id="sbRefresh">Status prüfen</button></div><p id="sbState" role="status"></p></section><section class="panel-section"><h3>TikTok-Chatnachricht über TikFinity</h3><p>Einmal in Streamer.bot die Aktion „Batto – TikFinity Chatnachricht“ mit der C#-Vorlage anlegen. TikFinity mit Streamer.bot verbinden und im TikFinity-Chatbot das Senden über Streamer.bot erlauben. Ein statischer Argument-Schritt darf <b>message</b> nicht überschreiben.</p><button id="sbCopyTemplate">C#-Vorlage kopieren</button><details><summary>Code ansehen</summary><pre>'+esc(TEMPLATE)+'</pre></details>'+field('Aktionen suchen','sbSearch','')+choice('Gemeinsame TikTok-Vorlage','sbTemplate',[[c.tiktokActionId||'',c.tiktokActionId?'Gespeicherte Vorlage – Aktionen laden':'Noch nicht ausgewählt']],c.tiktokActionId)+'<div class="toolbar"><button id="sbActions">Aktionen laden</button><button id="sbSaveTemplate" class="primary">TikTok-Vorlage speichern</button></div><p id="sbTemplateState">Alle TikTok-Broadcasts verwenden dieselbe Vorlage mit ihrem eigenen Nachrichtentext. Ohne Auswahl bleibt eine bisher eingerichtete HTTP-Verbindung erhalten.</p></section><section class="panel-section"><h3>Aktion testen</h3>'+choice('Aktion','sbTestAction',[['','Aktionen laden']],'')+field('Beispielnachricht','sbMessage','Batto Auto-Broadcast-Test')+'<pre id="sbArgs"></pre><div class="toolbar"><button id="sbPreview">Nur Vorschau</button><button id="sbExecute">Jetzt wirklich ausführen</button></div><p id="sbTestResult" role="status">Eine angenommene Aktion bestätigt noch keine Zustellung im TikTok-Chat.</p></section>';
  let actions=[];
  const fill=()=>{const filtered=actions.filter(a=>a.enabled&&(a.name.toLowerCase().includes($('#sbSearch').value.toLowerCase())||a.id===c.tiktokActionId));for(const id of ['sbTemplate','sbTestAction']){const el=$('#'+id),old=el.value;el.innerHTML=opts([['','Aktion auswählen'],...filtered.map(a=>[a.id,a.name])],old||c.tiktokActionId);}};
  const refresh=async()=>{const st=await api.streamerbotStatus();if(!box.isConnected)return;$('#sbState').textContent=st.connected?'Verbunden · Streamer.bot '+(st.version||'')+' · '+st.actions.length+' Aktionen':st.error||'Nicht verbunden.';actions=st.actions||[];fill();};
  $('#sbRefresh').onclick=safely(refresh);$('#sbDisconnect').onclick=safely(async()=>{await api.streamerbotDisconnect();await refresh();});
  $('#sbConnect').onclick=safely(async()=>{if($('#sbPassword').value)await api.streamerbotPassword($('#sbPassword').value);await saveAndSync({streamerbot:{...S.config.streamerbot,url:$('#sbUrl').value.trim(),autoConnect:$('#sbAuto').checked,tipProvider:$('#sbProvider').value,tiktokEvents:$('#sbTikEvents').value}});const r=await api.streamerbotConnect();await refresh();if(!r.ok)throw new Error(r.error);});
  $('#sbActions').onclick=safely(async()=>{const r=await api.streamerbotActions();if(r.ok===false)throw new Error(r.error);await refresh();});$('#sbSearch').oninput=fill;
  $('#sbSaveTemplate').onclick=safely(async()=>{const id=$('#sbTemplate').value;if(!actions.some(a=>a.id===id&&a.enabled))throw new Error('Eine aktivierte Aktion auswählen.');await saveAndSync({streamerbot:{...S.config.streamerbot,tiktokActionId:id}});$('#sbTemplateState').textContent='Gemeinsame Vorlage gespeichert. Jeder TikTok-Broadcast übergibt seinen eigenen Text als message.';});
  $('#sbCopyTemplate').onclick=safely(async()=>{await api.copyText(TEMPLATE);toast('C#-Vorlage kopiert.');});
  const args=()=>({message:$('#sbMessage').value});const showArgs=()=>$('#sbArgs').textContent=JSON.stringify(args(),null,2);$('#sbMessage').oninput=showArgs;showArgs();
  $('#sbPreview').onclick=()=>$('#sbTestResult').textContent='Vorschau – keine Ausführung: '+JSON.stringify({actionId:$('#sbTestAction').value,args:args()});
  $('#sbExecute').onclick=safely(async()=>{const actionId=$('#sbTestAction').value;if(!actionId)throw new Error('Aktion auswählen.');const b=$('#sbExecute');b.disabled=true;try{const r=await api.testAutomationAction({type:'streamerbot',actionId,args:args(),timeoutMs:15000});if(!r.ok)throw new Error(r.error);$('#sbTestResult').textContent='Streamer.bot hat den Auftrag angenommen. Ausführung und Zustellung im TikTok-Chat sind damit nicht bestätigt.';}finally{b.disabled=false;}});refresh().catch(()=>{});
 };
 let draft=null,host=null,dirty=false,editIndex=-1,stepDirty=false,stepDrafts=new Map(),step={type:'chat',text:'',platform:'same'};
 const resetStep=()=>{editIndex=-1;stepDirty=false;stepDrafts.clear();step={type:'chat',text:'',platform:'same'};};
 const newDraft=()=>({id:null,name:'',description:'',queueMode:'queue',failurePolicy:'stop-sequence',enabled:true,actions:[]});
 const types=[['chat','Chat-Nachricht'],['tts','Text vorlesen'],['media','Ton oder Video'],['mediapool','Medium aus Pool'],['chat-widget','Chat-Widget / Wunschgeschenke'],['discord','Discord-Nachricht'],['streamerbot','Streamer.bot-Aktion'],['delay','Wartezeit'],['overlay','OBS-Overlay'],['obs','OBS-Aktion'],['key-action','Gespeicherte Tastenkombination'],['hotkey','Tastenkombination an Programm'],['mouse','Rechtsklick an Programm']];
 function mount(nextHost=host){
  host=nextHost;if(!host)return;draft??=newDraft();$('#chainEditor')?.remove();const box=document.createElement('section');box.className='panel-section';box.id='chainEditor';host.append(box);
  box.innerHTML='<details '+(draft.id||draft.name?'open':'')+'><summary><b>Gemeinsame Aktionsketten</b></summary><p>Events, Commands und Eingabe-Hotkeys können denselben gespeicherten Ablauf verwenden.</p><div class="form-grid">'+field('Name','chainName',draft.name)+field('Beschreibung','chainDescription',draft.description)+choice('Bei erneutem Aufruf','chainQueue',[['queue','Nacheinander'],['discard','Während Ausführung verwerfen'],['coalesce','Nur letzten wartenden Aufruf behalten'],['parallel','Parallel']],draft.queueMode)+choice('Bei Fehler','chainFailure',[['stop-sequence','Abbrechen'],['continue','Nächsten Schritt ausführen']],draft.failurePolicy)+'</div>'+check('Kette aktiv','chainEnabled',draft.enabled!==false)+'<div>'+draft.actions.map((a,i)=>'<div class="list-row"><span>'+(i+1)+'. <b>'+esc(types.find(x=>x[0]===a.type)?.[1]||a.type)+'</b> · '+esc(a.text||a.actionId||a.widgetId||a.mediaId||a.poolId||(a.type==='delay'?a.ms+' ms':''))+'</span><label><input type="checkbox" data-step-enabled="'+i+'" '+(a.enabled!==false?'checked':'')+'>Aktiv</label><button data-step-edit="'+i+'">Bearbeiten</button><button data-step-copy="'+i+'">Duplizieren</button><button data-step-up="'+i+'" '+(i===0?'disabled':'')+'>↑</button><button data-step-down="'+i+'" '+(i===draft.actions.length-1?'disabled':'')+'>↓</button><button data-step-delete="'+i+'">Entfernen</button></div>').join('')+'</div><fieldset><legend>'+(editIndex>=0?'Schritt bearbeiten':'Schritt hinzufügen')+'</legend>'+choice('Aktion','chainType',types.some(x=>x[0]===step.type)?types:[...types,[step.type,'Bestehende Aktion: '+step.type]],step.type)+'<div id="chainStepFields"></div><button id="chainAdd">Schritt übernehmen</button><button id="chainCancelStep">Neuer Schritt</button></fieldset><div class="toolbar"><button id="chainSave" class="primary">Kette speichern</button><button id="chainNew">Neue Kette</button><button id="chainPreview">Nur Vorschau</button><button id="chainStop">Alle Aktionen stoppen</button><button id="chainStatus">Laufstatus</button></div><p id="chainDraftState">'+(dirty?'Ungespeicherter Entwurf':'')+'</p><pre id="chainRunState"></pre></details><h4>Gespeicherte Abläufe</h4>'+(S.config.actionChains||[]).map(c=>'<div class="list-row"><b>'+esc(c.name)+'</b><span>'+c.actions.length+' Schritte · '+(c.enabled!==false?'Aktiv':'Aus')+'</span><button data-chain-edit="'+esc(c.id)+'">Bearbeiten</button><button data-chain-copy="'+esc(c.id)+'">Duplizieren</button><button data-chain-test="'+esc(c.id)+'">Jetzt ausführen</button><button data-chain-delete="'+esc(c.id)+'">Löschen</button></div>').join('');
  box.querySelectorAll('[data-step-edit]').forEach(button=>{const i=Number(button.dataset.stepEdit),action=draft.actions[i];if(action.type==='key-action'){const label=keyActions().find(x=>x.id===action.keyActionId)?.name||'Tastenkombination fehlt';button.parentElement.querySelector('span').innerHTML=(i+1)+'. <b>Gespeicherte Tastenkombination</b> · '+esc(label);}});
  const changed=()=>{dirty=true;$('#chainDraftState').textContent='Ungespeicherter Entwurf';};
  const capture=()=>{draft={...draft,name:$('#chainName').value,description:$('#chainDescription').value,queueMode:$('#chainQueue').value,failurePolicy:$('#chainFailure').value,enabled:$('#chainEnabled').checked};changed();};
  ['chainName','chainDescription','chainQueue','chainFailure','chainEnabled'].forEach(id=>$('#'+id).oninput=capture);
  function fields(){const t=step.type;let html='';
   if(['chat','tts','discord','overlay'].includes(t))html+='<label>Text<textarea id="stepText">'+esc(step.text||'')+'</textarea></label>'+choice('Platzhalter einfügen','stepPlaceholder',[['','Auswählen'],['{username}','Nutzername'],['{user}','Anzeigename'],['{platform}','Plattform'],['{args}','Befehlsargumente']],'');
   if(t==='chat')html+=choice('Antwortziel','stepPlatform',[['same','Herkunftsplattform'],['twitch','Twitch'],['tiktok','TikTok'],['youtube','YouTube'],['cng','CNG – lokales Overlay'],['internal','Lokaler Chat']],step.platform||'same');
   if(t==='media')html+=choice('Medium','stepMedia',(S.config.media||[]).map(m=>[m.id,m.name]),step.mediaId);
   if(t==='key-action')html+=choice('Gespeicherte Tastenkombination','stepKeyAction',step.keyActionId&&!keyActions().some(x=>x.id===step.keyActionId)?[...keyActionOptions(),[step.keyActionId,'Nicht mehr vorhanden: '+step.keyActionId]]:keyActionOptions(),step.keyActionId)+'<p>Unter Hotkeys / Multi-Action zuerst eine Tastenkombination für Events und Stream Deck speichern.</p>';
   if(t==='mediapool')html+=choice('Medien-Pool','stepPool',(S.config.mediaPools||[]).map(m=>[m.id,m.name]),step.poolId);
   if(t==='hotkey')html+=field('Zielprozess','stepProcess',step.process)+field('Tastenkombination','stepKeys',step.keys)+choice('Tastenformat','stepKeyFormat',[['','Gespeichertes Tastenformat beibehalten'],['chord','Tastenkombination (z. B. Control+K oder K+RButton)'],['legacy','Bisheriges SendKeys-Format']],step.keyFormat||'')+field('Tastendauer (ms)','stepHold',step.holdMs??100,'number')+'<button type="button" id="stepRecord">Tastenkombination aufnehmen</button><button type="button" id="stepCancelRecord" data-cancel-record>Aufnahme beenden</button><span id="stepRecordStatus" role="status"></span>';
   if(t==='mouse')html+=field('Zielprozess','stepProcess',step.process)+'<p>Ein rechter Mausklick im gewählten Programm.</p>';
   if(t==='delay')html+=field('Wartezeit in Millisekunden','stepDelay',step.ms||0,'number');
   if(t==='streamerbot')html+=choice('Aktion','stepSB',[[step.actionId||'',step.actionId||'Verbindung wird gelesen…']],step.actionId)+field('Nachricht als Argument message','stepMessage',step.args?.message||'{message}')+check('Auf zusätzliche Batto-Abschlussmeldung warten (nur mit Abschluss-Bridge)','stepWait',step.waitForCompletion===true);
   if(t==='chat-widget')html+=choice('Anzeige','stepWidget',[['wishlist','Wunschgeschenke'],...(S.config.chatExtras?.widgets||[]).map(w=>[w.id,w.name])],step.kind==='wishlist'?'wishlist':step.widgetId)+check('Einblenden','stepVisible',step.visible!==false)+field('Dauer (ms); 0 verwendet gespeicherte Dauer','stepDuration',step.durationMs||0,'number');
   if(t==='overlay')html+=check('Einblenden','stepVisible',step.visible!==false);
   if(t==='obs')html+=field('OBS-Anfrage','stepRequest',step.request)+'<label>Parameter als JSON<textarea id="stepData">'+esc(step.dataDraft??JSON.stringify(step.data||{}))+'</textarea></label>';
   html+=choice('Bei Fehler in diesem Schritt','stepFailure',[['','Einstellung der Kette'],['stop-sequence','Abbrechen'],['continue','Fortsetzen']],step.failurePolicy||'')+field('Maximale Wartezeit (ms)','stepTimeout',step.timeoutMs||30000,'number');$('#chainStepFields').innerHTML=html;
   const remember=()=>{
    if($('#stepText'))step.text=$('#stepText').value;if($('#stepPlatform'))step.platform=$('#stepPlatform').value;if($('#stepMedia'))step.mediaId=$('#stepMedia').value;if($('#stepPool'))step.poolId=$('#stepPool').value;if($('#stepDelay'))step.ms=Number($('#stepDelay').value);
    if($('#stepProcess'))step.process=$('#stepProcess').value;if($('#stepKeys')){step.keys=$('#stepKeys').value;if($('#stepKeyFormat').value)step.keyFormat=$('#stepKeyFormat').value;else delete step.keyFormat;step.holdMs=Number($('#stepHold').value);}
    if($('#stepKeyAction'))step.keyActionId=$('#stepKeyAction').value;
    if($('#stepSB')){step.actionId=$('#stepSB').value;step.args={...step.args,message:$('#stepMessage').value};step.waitForCompletion=$('#stepWait').checked;}
    if($('#stepWidget')){const value=$('#stepWidget').value;step.kind=value==='wishlist'?'wishlist':'widget';step.widgetId=value==='wishlist'?'':value;step.durationMs=Number($('#stepDuration').value);}
    if($('#stepVisible'))step.visible=$('#stepVisible').checked;if($('#stepRequest')){step.request=$('#stepRequest').value;step.dataDraft=$('#stepData').value;}
    step.failurePolicy=$('#stepFailure').value;step.timeoutMs=Number($('#stepTimeout').value);stepDirty=true;changed();
   };
   $('#chainStepFields').querySelectorAll('input,select,textarea').forEach(el=>{el.oninput=remember;el.onchange=remember;});
   $('#stepPlaceholder')?.addEventListener('change',()=>{$('#stepText').value+=$('#stepPlaceholder').value;$('#stepPlaceholder').value='';remember();});
   $('#stepRecord')?.addEventListener('click',safely(()=>recordCombination($('#stepKeys'),$('#stepRecordStatus'),box,()=>{$('#stepKeyFormat').value='chord';remember();})));
   $('#stepCancelRecord')?.addEventListener('pointerdown',cancelRecording);$('#stepCancelRecord')?.addEventListener('click',cancelRecording);
   if(t==='streamerbot')api.streamerbotStatus().then(st=>{if($('#stepSB'))$('#stepSB').innerHTML=opts([['','Aktion auswählen'],...(st.actions||[]).filter(a=>a.enabled).map(a=>[a.id,a.name])],step.actionId);}).catch(()=>{});
  }
  fields();$('#chainType').onchange=()=>{stepDrafts.set(step.type,structuredClone(step));const type=$('#chainType').value;step=structuredClone(stepDrafts.get(type)||{type,enabled:true,...(type==='hotkey'?{keyFormat:'chord'}:{}),...(type==='mouse'?{button:'right'}:{})});stepDirty=true;changed();fields();};
  $('#chainAdd').onclick=safely(async()=>{requireRecordingFinished();capture();const t=step.type,a={...step,enabled:step.enabled!==false,timeoutMs:Number($('#stepTimeout').value)};if($('#stepFailure').value)a.failurePolicy=$('#stepFailure').value;else delete a.failurePolicy;
   if($('#stepText'))a.text=$('#stepText').value;if(t==='chat')a.platform=$('#stepPlatform').value;if(t==='media')a.mediaId=$('#stepMedia').value;if(t==='mediapool')a.poolId=$('#stepPool').value;if(t==='delay')a.ms=Number($('#stepDelay').value);
   if(t==='hotkey'){a.process=$('#stepProcess').value;a.keys=$('#stepKeys').value;if($('#stepKeyFormat').value)a.keyFormat=$('#stepKeyFormat').value;else delete a.keyFormat;a.holdMs=Number($('#stepHold').value);if(!a.process.trim()||!a.keys.trim())throw Error('Zielprozess und Tastenkombination eingeben.');if(a.keyFormat==='chord')a.keys=requireCombination(a.keys);}
   if(t==='key-action'){a.keyActionId=$('#stepKeyAction').value;if(!keyActions().some(x=>x.id===a.keyActionId))throw Error('Bitte eine vorhandene Tastenkombination auswählen.');}
   if(t==='mouse'){a.process=$('#stepProcess').value;a.button='right';if(!a.process.trim())throw Error('Zielprozess eingeben.');}
   if(t==='streamerbot'){a.actionId=$('#stepSB').value;if(!a.actionId)throw new Error('Streamer.bot-Aktion auswählen.');a.args={...step.args,message:$('#stepMessage').value};a.waitForCompletion=$('#stepWait').checked;}
   if(t==='chat-widget'){const value=$('#stepWidget').value;a.kind=value==='wishlist'?'wishlist':'widget';a.widgetId=value==='wishlist'?'':value;a.visible=$('#stepVisible').checked;a.durationMs=Number($('#stepDuration').value);}
   if(t==='overlay')a.visible=$('#stepVisible').checked;if(t==='obs'){a.request=$('#stepRequest').value;a.data=JSON.parse($('#stepData').value||'{}');delete a.dataDraft;}
   if(editIndex<0)draft.actions.push(a);else draft.actions[editIndex]=a;resetStep();mount();});
  $('#chainCancelStep').onclick=()=>{if(stepDirty&&!confirm('Nicht übernommene Schritteinträge verwerfen?'))return;resetStep();mount();};
  const operations={edit:i=>{editIndex=i;stepDirty=false;stepDrafts.clear();step=structuredClone(draft.actions[i]);},copy:i=>draft.actions.splice(i+1,0,structuredClone(draft.actions[i])),up:i=>{[draft.actions[i-1],draft.actions[i]]=[draft.actions[i],draft.actions[i-1]];},down:i=>{[draft.actions[i+1],draft.actions[i]]=[draft.actions[i],draft.actions[i+1]];},delete:i=>draft.actions.splice(i,1)};
  for(const [op,fn] of Object.entries(operations))box.querySelectorAll('[data-step-'+op+']').forEach(b=>b.onclick=()=>{if(stepDirty&&!confirm('Nicht übernommene Schritteinträge verwerfen?'))return;capture();fn(Number(b.getAttribute('data-step-'+op)));if(op!=='edit')resetStep();mount();});
  box.querySelectorAll('[data-step-enabled]').forEach(b=>b.onchange=()=>{draft.actions[Number(b.dataset.stepEnabled)].enabled=b.checked;changed();});
  $('#chainSave').onclick=safely(async()=>{requireRecordingFinished();if(stepDirty)throw Error('Den bearbeiteten Schritt zuerst mit „Schritt übernehmen“ hinzufügen.');capture();if(!draft.name.trim())throw new Error('Namen eingeben.');if(!draft.actions.length)throw new Error('Mindestens einen Schritt hinzufügen.');const item={...structuredClone(draft),id:draft.id||cryptoId()},all=[...(S.config.actionChains||[])],i=all.findIndex(c=>c.id===item.id);if(i<0)all.push(item);else all[i]=item;await saveAndSync({actionChains:all},'Aktionskette gespeichert.');draft=item;dirty=false;mount();$('#chainEditor details').open=false;});
  $('#chainNew').onclick=()=>{if(dirty&&!confirm('Ungespeicherten Kettenentwurf verwerfen?'))return;draft=newDraft();dirty=false;resetStep();mount();$('#chainEditor details').open=true;};
  $('#chainPreview').onclick=()=>$('#chainRunState').textContent='Vorschau – keine Ausführung\n'+JSON.stringify({platform:'twitch',username:'Beispielnutzer',args:'Beispiel',actions:draft.actions},null,2);
  $('#chainStop').onclick=safely(()=>api.cancelAllAutomations());$('#chainStatus').onclick=safely(async()=>$('#chainRunState').textContent=JSON.stringify(await api.chainStatus(),null,2));
  box.querySelectorAll('[data-chain-edit],[data-chain-copy]').forEach(b=>b.onclick=()=>{if(dirty&&!confirm('Ungespeicherten Kettenentwurf verwerfen?'))return;draft=structuredClone(S.config.actionChains.find(c=>c.id===(b.dataset.chainEdit||b.dataset.chainCopy)));if(b.dataset.chainCopy){draft.id=null;draft.name+=' Kopie';draft.enabled=false;}dirty=!!b.dataset.chainCopy;resetStep();mount();});
  box.querySelectorAll('[data-chain-test]').forEach(b=>b.onclick=safely(async()=>{const r=await api.triggerChain(b.dataset.chainTest);if(!r.ok||!r.result?.ok)throw new Error(r.error||r.result?.error||'Aktion nicht ausgeführt.');toast('Aktionskette verarbeitet. Details unter Laufstatus.');}));
  box.querySelectorAll('[data-chain-delete]').forEach(b=>b.onclick=safely(async()=>{if(!confirm('Kette löschen? Zugeordnete Auslöser können sie danach nicht mehr starten.'))return;await saveAndSync({actionChains:S.config.actionChains.filter(c=>c.id!==b.dataset.chainDelete)});mount();}));
 }
 window.BattoActionEditor={mount};
 document.addEventListener('batto:view',cancelRecording);
 let keyDraft=null,keySaving=false;
 renderHotkeysModule=function(){
  const root=$('#hotkeysModule'),d=keyDraft||{name:'',accelerator:'',scope:'global',triggerMode:'down',passthrough:true,debounceMs:300,enabled:true};
  root.innerHTML='<section class="panel-section"><h3>Tastatur und PC-Maus als Auslöser</h3><p>Startet gespeicherte Aktionsketten. Während der Aufnahme werden keine Aktionen ausgelöst.</p><div class="form-grid">'+field('Name','inputKeyName',d.name)+field('Kombination','inputKey',d.accelerator)+'</div><div class="toolbar"><button id="inputRecord">Kombination aufnehmen</button><button id="inputCancelRecord">Aufnahme beenden</button></div><p id="inputRecordStatus" role="status"></p><div class="form-grid">'+choice('Geltungsbereich','inputScope',[['global','Global (auch minimiert)'],['app','Nur im aktiven Batto-Fenster']],d.scope)+choice('Auslösen','inputMode',[['down','Einmal beim Drücken / Radimpuls'],['up','Beim Loslassen'],['repeat','Wiederholen beim Halten']],d.triggerMode)+field('Wiederholungsschutz (ms)','inputDebounce',d.debounceMs,'number')+choice('Aktionskette','inputChain',chainList(),d.chainId)+'</div>'+check('Originaleingabe weitergeben','inputPass',d.passthrough!==false)+check('Alle Aktionen stoppen','inputStop',d.stopAll)+check('Belegung aktiv','inputEnabled',d.enabled!==false)+'<p>Linke, rechte, mittlere und seitliche Maustasten (XButton1 / XButton2), Mausrad in vier Richtungen, Tastatur und Zusatztasten. Zusätzliche Maustasten bei Bedarf in der Maussoftware zuordnen. Mausrad: einzelne Impulse.</p><div class="toolbar"><button id="inputSave" class="primary">Belegung speichern</button><button id="inputNew">Neue Belegung</button><button id="inputTest">Aktionskette jetzt testen</button></div><p id="inputKeyStatus" role="status"></p></section><section class="panel-section"><h3>Gespeicherte Belegungen</h3>'+(S.config.hotkeys||[]).map(k=>'<div class="list-row"><span><b>'+esc(k.name||k.accelerator)+'</b> · '+esc(k.accelerator)+' · '+(k.scope==='app'?'Batto-Fenster':'Global')+' · '+(k.enabled!==false?'Aktiv':'Aus')+'</span><button data-key-edit="'+esc(k.id)+'">Bearbeiten</button><button data-key-toggle="'+esc(k.id)+'">'+(k.enabled===false?'Aktivieren':'Deaktivieren')+'</button><button data-key-delete="'+esc(k.id)+'">Löschen</button></div>').join('')+'</section><div id="hotkeyChains"></div>';
  const read=()=>({...d,name:$('#inputKeyName').value,accelerator:$('#inputKey').value.trim(),scope:$('#inputScope').value,triggerMode:$('#inputMode').value,passthrough:$('#inputPass').checked,debounceMs:Number($('#inputDebounce').value),chainId:$('#inputStop').checked?undefined:$('#inputChain').value,stopAll:$('#inputStop').checked,enabled:$('#inputEnabled').checked});
  $('#inputKey').placeholder='F8, Control+F8 oder K+RButton';
  if(d.chainId&&!(S.config.actionChains||[]).some(x=>x.id===d.chainId))$('#inputChain').value='';
  $('#inputKey').insertAdjacentHTML('afterend','<small>Direkt eingeben oder aufnehmen. Strg, Alt, Umschalt und Windows brauchen eine weitere Taste oder Maustaste.</small>');
  const mouseChoice=document.createElement('div');mouseChoice.className='toolbar';mouseChoice.innerHTML=choice('Maustaste zur Kombination hinzufügen','inputMouse',[['','Bitte wählen'],['LButton','Linke Maustaste'],['RButton','Rechte Maustaste'],['MButton','Mittlere Maustaste'],['XButton1','Seitliche Maustaste 1'],['XButton2','Seitliche Maustaste 2'],['WheelUp','Mausrad nach oben'],['WheelDown','Mausrad nach unten'],['WheelLeft','Mausrad nach links'],['WheelRight','Mausrad nach rechts']],'')+'<button type="button" id="inputAddMouse">Maustaste hinzufügen</button>';
  $('#inputRecord').parentElement.after(mouseChoice);
  $('#inputSave').parentElement.insertAdjacentHTML('beforebegin','<p id="inputValidation" role="status"></p>');
  root.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',()=>{keyDraft=read();$('#inputValidation').textContent='';}));
  $('#inputAddMouse').onclick=()=>{const mouse=$('#inputMouse').value;if(!mouse)return;const parts=$('#inputKey').value.split('+').map(x=>x.trim()).filter(Boolean);if(!parts.some(x=>x.toLowerCase()===mouse.toLowerCase()))parts.push(mouse);$('#inputKey').value=parts.join('+');keyDraft=read();$('#inputValidation').textContent='Kombination: '+keyDraft.accelerator;};
  $('#inputRecord').onclick=safely(()=>recordCombination($('#inputKey'),$('#inputRecordStatus'),root,()=>{keyDraft=read();$('#inputValidation').textContent='';}));
  $('#inputCancelRecord').setAttribute('data-cancel-record','');
  $('#inputCancelRecord').onpointerdown=cancelRecording;$('#inputCancelRecord').onclick=cancelRecording;
  $('#inputSave').onclick=safely(async()=>{
   if(keySaving)return;requireRecordingFinished();const item={...read(),id:d.id||cryptoId()};keyDraft={...item};
   try{item.accelerator=requireCombination(item.accelerator);}
   catch(error){$('#inputValidation').textContent=error.message;$('#inputKey').focus();throw error;}
   if(!item.stopAll&&!(S.config.actionChains||[]).some(x=>x.id===item.chainId)){const message='Bitte eine vorhandene Aktionskette auswählen oder „Alle Aktionen stoppen“ aktivieren.';$('#inputValidation').textContent=message;$('#inputChain').focus();throw Error(message);}
   keySaving=true;$('#inputSave').disabled=true;
   try{const all=[...(S.config.hotkeys||[])],index=all.findIndex(k=>k.id===item.id);if(index<0)all.push(item);else all[index]=item;await saveAndSync({hotkeys:all},'Belegung gespeichert.');
    keyDraft=structuredClone((S.config.hotkeys||[]).find(k=>k.id===item.id)||item);renderHotkeysModule();$('#inputValidation').textContent='Gespeichert: '+keyDraft.accelerator+'. Du bearbeitest weiterhin diese Belegung.';
   }catch(error){const message=String(error?.message||error).replace(/^Error invoking remote method '[^']+':\s*(?:Error:\s*)?/,'');if($('#inputValidation'))$('#inputValidation').textContent=message;throw Error(message);}
   finally{keySaving=false;if($('#inputSave'))$('#inputSave').disabled=false;}
  });
  $('#inputSave').disabled=keySaving;
  $('#inputNew').onclick=()=>{cancelRecording();keyDraft=null;renderHotkeysModule();};
  $('#inputTest').onclick=safely(async()=>{requireRecordingFinished();const item=read();if(item.stopAll){await api.cancelAllAutomations();toast('Aktionen gestoppt.');return;}if(!item.chainId)throw new Error('Aktionskette auswählen.');const r=await api.triggerChain(item.chainId);if(!r.ok||!r.result?.ok)throw new Error(r.error||r.result?.error||'Aktionskette nicht ausgeführt.');toast('Aktionskette verarbeitet.');});
  root.querySelectorAll('[data-key-edit]').forEach(b=>b.onclick=()=>{keyDraft=structuredClone(S.config.hotkeys.find(k=>k.id===b.dataset.keyEdit));renderHotkeysModule();});
  root.querySelectorAll('[data-key-toggle]').forEach(b=>b.onclick=safely(async()=>{const id=b.dataset.keyToggle;await saveAndSync({hotkeys:S.config.hotkeys.map(k=>k.id===id?{...k,enabled:k.enabled===false}:k)});if(keyDraft?.id===id){const saved=S.config.hotkeys.find(k=>k.id===id);if(saved)keyDraft={...keyDraft,enabled:saved.enabled};}renderHotkeysModule();}));
  root.querySelectorAll('[data-key-delete]').forEach(b=>b.onclick=safely(async()=>{const id=b.dataset.keyDelete;await saveAndSync({hotkeys:S.config.hotkeys.filter(k=>k.id!==id)});if(keyDraft?.id===id)keyDraft=null;renderHotkeysModule();}));
  root.querySelectorAll('[data-key-edit]').forEach(button=>{const transfer=document.createElement('button');transfer.type='button';transfer.dataset.keyToOutput=button.dataset.keyEdit;transfer.textContent='Für Events übernehmen';transfer.onclick=safely(()=>{const item=(S.config.hotkeys||[]).find(x=>x.id===transfer.dataset.keyToOutput);if(item)prefillKeyAction(item);});button.after(transfer);});
  const refresh=async()=>{const items=await api.hotkeyStatus();if(root.isConnected&&$('#inputKeyStatus'))$('#inputKeyStatus').textContent=items.map(x=>x.accelerator+': '+(x.pending?'Wird registriert…':x.registered?'Bereit':x.error)).join(' · ');};refresh().catch(()=>{});setTimeout(()=>refresh().catch(()=>{}),1200);mount($('#hotkeyChains'));
  renderKeyActions(root);
 };
})();
