'use strict';
(()=>{
 const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={twitch:'Twitch',tiktok:'TikTok',youtube:'YouTube',cng:'CNG'},labels={addModerator:'Als Moderator hinzufügen',removeModerator:'Moderatorrechte entfernen',mute:'Stummschalten',unmute:'Entstummen',block:'Im Kanal sperren',unblock:'Entsperren'};
 let snapshot={archive:{},viewers:{},moderation:{}},history=[],loading=null,archiveRows=[],archiveFilters={},archiveOffset=0,contextGeneration=0,archiveGeneration=0;
 const state=p=>snapshot.moderation?.[p]||{platform:p,actions:{},moderators:[],muted:[],blocked:[],listMode:'unavailable'};
 const stamp=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'Nicht bekannt':d.toLocaleString('de-DE',{timeZoneName:'short'});};
 const error=(target,e)=>{if(target){target.textContent=String(e?.error||e?.message||e||'Unbekannter Fehler');target.classList.add('error');}};
 async function call(fn,...args){try{return await fn(...args);}catch(e){return{ok:false,error:e.message};}}
 async function reload(){if(loading)return loading;loading=(async()=>{const s=await call(api.communityStatus);if(s?.ok===false){error(q('#communityStatus'),s);return;}snapshot=s.result||s;const h=await call(api.moderationHistory,{});if(h.ok)history=h.items||[];renderModeration();renderHistory();renderViewers();renderStorage();if(S.view==='moderation')renderModerationModule();})();try{await loading;}finally{loading=null;}}
 function tabs(){return Object.keys(names).map(p=>`<button data-community-platform="${p}" class="${S.modTab===p?'active':''}">${names[p]}</button>`).join('');}
 function bindTabs(root){root?.querySelectorAll('[data-community-platform]').forEach(b=>b.onclick=()=>{S.modTab=b.dataset.communityPlatform;renderModeration();renderModerationModule(true);});}
 function entries(p){const st=state(p),status=st.error||(st.connected?`Angemeldet: ${st.identity?.username||st.identity?.id||'Konto'} · Kanal ${st.channelId||'nicht gewählt'}`:'Moderationskonto nicht verbunden.');return `<div class="community-status">${html(status)}</div><div class="community-list-title">${st.listMode==='complete'?(st.bansMode==='complete'?'Bestätigte Plattformlisten':'Moderatoren vollständig · Sperren nur bekannte Vorgänge'):st.listMode==='observed'?'Erkannte Moderatoren · keine vollständige Plattformliste':'Plattformlisten noch nicht verfügbar'}${st.confirmedAt?' · '+html(stamp(st.confirmedAt)):''}</div><div class="community-mod-list">${[['moderators','Moderatoren','removeModerator'],['muted','Stumm','unmute'],['blocked','Gesperrt','unblock']].map(([key,title,action])=>`<div><strong>${title} (${(st[key]||[]).length})</strong>${st.connected&&key!=='moderators'&&st.bansMode!=='complete'?'<small>Nur bekannte Vorgänge · keine vollständige Plattformliste</small>':''}${(st[key]||[]).slice(0,80).map(row=>`<div class="community-record"><b>${html(row.displayName||row.username||row.userId)}</b><small>ID: ${html(row.userId)}</small>${row.reason?`<small>Grund: ${html(row.reason)}</small>`:''}${row.expiresAt?`<small>Bis ${html(stamp(row.expiresAt))}</small>`:''}<button data-community-user="${html(row.userId)}" data-community-action="${action}" ${st.actions?.[action]?'':'disabled'}>${labels[action]}</button><button data-context-user="${html(row.userId)}">Verlauf</button></div>`).join('')||'<div class="community-empty">Keine bestätigten Einträge.</div>'}</div>`).join('')}</div>`;}
 function bindRows(root){root?.querySelectorAll('[data-community-action]').forEach(b=>b.onclick=()=>{const st=state(S.modTab),row=[...(st.moderators||[]),...(st.muted||[]),...(st.blocked||[])].find(r=>r.userId===b.dataset.communityUser);if(row)doModeration({...row,platform:S.modTab,channelId:row.channelId||st.channelId},b.dataset.communityAction,row.reason||'');});root?.querySelectorAll('[data-context-user]').forEach(b=>b.onclick=()=>openArchive({platform:S.modTab,userId:b.dataset.contextUser,channelId:state(S.modTab).channelId}));}
 renderModeration=function(){const el=q('#modTabs'),cols=q('#modColumns');if(!el||!cols)return;el.innerHTML=tabs();cols.classList.remove('mod-columns');cols.innerHTML=entries(S.modTab);bindTabs(el);bindRows(cols);};
 function historyTable(rows){return rows.slice(0,100).map(e=>`<tr><td>${html(stamp(e.timestamp||e.ts))}</td><td>${html(e.displayName||e.username||e.targetUser||e.userId)}</td><td>${html(labels[e.action]||e.action)}${e.durationSeconds?`<small> ${e.durationSeconds} s</small>`:''}</td><td>${html(e.reason||'Von der Plattform nicht mitgeteilt')}</td><td class="community-table-note">${html(e.lastMessage||e.excerpt||'Nicht aufgezeichnet')}<small>Zuletzt empfangener Text, kein bewiesener Sperrgrund.</small></td><td>${html(e.initiator||e.requestedBy||e.actor||'Nicht bekannt')}<small> Konto: ${html(e.executor||e.accountId||'Nicht bekannt')}</small></td><td>${html(names[e.platform]||e.platform)}</td><td>${html(e.result||e.status||'Unklar')}${e.error?`<small>${html(e.error)}</small>`:''}<button data-community-incident="${html(e.id||e.actionId)}">Kontext</button></td></tr>`).join('')||'<tr><td colspan="8">Noch kein bestätigter Moderationsverlauf.</td></tr>';}
 function bindHistory(root){root?.querySelectorAll('[data-community-incident]').forEach(b=>b.onclick=()=>{const e=history.find(x=>(x.id||x.actionId)===b.dataset.communityIncident);if(e)openArchive({platform:e.platform,channelId:e.channelId,from:new Date(new Date(e.timestamp||e.ts).getTime()-300000).toISOString(),to:new Date(new Date(e.timestamp||e.ts).getTime()+300000).toISOString()});});}
 renderHistory=function(){const body=q('#historyBody');if(!body)return;const filter=q('#historyPlatform')?.value||'all';body.innerHTML=historyTable(history.filter(e=>filter==='all'||e.platform===filter));bindHistory(body);};
 function authMarkup(){const cfg=S.config?.community?.moderation||{},p=S.modTab;return `<details class="community-auth"><summary>Moderationskonto verbinden</summary>${p==='twitch'?`<p>Die Moderationsanmeldung ist getrennt vom vorhandenen Twitch-Chatfenster.</p><label>Twitch Client-ID deiner Anwendung<input id="communityClientId" value="${html(cfg.twitch?.clientId||S.config.platforms.twitch.clientId||'')}"></label><label>Kanalname<input id="communityChannel" value="${html(cfg.twitch?.channel||S.config.platforms.twitch.channel||'')}"></label><button id="communityConnect">Mit Twitch anmelden</button><div id="communityLogin" class="community-status" role="status">${snapshot.login?.status==='pending'?`Code: <strong>${html(snapshot.login.code)}</strong> <button id="communityOpenLogin">Anmeldung öffnen</button>`:html(snapshot.login?.error||'')}</div>`:p==='youtube'?`<p>YouTube benötigt ein berechtigtes OAuth-Konto für den eigenen LIVE-Chat.</p><label>LIVE-Chat-ID<input id="communityYoutubeChat" value="${html(cfg.youtube?.liveChatId||S.config.platforms.youtube.liveChatId||'')}"></label><label>OAuth-Zugriffstoken<input id="communityYoutubeToken" type="password" autocomplete="off" placeholder="Wird geschützt gespeichert"></label><button id="communityConnect">YouTube-Konto prüfen</button>`:`<p class="community-unavailable">Plattformaktion nicht verfügbar. Die aktuelle ${names[p]}-Anbindung stellt noch keinen geprüften Moderationszugriff bereit.</p><button id="communityOpenPlatform">Plattformverwaltung öffnen</button>`}</details>`;}
 renderModerationModule=function(force=false){const el=q('#moderationModule');if(!el)return;if(!force&&(el.querySelector('.community-auth[open]')||el.contains(document.activeElement)&&document.activeElement.matches('input,select,textarea')))return;el.innerHTML=`<div class="tabs">${tabs()}</div><div class="community-toolbar"><button id="communityRefresh">Plattformstatus abgleichen</button><button id="communityDisconnect">Moderationskonto trennen</button><button id="communityArchiveOpen">Chatarchiv öffnen</button></div><div id="communityStatus" class="community-status" role="status"></div>${entries(S.modTab)}${authMarkup()}<h3>Moderationsverlauf</h3><div class="table-scroll"><table><thead><tr><th>Zeit</th><th>Name</th><th>Aktion</th><th>Grund</th><th>Chatbezug</th><th>Durch</th><th>Plattform</th><th>Ergebnis</th></tr></thead><tbody>${historyTable(history.filter(e=>e.platform===S.modTab))}</tbody></table></div>`;bindTabs(el);bindRows(el);bindHistory(el);if(q('#communityOpenLogin'))q('#communityOpenLogin').onclick=()=>api.moderationOpenLogin({platform:'twitch'});q('#communityArchiveOpen').onclick=()=>openArchive({platform:S.modTab});q('#communityRefresh').onclick=async()=>{q('#communityStatus').textContent='Status wird abgeglichen …';const r=await call(api.moderationRefresh,{platform:S.modTab});if(!r.ok)error(q('#communityStatus'),r);else await reload();};q('#communityDisconnect').onclick=async()=>{const r=await call(api.moderationDisconnect,{platform:S.modTab});if(!r.ok)error(q('#communityStatus'),r);else await reload();};q('#communityOpenPlatform')?.addEventListener('click',()=>S.modTab==='tiktok'?api.openLiveCenter():api.openExternal('https://cng-plattform.com/'));q('#communityConnect')?.addEventListener('click',async e=>{const p=S.modTab;e.currentTarget.disabled=true;const payload=p==='twitch'?{platform:p,clientId:q('#communityClientId').value.trim(),channel:q('#communityChannel').value.trim()}:{platform:p,liveChatId:q('#communityYoutubeChat').value.trim(),token:q('#communityYoutubeToken').value.trim()};const r=await call(api.moderationConnect,payload);if(q('#communityYoutubeToken'))q('#communityYoutubeToken').value='';if(!r.ok)error(q('#communityStatus'),r);else if(r.pending){q('#communityLogin').innerHTML=`Code: <strong>${html(r.code)}</strong> <button id="communityOpenLogin">Anmeldung öffnen</button>`;q('#communityOpenLogin').onclick=()=>api.moderationOpenLogin({platform:'twitch'});}else await reload();if(q('#communityConnect'))q('#communityConnect').disabled=false;});};
 function confirmAction(user,action,reason){return new Promise(resolve=>{const d=document.createElement('dialog');d.className='community-dialog';d.innerHTML=`<h3>${html(labels[action]||action)}</h3><p>${html(user.displayName||user.username||user.userId)} · ${html(names[user.platform]||user.platform)}</p><small>Kanal ${html(user.channelId||state(user.platform).channelId||'wird geprüft')} · ID ${html(user.userId||'wird anhand des Kontos geprüft')}</small>${['mute','block'].includes(action)?`<label>Grund<input name="reason" maxlength="500" value="${html(reason)}"></label>`:''}${action==='mute'?'<label>Dauer<select name="duration"><option value="600">10 Minuten</option><option value="60">1 Minute</option><option value="1800">30 Minuten</option><option value="3600">1 Stunde</option><option value="86400">1 Tag</option></select></label>':''}<div class="toolbar"><button data-cancel>Abbrechen</button><button data-confirm class="primary">Auf Plattform ausführen</button></div>`;document.body.append(d);let done=false;const finish=value=>{if(done)return;done=true;d.close();d.remove();resolve(value);};d.querySelector('[data-cancel]').onclick=()=>finish(null);d.querySelector('[data-confirm]').onclick=()=>finish({reason:d.querySelector('[name=reason]')?.value||'',durationSeconds:Number(d.querySelector('[name=duration]')?.value||600)});d.oncancel=e=>{e.preventDefault();finish(null);};d.showModal();});}
 doModeration=async function(user,action,reason=''){
  q('#contextMenu').hidden=true;if(!user)return;const st=state(user.platform);if(!user.channelId)return toast('Kanal der ausgewählten Nachricht ist noch nicht bestätigt. Bitte zuerst die Verbindung abgleichen.',true);
  if(!st.actions?.[action])return toast(st.error||'Plattformaktion nicht verfügbar. Moderationskonto und Berechtigungen prüfen.',true);
  if(user.platform==='twitch'&&!/^\d+$/.test(String(user.userId||''))){const resolved=await call(api.moderationResolve,{platform:'twitch',username:user.username,channelId:user.channelId||st.channelId});if(!resolved.ok)return toast(resolved.error,true);user={...user,...resolved};}
  const opts=await confirmAction(user,action,reason);if(!opts)return;toast('Wird ausgeführt …');const id=user.messageId||user.id,found=S.messages.find(m=>m.id===id);
  const result=await call(api.moderationPerform,{...user,...opts,action,channelId:user.channelId||st.channelId,messageId:id,lastMessage:found?.message||'',requestId:crypto.randomUUID()});
  if(!result.ok)toast(result.error||'Aktion fehlgeschlagen oder Ausgang unklar.',true);else toast('Plattform hat die Aktion bestätigt.');await reload();
 };
 document.addEventListener('contextmenu',e=>{if(!e.target.closest('.chat-user'))return;const token=++contextGeneration;const user=S.contextUser;if(!user)return;const menu=q('#contextMenu');menu.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);call(api.moderationCapabilities,{platform:user.platform,channelId:user.channelId||state(user.platform).channelId}).then(r=>{if(token!==contextGeneration)return;const actions=r.actions||r.state?.actions||r.result?.actions||state(user.platform).actions||{};menu.querySelectorAll('[data-action]').forEach(b=>b.disabled=!actions[b.dataset.action]);});});
 function renderViewers(){const pill=q('.chat-card .live-pill');if(pill){const connected=['tikfinity','twitch','youtube'].some(p=>S.adapters?.[p]?.connected);pill.innerHTML='<i></i>'+(connected?'Chat verbunden':'Chat bereit');pill.classList.toggle('offline',!connected);}const head=q('.chat-card .card-head>div');if(!head)return;let bar=q('#communityViewers');if(!bar){bar=document.createElement('div');bar.id='communityViewers';bar.className='community-viewers';head.append(bar);}const viewers=snapshot.viewers||{},settings=viewers.settings||S.config?.community?.viewers||{};bar.hidden=settings.enabled===false||(!settings.tiktok&&!settings.twitch);bar.innerHTML=['tiktok','twitch'].filter(p=>settings[p]!==false).map(p=>{const v=viewers[p]||{},state=v.state||v.status;const value=state==='offline'?'Offline':state==='stale'?'Veraltet':Number.isFinite(v.count??v.viewerCount)?Number(v.count??v.viewerCount).toLocaleString('de-DE'):'Nicht verfügbar';return `<span>${names[p]} · ${html(value)}</span>`;}).join('');}
 function renderStorage(){const host=q('.connections-card');if(!host)return;let box=q('#communityStorage');if(!box){box=document.createElement('div');box.id='communityStorage';box.className='community-storage';host.insertBefore(box,host.querySelector('[data-open-view]'));box.innerHTML='<strong>Automatische Chatspeicherung</strong><label class="switch"><input type="checkbox" id="communityRecord"><span>Aufzeichnung</span></label><div id="communityRecordingState" class="community-status" role="status"></div><button id="communityOpenArchive">Chatarchiv öffnen</button>';q('#communityRecord').onchange=async e=>{e.target.disabled=true;const r=await call(api.archiveConfig,{enabled:e.target.checked});if(!r.ok)toast(r.error,true);await reload();q('#communityRecord').disabled=false;};q('#communityOpenArchive').onclick=()=>openArchive({});}const enabled=snapshot.archive?.enabled??S.config?.community?.archive?.enabled??false;q('#communityRecord').checked=enabled;const a=snapshot.archive||{};const status=a.error?'Speicherfehler: '+a.error:a.recording?'Aufzeichnung aktiv':enabled?'Archiv wird vorbereitet · noch keine bestätigte Aufzeichnung':'Aufzeichnung aus';q('#communityRecordingState').textContent=status;if(q('#archiveCurrentStatus'))q('#archiveCurrentStatus').textContent=status;q('#communityRecordingState').classList.toggle('error',!!a.error);}
 function archiveSettings(){const a={...S.config.community.archive,...snapshot.archive},v=snapshot.viewers.settings||S.config.community.viewers;return `<details class="community-auth"><summary>Aufzeichnung, Speicherort und Zuschaueranzeige einstellen</summary><div class="community-toolbar"><label><input type="checkbox" id="archiveEnabled" ${a.enabled?'checked':''}> Vollständigen Chat aufzeichnen</label><label><input type="checkbox" id="archiveModeration" ${a.moderationEnabled?'checked':''}> Moderationsverlauf speichern</label><label><input type="checkbox" id="archiveExcerpts" ${a.excerptsEnabled?'checked':''}> Nachrichten-Auszüge speichern</label></div><div class="community-controls"><label>Speicherordner<input id="archiveDirectory" value="${html(a.directory)}" placeholder="Lokaler Batto-Datenordner"></label><label>Aufbewahrung<select id="archiveRetention">${[[0,'Keine automatische Löschung'],[7,'7 Tage'],[30,'30 Tage'],[90,'90 Tage'],[365,'1 Jahr']].map(([val,label])=>`<option value="${val}" ${a.retentionDays===val?'selected':''}>${label}</option>`).join('')}</select></label><div><button id="archiveSave" class="primary">Speichern</button></div></div><div class="community-toolbar"><label><input type="checkbox" id="viewerEnabled" ${v.enabled?'checked':''}> Zuschauer anzeigen</label><label><input type="checkbox" id="viewerTikTok" ${v.tiktok?'checked':''}> TikTok</label><label><input type="checkbox" id="viewerTwitch" ${v.twitch?'checked':''}> Twitch</label><button id="viewerSave">Zuschaueranzeige speichern</button></div><div class="community-status" role="status" id="archiveSaveFeedback"></div></details>`;}
 async function searchArchive(){const generation=++archiveGeneration;const el=q('#communityArchiveResults');if(!el)return;el.textContent='Suche …';const data=await call(api.archiveSearch,{...archiveFilters,limit:100,offset:archiveOffset});if(generation!==archiveGeneration)return;if(!data.ok){error(el,data);return;}archiveRows=data.items||[];q('#communityArchiveCount').textContent=`${data.total??archiveRows.length} Nachrichten · ${archiveOffset+1}–${archiveOffset+archiveRows.length}`;el.innerHTML=archiveRows.map((r,i)=>`<article class="community-record"><div class="community-row-head"><b>${html(r.displayName||r.username)} · ${html(names[r.platform]||r.platform)}</b><small>${html(stamp(r.timestamp))}</small></div><small>Kanal ${html(r.channelId)} · Nutzer-ID ${html(r.userId)}${r.identityVerified===false?' · noch nicht verifiziert':''}</small><p>${html(r.text)}</p><button data-archive-context="${i}">Chatkontext</button></article>`).join('')||'<p>Keine aufgezeichneten Nachrichten gefunden.</p>';el.querySelectorAll('[data-archive-context]').forEach(b=>b.onclick=async()=>{const r=archiveRows[Number(b.dataset.archiveContext)],data=await call(api.archiveContext,{platform:r.platform,channelId:r.channelId,timestamp:r.timestamp});const target=q('#communityArchiveContext');target.hidden=false;target.textContent=data.ok?(data.items||[]).map(x=>`${stamp(x.timestamp)} · ${x.displayName||x.username}: ${x.text}`).join('\n')||'Nicht aufgezeichnet.':data.error;});q('#archivePrev').disabled=archiveOffset===0;q('#archiveNext').disabled=archiveOffset+archiveRows.length>=Number(data.total||0);}
 function renderArchive(){const el=q('#communityArchiveModule');if(!el||!S.config?.community)return;const f=archiveFilters;el.innerHTML=`<div class="community-status" id="archiveCurrentStatus">${snapshot.archive.error?'Speicherfehler: '+html(snapshot.archive.error):snapshot.archive.recording?'Aufzeichnung aktiv':S.config.community.archive.enabled?'Archiv wird vorbereitet …':'Aufzeichnung aus · vorhandene Archive bleiben zugänglich'}</div><small>Speicherort: ${html(snapshot.archive.file||snapshot.archive.directory||S.config.community.archive.directory||'Lokaler Batto-Datenordner')}</small><div class="community-controls"><label>Text durchsuchen<input id="archiveQuery" value="${html(f.query)}" placeholder="Text, Emojis …"></label><label>Name oder Nutzer-ID<input id="archivePerson" value="${html(f.person||f.userId)}"></label><label>Plattform<select id="archivePlatform"><option value="">Alle Plattformen</option>${Object.keys(names).map(p=>`<option value="${p}" ${f.platform===p?'selected':''}>${names[p]}</option>`).join('')}</select></label><label>Kanal / Raum-ID<input id="archiveChannel" value="${html(f.channelId)}"></label><label>Von<input type="datetime-local" id="archiveFrom"></label><label>Bis<input type="datetime-local" id="archiveTo"></label><label>Sitzung<select id="archiveSession"><option value="">Alle Sitzungen</option></select></label></div><div class="toolbar"><button class="primary" id="archiveSearch">Suchen</button><button id="archiveReset">Filter zurücksetzen</button><select id="archiveExportFormat"><option value="txt">TXT</option><option value="csv">CSV</option><option value="json">JSON</option></select><button id="archiveExport">Ergebnisse exportieren</button></div><div class="community-status" id="communityArchiveCount" role="status"></div><div class="community-results" id="communityArchiveResults"></div><div class="toolbar"><button id="archivePrev">← Zurück</button><button id="archiveNext">Weiter →</button></div><div class="community-context" id="communityArchiveContext" hidden></div>${archiveSettings()}`;
 const localDate=iso=>{if(!iso)return'';const d=new Date(iso);if(Number.isNaN(d.getTime()))return'';return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};q('#archiveFrom').value=localDate(f.from);q('#archiveTo').value=localDate(f.to);
 q('#archiveSearch').onclick=()=>{archiveOffset=0;archiveFilters={query:q('#archiveQuery').value,person:q('#archivePerson').value,platform:q('#archivePlatform').value,channelId:q('#archiveChannel').value,sessionId:q('#archiveSession').value,from:q('#archiveFrom').value?new Date(q('#archiveFrom').value).toISOString():'',to:q('#archiveTo').value?new Date(q('#archiveTo').value).toISOString():''};searchArchive();};q('#archiveReset').onclick=()=>{archiveFilters={};archiveOffset=0;renderArchive();};q('#archivePrev').onclick=()=>{archiveOffset=Math.max(0,archiveOffset-100);searchArchive();};q('#archiveNext').onclick=()=>{archiveOffset+=100;searchArchive();};q('#archiveExport').onclick=async()=>{const r=await call(api.archiveExport,{format:q('#archiveExportFormat').value,filters:archiveFilters});if(!r.canceled)toast(r.ok?`${r.count} Nachrichten exportiert.`:r.error,!r.ok);};
 q('#archiveSave').onclick=async()=>{const r=await call(api.archiveConfig,{enabled:q('#archiveEnabled').checked,moderationEnabled:q('#archiveModeration').checked,excerptsEnabled:q('#archiveExcerpts').checked,directory:q('#archiveDirectory').value.trim(),retentionDays:Number(q('#archiveRetention').value)});if(!r.ok)error(q('#archiveSaveFeedback'),r);else{await reload();if(q('#archiveSaveFeedback'))q('#archiveSaveFeedback').textContent='Speichereinstellungen übernommen.';}};q('#viewerSave').onclick=async()=>{const r=await call(api.viewersConfig,{enabled:q('#viewerEnabled').checked,tiktok:q('#viewerTikTok').checked,twitch:q('#viewerTwitch').checked});if(!r.ok)error(q('#archiveSaveFeedback'),r);else{await reload();if(q('#archiveSaveFeedback'))q('#archiveSaveFeedback').textContent='Zuschaueranzeige gespeichert.';}};
 call(api.archiveSessions).then(r=>{const select=q('#archiveSession');if(r.ok&&select){select.innerHTML='<option value="">Alle Sitzungen</option>'+(r.items||[]).map(s=>`<option value="${html(s.id)}">${html(s.label||stamp(s.started_at))} (${s.messages||0})</option>`).join('');select.value=f.sessionId||'';}});searchArchive();}
 function openArchive(filters){archiveFilters=filters;archiveOffset=0;setView('chatarchive');renderArchive();}
 const originalModule=renderModule;renderModule=function(view){originalModule(view);if(view==='chatarchive')renderArchive();if(view==='settings')appendSettingsLink();};
 function appendSettingsLink(){const host=q('#settingsModule');if(!host||q('#communitySettingsLink'))return;const box=document.createElement('div');box.id='communitySettingsLink';box.className='community-storage';box.innerHTML='<strong>Chatarchiv und Zuschaueranzeige</strong><p>Aufzeichnung, Speicherort, Aufbewahrung und Zuschauerzahlen einstellen.</p><button>Öffnen</button>';box.querySelector('button').onclick=()=>openArchive({});host.prepend(box);}
 const previousConnections=renderConnections;renderConnections=function(){previousConnections();renderStorage();renderViewers();};
 const previousChat=renderChat;renderChat=function(){previousChat();renderViewers();qa('.chat-user').forEach(el=>{const m=S.messages.find(x=>x.id===el.dataset.messageId);if(!m)return;const st=state(m.platform),sameChannel=!!m.channelId&&m.channelId===st.channelId,fresh=value=>!!value&&Date.now()-Date.parse(value)<120000,complete=st.connected&&st.listMode==='complete'&&fresh(st.confirmedAt),known=sameChannel&&(st.moderators||[]).some(r=>r.userId===m.userId&&r.channelId===m.channelId&&fresh(r.confirmedAt)),sourceConfirmed=m.moderator&&(m.identityVerified===true||m.raw?.user?.identityVerified===true)&&fresh(m.moderatorConfirmedAt||m.raw?.user?.moderatorConfirmedAt||m.timestamp);if(sameChannel&&(complete?known:(known||sourceConfirmed))){const badge=document.createElement('span');badge.className='community-mod-badge';badge.textContent='MOD';badge.title=(names[m.platform]||m.platform)+' · bestätigter Moderator';el.append(badge);}});};
 api.onCommunityStatus?.(s=>{const changed=JSON.stringify(snapshot.moderation)!==JSON.stringify(s.moderation);snapshot=s;renderViewers();renderStorage();if(changed){renderModeration();renderChat();}});api.onViewersStatus?.(v=>{snapshot.viewers=v;renderViewers();});api.onModerationStatus?.(()=>reload());api.onModerationEvent?.(()=>reload());
 api.onModerationLoginStatus?.(login=>{snapshot.login=login;const target=q('#communityLogin');if(!target)return;if(login.status==='pending'){target.innerHTML=`Code: <strong>${html(login.code)}</strong> <button id="communityOpenLogin">Anmeldung öffnen</button>`;q('#communityOpenLogin').onclick=()=>api.moderationOpenLogin({platform:'twitch'});}else target.textContent=login.error||'Anmeldung abgeschlossen.';});
 api.onConfigChanged?.(()=>{renderStorage();renderViewers();});
 const visible=()=>!document.hidden&&(detached||['dashboard','moderation','chatarchive','settings'].includes(S.view));
 const poll=setInterval(()=>{if(S.config&&visible())reload().catch(()=>{});},15000);window.addEventListener('beforeunload',()=>clearInterval(poll));
 for(const event of ['batto:view','visibilitychange'])document.addEventListener(event,()=>{if(S.config&&visible())reload().catch(()=>{});});
 api.getState().then(r=>{if(r.community)snapshot=r.community;renderStorage();renderViewers();return reload();}).catch(e=>console.warn('Community:',e.message));
 window.BattoCommunity={reload,renderArchive,openArchive};
})();
