(()=>{'use strict';
const root=document.getElementById('dual-root'),$=id=>document.getElementById('dual-'+id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const detached=document.body.hasAttribute('data-dual-detached');
let baseRevision=0,conflict=false;
let state,config,initialized=false,dirty=false,selected='tiktok',layer='game',drag=null,busy=false,snapshot=null;
let previewEnabled=true,previewMode='program',previewTimer,previewBusy=false,previewEpoch=0,sourceTimer,obsImport=null,collectionSignature='';
const cameras=['camera','camera2','camera3'],pictureSources=['game',...cameras];
const labels={tiktok:'TikTok',twitch:'Twitch',game:'Spiel / Bildschirm',camera:'Kamera 1',camera2:'Kamera 2',camera3:'Kamera 3',microphone:'Mikrofon',desktop:'PC-Ton'};
const builtins=['Spiel','Pause','Start','Ende'];
const sceneGroups=[['','Gemeinsame Schnellwahl'],['tiktok','TikTok · Hochformat'],['twitch','Twitch · Querformat']];
function fallbackSceneOrder(a,b){const rank=item=>{const name=String(item.name||item.label||'').toLocaleLowerCase('de').replace(/[_-]/g,' ').replace(/\b(tiktok|twitch|tt|hochformat|querformat)\b/g,'').trim();const i=['start','spiel','pause','chat','ende','offline','pc'].indexOf(name);return i<0?99:i;};return rank(a)-rank(b)||String(a.name||a.label).localeCompare(String(b.name||b.label),'de',{numeric:true,sensitivity:'base'});}
function sceneOptions(){
 const scenes=(config?.obsCollection?.scenes||[]).filter(s=>!s.internal),provided=state?.sceneChoices;
 if(provided)return provided.map(choice=>{const scene=scenes.find(s=>s.key===choice.value);return scene?{name:scene.name,platform:scene.platform,...choice}:choice;});
 return [...builtins.map(value=>({value,label:value,name:value})).sort(fallbackSceneOrder),...['tiktok','twitch'].flatMap(platform=>scenes.filter(s=>s.platform===platform).sort(fallbackSceneOrder).map(s=>{const partner=scenes.find(p=>p.id===s.partnerId&&p.platform!==platform);return {value:s.key,label:s.label||s.name,name:s.name,platform,spokenName:labels[platform]+' '+s.name,partnerLabel:partner?.label||partner?.name,partnerName:partner?.name,partnerKey:partner?.key};}))];
}
function sceneSelectOptions(){const choices=sceneOptions();return sceneGroups.map(([platform,title])=>{const items=choices.filter(item=>(item.platform||'')===platform);return items.length?`<optgroup label="${esc(title)}">${items.map(item=>`<option value="${esc(item.value)}">${esc(item.name||item.label)}</option>`).join('')}</optgroup>`:'';}).join('');}
function sceneLabel(value=config?.program.scene){return sceneOptions().find(s=>s.value===value)?.label||value||'';}
function importedScene(value=config?.program.scene,platform=selected){const library=config?.obsCollection,scenes=library?.scenes||[],id=library?.aliases?.[platform]?.[value];const chosen=scenes.find(s=>s.key===value||s.id===id);if(!chosen)return null;return chosen.platform===platform?chosen:scenes.find(s=>s.id===chosen.partnerId)||chosen;}
function outputName(platform=selected){return importedScene(config?.program.scene,platform)?.name||sceneLabel();}
function editingShared(){return previewMode==='sources'||config?.program.scene==='Spiel'&&!importedScene();}

const visible=()=>!window.BattoResources?.suspended&&!document.hidden&&document.getElementById('view-dualstream').classList.contains('active');
const active=()=>visible()&&(detached||!state?.detached);
const live=()=>Object.values(state?.state.outputs||{}).some(o=>['camera','live','connecting','test'].includes(o.state));
function message(text){$('message').textContent=text;}
async function api(command,value){return window.batto.dual(command,value);}
function run(fn){return async event=>{event?.preventDefault();if(busy)return;busy=true;status();try{await fn(event);}catch(e){const text=String(e.message).replace(/^Error invoking remote method [^:]+: Error: /,'');message(text);if($('obs-dialog')?.open)$('obs-status').textContent=text;}finally{busy=false;status();schedulePreview();}};}
function on(id,fn){$(id).addEventListener('click',run(fn));}
function build(){
 root.innerHTML=`<div class="dual-toolbar dual-window-controls"><button id="dual-detach">Entkoppeln</button><button id="dual-attach" hidden>Andocken</button><label class="suite-check" id="dual-top-label" hidden><input id="dual-top" type="checkbox"> Immer oben</label><button id="dual-reload" hidden>Aktuellen Stand neu laden</button><button id="dual-import">Projekt importieren</button><button id="dual-obs-import">OBS-Szenensammlung importieren</button><button id="dual-export">Projekt exportieren</button><button id="dual-save" class="primary">Änderungen speichern</button><span id="dual-dirty" class="suite-help"></span></div>
 <div id="dual-message" class="dual-message" role="status" aria-live="polite"></div>
 <div id="dual-detached-note" class="dual-detached-note" hidden>Dual Stream ist in einem eigenen Fenster geöffnet. Die Vorschau läuft dort. <button id="dual-focus">Fenster anzeigen</button><button id="dual-dock">Hier andocken</button></div><div id="dual-workspace"><article class="suite-panel"><div class="dual-toolbar"><label>Qualität <select id="dual-profile"><option value="economy_720p30">Sparprofil · 720p / 30 FPS</option><option value="fullhd_1080p30">Full HD · 1080p / 30 FPS</option></select></label><button id="dual-probe">Geräte erkennen</button><button id="dual-library">Videobibliotheken wählen</button><button id="dual-register">Virtuelle Kameras einrichten</button></div><div id="dual-readiness" class="dual-readiness"></div><div id="dual-sources">${pictureSources.map(s=>`<div class="dual-source-row"><label class="suite-check"><input id="dual-source-${s}" type="checkbox"> ${labels[s]}</label>${s==='game'?'<select id="dual-kind" aria-label="Aufnahmeart"><option value="game">Spielaufnahme</option><option value="window">Fensteraufnahme</option><option value="screen">Bildschirmaufnahme</option></select>':'<span class="suite-help">Für beide Ziele gemeinsam</span>'}<div class="dual-source-device"><select id="dual-target-${s}" aria-label="${labels[s]} auswählen"></select>${s!=='game'?`<small id="dual-source-status-${s}" class="dual-source-status" role="status"></small>`:''}</div></div>`).join('')}</div><p class="suite-help dual-camera-help">Bis zu drei Kameras gemeinsam für TikTok und Twitch. Zusätzliche Kameras bleiben aus, bis du sie einschaltest. Unter „Quelle anordnen“ wählst du jede Kamera einzeln.</p></article>
 <article class="suite-panel"><h3>Szenen &amp; Einblendungen</h3><div class="dual-toolbar"><label>Szene<select id="dual-scene" aria-label="Szene auswählen"></select></label><label>Übergang<select id="dual-transition"><option value="fade">Überblenden</option><option value="cut">Schnitt</option></select></label><label>Dauer (ms)<input id="dual-transition-ms" type="number" min="100" max="2000" step="50" value="350"></label><button id="dual-scene-apply" class="primary">Szene auf beide Ausgaben schalten</button><button id="dual-background">Hintergrund wählen</button><button id="dual-background-clear">Hintergrund löschen</button></div><p id="dual-background-note" class="suite-help"></p><div class="dual-toolbar"><label class="suite-check"><input id="dual-chat-overlay" type="checkbox"> Chat im Stream zeigen</label><label class="suite-check"><input id="dual-events-overlay" type="checkbox"> Ereignisse im Stream zeigen</label><button id="dual-program-save">Einblendungen speichern</button></div><div class="dual-toolbar"><button id="dual-companion">LIVE-Studio-Sitzung markieren</button><button id="dual-chat-url">Chat-Adresse für LIVE Studio kopieren</button><button id="dual-events-url">Ereignis-Adresse kopieren</button></div><p id="dual-current-scene" class="suite-help"></p><details id="dual-collection" class="dual-collection" hidden><summary id="dual-collection-title"></summary><p id="dual-collection-note" class="suite-help"></p><div id="dual-collection-scenes" class="dual-collection-scenes"></div><div id="dual-collection-warnings" class="suite-help"></div></details><p class="suite-help">Importierte OBS-Szenen stehen unter ihrem eigenen Namen zur Verfügung. Start, Pause und Ende verwenden deine zugeordneten OBS-Szenen oder Hintergrundbilder. Die Chat-Einblendung zeigt die letzten vier Nachrichten. Für TikTok LIVE Studio kannst du die vorhandene Stream-Ansicht als Browserquelle verwenden; der eigene Video-Dienst kann dabei ausgeschaltet bleiben.</p></article>
 <article class="suite-panel"><div class="dual-toolbar" role="tablist" aria-label="Leinwand"><button id="dual-tab-tiktok" class="dual-tab" role="tab">TikTok · 9:16</button><button id="dual-tab-twitch" class="dual-tab" role="tab">Twitch · 16:9</button><span id="dual-dimensions" class="suite-help"></span></div><div class="dual-toolbar"><label>Vorschau<select id="dual-preview-mode"><option value="program">Aktuelle Ausgabe</option><option value="sources">Kamera &amp; Spiel prüfen</option></select></label><span id="dual-preview-title" class="suite-help"></span></div>
 <div id="dual-scene-note" class="dual-scene-note" hidden><span id="dual-scene-note-text"></span> <button id="dual-show-game">Kamera &amp; Spiel prüfen</button></div><div class="dual-editor"><div><div class="dual-canvas-wrap"><div id="dual-canvas" class="dual-canvas tiktok" aria-label="Leinwand mit verschiebbaren Quellen"></div></div><p id="dual-preview-note" class="suite-help" role="status"></p><div id="dual-camera-note" class="suite-help dual-camera-notes" role="status"></div><div class="dual-toolbar"><button id="dual-prepare">Quellen vorbereiten</button><button id="dual-preview">Vorschau starten</button><label class="suite-check"><input id="dual-auto-preview" type="checkbox" checked> Sparsame Vorschau · 1 Bild/s</label><button id="dual-release">Video-Dienst ausschalten</button></div></div>
 <div><h3>Quelle anordnen</h3><p id="dual-editor-note" class="suite-help"></p><button id="dual-template">Kamera oben, Spiel darunter</button><label>Bildquelle<select id="dual-layer"><option value="game">Spiel / Bildschirm</option>${cameras.map(id=>`<option value="${id}">${labels[id]}</option>`).join('')}</select></label><label class="suite-check"><input id="dual-visible" type="checkbox"> Auf dieser Leinwand zeigen</label><div class="dual-form-grid">${[['x','Links (%)'],['y','Oben (%)'],['width','Breite (%)'],['height','Höhe (%)']].map(([k,t])=>`<label>${t}<input id="dual-${k}" type="number" min="${k==='width'||k==='height'?2:0}" max="100" step="0.1"></label>`).join('')}</div><label>Einpassen<select id="dual-fit"><option value="contain">Vollständig zeigen</option><option value="cover">Fläche füllen / beschneiden</option></select></label><p class="suite-help">Quelle im Bild verschieben oder Prozentwerte eintragen. Beide Leinwände speichern ihre Anordnung getrennt.</p></div></div></article>
 <div class="dual-output-grid">${['tiktok','twitch'].map(p=>`<article class="suite-panel"><div class="dual-output-title"><h3>${labels[p]} · virtuelle Kamera</h3><span id="dual-status-${p}" class="dual-status">Aus</span></div><div id="dual-metrics-${p}" class="dual-metrics"></div><div class="dual-toolbar"><button id="dual-start-${p}" class="primary">Kamera starten</button><button id="dual-stop-${p}">Stoppen</button></div><div id="dual-error-${p}" class="suite-help"></div></article>`).join('')}</div>
 <div class="dual-toolbar"><button id="dual-start-both" class="primary">Beide Kameras starten</button><button id="dual-stop-both">Beide stoppen</button><button id="dual-gaming">Gaming-Modus</button></div><p class="suite-help">Ohne Streamkey: Kamera hier starten und in LIVE Studio „Batto TikTok“ als Kamera wählen. Für Querformat „Batto Twitch“ wählen. Fehlen die Geräte dort, „Virtuelle Kameras einrichten“ drücken, die einmalige Windows-Administratorbestätigung bestätigen und LIVE Studio danach vollständig neu starten. Mikrofon und PC-Ton direkt in LIVE Studio einstellen. Virtuelle Kameras übertragen nur Bild; den Stream startest du in LIVE Studio. Gaming-Modus speichert dieses Layout und schließt die Bedienoberfläche, um RAM freizugeben. Dienste, Jarvis und Kameras laufen weiter. Über das Taskleisten-Symbol oder Stream Deck öffnest du das Fenster wieder. Ein entkoppeltes Dual-Stream-Fenster bleibt bedienbar; du kannst es zum Sparen ebenfalls schließen.</p></div>
 <dialog id="dual-obs-dialog" class="dual-import-dialog" aria-labelledby="dual-obs-title"><h3 id="dual-obs-title">OBS-Szenensammlung übernehmen</h3><p id="dual-obs-name"></p><p id="dual-obs-summary" class="suite-help"></p><div id="dual-obs-inventory" class="dual-obs-inventory"></div><details><summary>Optional: vorhandene Szenentasten zuordnen</summary><p class="suite-help">Spiel, Start, Pause und Ende können zusätzlich deine OBS-Szenen aufrufen. Alle Szenen werden unabhängig von dieser Zuordnung übernommen.</p><div id="dual-obs-mapping" class="dual-import-mapping"></div></details><p class="suite-help">Kameraebenen mit passendem Gerät nutzen Kamera 1, 2 oder 3. Sonstige Kameraebenen nutzen Kamera 1. Zusätzliche Kameras werden in importierte Szenen nicht automatisch eingefügt. Weitere Spiel- und Fensterquellen behalten ihre OBS-Zuordnung. Falls gewünscht, wähle hier eine andere gemeinsame Bildquelle aus der Sammlung.</p><div id="dual-obs-sources" class="dual-import-mapping"></div><details id="dual-obs-details"><summary>Quellen und Hinweise prüfen</summary><div id="dual-obs-warnings"></div></details><p id="dual-obs-status" class="suite-help" role="status"></p><div class="dual-toolbar"><button id="dual-obs-apply" class="primary">Sammlung übernehmen</button><button id="dual-obs-cancel">Abbrechen</button></div></dialog>`;
 on('detach',async()=>{if(dirty)await save();state=await api('detach');status();});
 on('focus',async()=>{state=await api('detach');status();});
 const dock=async()=>{if(dirty)await save();state=await api('attach');status();};on('attach',dock);on('dock',dock);
 $('top').onchange=event=>{const value=event.target.checked;return run(async()=>{state=await api('always-on-top',value);})(event);};
 on('reload',async()=>{if(dirty&&!confirm('Ungespeicherte Änderungen verwerfen und den aktuellen Stand laden?'))return;adopt(await api('state'));message('Aktueller Stand geladen.');});
 on('register',async()=>{if(dirty)await save();message('Kameraeinrichtung: Bitte die Windows-Administratorbestätigung bestätigen, falls sie erscheint.');state=await api('register-cameras');fillDevices();message('Kameras für LIVE Studio eingerichtet. LIVE Studio vollständig beenden und neu öffnen, dann „Batto TikTok“ oder „Batto Twitch“ auswählen.');});
 on('template',()=>{config.layouts.tiktok=[{source:'game',x:0,y:.48,width:1,height:.52,fit:'contain',visible:true},{source:'camera',x:0,y:0,width:1,height:.48,fit:'cover',visible:true},...config.layouts.tiktok.filter(item=>cameras.slice(1).includes(item.source))];config.layoutRevision=2;selected='tiktok';layer='camera';changed();editor();canvas();message('Kamera 1 füllt den gesamten oberen Bereich. Die Anordnung von Kamera 2 und 3 bleibt erhalten. Änderungen speichern.');});
 on('gaming',async()=>{clearTimeout(sourceTimer);invalidatePreview(false);if(dirty)await save();await api('gaming');});
 on('companion',async()=>{await api('companion');state=await api('state');message('Live-Markierung gilt für Bot-Regeln und Auto-Broadcast. LIVE Studio selbst wird dadurch nicht gestartet oder gestoppt.');});
 for(const kind of ['chat','events'])on(kind+'-url',async()=>{await api('copy-overlay',kind);message('Adresse kopiert. In LIVE Studio als Browserquelle hinzufügen.');});
 const chooseScene=async scene=>{if(dirty)await save();const next=await api('scene',{scene,transition:$('transition').value,durationMs:Number($('transition-ms').value),baseRevision});previewMode='program';$('preview-mode').value='program';adopt(next);message('Szene '+sceneLabel()+' ausgewählt.'+(!state.state.prepared?' Mit „Vorschau starten“ siehst du die Ausgabe.':''));};
 on('scene-apply',()=>chooseScene($('scene').value));on('show-game',()=>{previewMode='sources';$('preview-mode').value='sources';invalidatePreview();canvas();status();schedulePreview(0);});
 $('collection-scenes').addEventListener('click',run(async event=>{const button=event.target.closest('[data-imported-scene]');if(button)await chooseScene(button.dataset.importedScene);}));
 on('program-save',async()=>{if(dirty)await save();state=await api('program',{...state.config.program,chat:$('chat-overlay').checked,events:$('events-overlay').checked,baseRevision});config.program=JSON.parse(JSON.stringify(state.config.program));message('Einblendungen gespeichert.');});
 on('background',async()=>{if(dirty)await save();const scene=$('scene').value;if(scene==='Spiel')throw Error('Für Spiel wählst du die Bildquelle im oberen Bereich.');const next=await api('background',{scene,platform:selected,baseRevision});if(next){adopt(next);message('Hintergrund für '+labels[selected]+' gespeichert.');}});
 on('background-clear',async()=>{if(dirty)await save();const scene=$('scene').value;adopt(await api('background-clear',{scene,platform:selected,baseRevision}));message('Hintergrund für '+labels[selected]+' · '+scene+' gelöscht. Die Originaldatei bleibt erhalten.');});
 $('scene').onchange=()=>{backgroundNote();status();};
 on('save',save);on('probe',async()=>{if(dirty)await save();state=await api('probe');fillDevices();status();message('Aufnahmegeräte erkannt. Virtuelle Kameras benötigen keinen Stream-Encoder.');});
 on('library',async()=>{if(dirty)await save();const next=await api('library');if(next)adopt(next);});
 on('import',async()=>{if(dirty&&!confirm('Ungespeicherte Änderungen verwerfen und ein Projekt importieren?'))return;const next=await api('import');if(next){adopt(next);message('Projekt übernommen. Aufnahmequellen bitte zuordnen.');}});
 on('obs-import',async()=>{if(dirty)await save();const next=await api('obs-import-preview');if(next)showObsImport(next);});
 on('obs-apply',async()=>{if(!obsImport)throw Error('Bitte zuerst eine OBS-Szenensammlung auswählen.');const mapping=Object.fromEntries(['tiktok','twitch'].map(p=>[p,Object.fromEntries(['Spiel','Start','Pause','Ende'].map(scene=>[scene,document.querySelector(`[data-obs-platform="${p}"][data-obs-scene="${scene}"]`).value]))])),sources=Object.fromEntries(['camera','game'].map(id=>[id,$('obs-source-'+id).value]));const next=await api('obs-import-apply',{token:obsImport.token,mapping,sources,baseRevision:obsImport.baseRevision??baseRevision});previewMode='program';$('preview-mode').value='program';adopt(next);$('obs-dialog').close();obsImport=null;message((next.importSummary||'OBS-Szenensammlung übernommen.')+' Alle importierten Szenen stehen jetzt in der Szenenauswahl und bei Jarvis / Touch Deck bereit. Szene auswählen und „Vorschau starten“ drücken.'+(next.importWarnings?.length?' Hinweise findest du unter „OBS-Szenensammlung“ bei den Szenen.':''));$('collection').open=true;});
 on('obs-cancel',()=>{$('obs-dialog').close();obsImport=null;});$('obs-dialog').addEventListener('cancel',event=>{if(busy)event.preventDefault();else obsImport=null;});
 on('export',async()=>{if(dirty)await save();const r=await api('export');if(r.saved)message('Projekt exportiert.');});
 on('prepare',async()=>{if(dirty)await save();state=await api('prepare');message('Quellen vorbereitet. Vorschau wird geladen; die virtuellen Ausgaben sind noch aus.');schedulePreview(150);});
 on('release',async()=>{state=await api('release');snapshot=null;canvas();message('Video-Dienst ausgeschaltet.');});
 on('preview',async()=>{if(dirty)await save();if(!state.state.prepared)state=await api('prepare');previewEnabled=true;$('auto-preview').checked=true;snapshot=await api('snapshot',{platform:selected,mode:previewMode});canvas();schedulePreview();});
 $('preview-mode').onchange=()=>{previewMode=$('preview-mode').value;invalidatePreview();canvas();status();schedulePreview(0);};
 for(const p of ['tiktok','twitch']){
  $('tab-'+p).onclick=()=>{selected=p;invalidatePreview();editor();canvas();status();schedulePreview(0);};
  on('start-'+p,()=>start(p));on('stop-'+p,async()=>{state=await api('stop',p);});
 }
 on('start-both',()=>start('both'));on('stop-both',async()=>{state=await api('stop','both');});
 $('profile').onchange=()=>{config.profile=$('profile').value;changed();canvas();};
 $('kind').onchange=()=>{config.sources.game.kind=$('kind').value;config.sources.game.target='';config.sources.game.name='';config.sources.game.enabled=false;changed();fillDevices();canvas();};
 for(const s of pictureSources){
  $('source-'+s).onchange=()=>{config.sources[s].enabled=$('source-'+s).checked;changed();canvas();scheduleSources();};
  $('target-'+s).onchange=()=>{config.sources[s].target=$('target-'+s).value;config.sources[s].name=$('target-'+s).selectedOptions[0]?.textContent||'';changed();scheduleSources();};
 }
 $('auto-preview').onchange=()=>{previewEnabled=$('auto-preview').checked;invalidatePreview(false);previewNote();schedulePreview(0);};
 $('layer').onchange=()=>{layer=$('layer').value;editor();canvas();};
 for(const k of ['x','y','width','height','visible','fit'])$(''+k).addEventListener('change',()=>{const item=config.layouts[selected].find(x=>x.source===layer);if(k==='visible')item[k]=$('visible').checked;else if(k==='fit')item[k]=$('fit').value;else{const n=Number($(k).value)/100;if(!Number.isFinite(n))return;item[k]=Math.max(k==='width'||k==='height'?.02:0,Math.min(1,n));if(item.x+item.width>1)item.x=1-item.width;if(item.y+item.height>1)item.y=1-item.height;}changed();editor();canvas();});
 const stage=$('canvas');stage.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-dual-source]');if(!el||live()||!editingShared())return;layer=el.dataset.dualSource;const item=config.layouts[selected].find(x=>x.source===layer);drag={pointer:e.pointerId,x:e.clientX,y:e.clientY,startX:item.x,startY:item.y,rect:stage.getBoundingClientRect()};stage.setPointerCapture(e.pointerId);editor();e.preventDefault();});
 stage.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;const item=config.layouts[selected].find(x=>x.source===layer);item.x=Math.max(0,Math.min(1-item.width,drag.startX+(e.clientX-drag.x)/drag.rect.width));item.y=Math.max(0,Math.min(1-item.height,drag.startY+(e.clientY-drag.y)/drag.rect.height));changed();editor();canvas();});
 const end=e=>{if(drag?.pointer===e.pointerId){drag=null;if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);}};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);
}
function changed(){dirty=true;invalidatePreview();status();}
async function save(){if(conflict)throw Error('Der gespeicherte Stand wurde geändert. Bitte zuerst neu laden.');state=await api('save',{...config,baseRevision});adopt(state);message('Dual-Stream-Einstellungen gespeichert.');}
async function start(p){if(dirty)await save();state=await api('start',p);message('Virtuelle Kamera läuft. Jetzt in LIVE Studio als Kamera auswählen.');schedulePreview(150);}
function showObsImport(preview){
 obsImport=preview;$('obs-name').textContent=preview.name||'OBS-Szenensammlung';$('obs-status').textContent='Die aktuelle Konfiguration wird erst nach „Sammlung übernehmen“ geändert.';
 const scenes=(Array.isArray(preview.scenes)?preview.scenes:[]).filter(s=>!s.internal);
 $('obs-summary').textContent=`Alle ${scenes.length} OBS-Szenen werden unter ihren eigenen Namen übernommen. Zusammengehörige Hoch- und Querformatszenen werden gemeinsam geschaltet. Nicht verfügbare Dateien oder nicht unterstützte Quellen werden unten ausgewiesen.`;
 $('obs-inventory').innerHTML=scenes.map(item=>`<div><strong>${esc(item.label||item.name)}</strong><span>${esc(item.width)} × ${esc(item.height)} · ${esc(item.summary||'OBS-Szene')}</span></div>`).join('');
 $('obs-mapping').innerHTML=['tiktok','twitch'].map(platform=>`<fieldset><legend>${labels[platform]} · ${platform==='tiktok'?'9:16':'16:9'}</legend>${['Spiel','Start','Pause','Ende'].map(scene=>`<label>${scene}<select data-obs-platform="${platform}" data-obs-scene="${scene}"><option value="">Aktuelle Szene behalten</option>${scenes.map(item=>`<option value="${esc(item.id)}">${esc(item.label||item.name)}${item.width&&item.height?' · '+esc(item.width)+' × '+esc(item.height):''}</option>`).join('')}</select></label>`).join('')}</fieldset>`).join('');
 for(const platform of ['tiktok','twitch'])for(const scene of ['Spiel','Start','Pause','Ende']){const select=document.querySelector(`[data-obs-platform="${platform}"][data-obs-scene="${scene}"]`);select.value=preview.suggestedMapping?.[platform]?.[scene]||'';if(select.selectedIndex<0)select.value='';}
 $('obs-sources').innerHTML=['camera','game'].map(id=>`<label>${id==='camera'?'Kamera 1 · gemeinsame Hauptkamera':'Gemeinsames Spiel / Fenster'}<select id="dual-obs-source-${id}"><option value="">Aktuelle Quelle behalten</option>${(preview.sources?.[id]||[]).map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label>`).join('');
 for(const id of ['camera','game'])$('obs-source-'+id).value='';
 const notes=[...(preview.warnings||[])];for(const item of scenes){for(const note of item.warnings||[])notes.push(item.name+': '+note);for(const asset of item.assets||[])if(asset.exists===false)notes.push(item.name+': Datei fehlt – '+(asset.name||asset.path||'unbekannte Datei'));}
 $('obs-warnings').innerHTML=notes.length?'<ul>'+[...new Set(notes)].map(note=>'<li>'+esc(note)+'</li>').join('')+'</ul>':'<p>Keine Probleme bei den unterstützten Quellen erkannt.</p>';
 $('obs-details').open=notes.length>0;$('obs-dialog').showModal();
}
function renderCollection(){
 const collection=config?.obsCollection,scenes=(collection?.scenes||[]).filter(s=>!s.internal),warnings=[...new Set([...(collection?.warnings||[]),...(state?.importWarnings||[]),...(state?.state?.importWarnings||[])])];
 const choices=sceneOptions().filter(item=>item.platform),signature=JSON.stringify([collection?.name,scenes.map(s=>[s.key,s.label,s.width,s.height,s.partnerId]),choices,config.program.scene,warnings]);if(signature===collectionSignature)return;collectionSignature=signature;$('collection').hidden=!scenes.length;
 $('collection-title').textContent='OBS-Szenensammlung · '+scenes.length+' Szenen';
 $('collection-note').textContent=(collection?.name||'')+' · Nach Plattform sortiert. Zugeordnete Hoch- und Querformatszenen werden weiterhin gemeinsam geschaltet. Die Jarvis-Sätze unter den Tasten wählen dieselbe Szene.';
 $('collection-scenes').innerHTML=sceneGroups.filter(([platform])=>platform).map(([platform,title])=>{const items=choices.filter(item=>item.platform===platform),activeScene=importedScene(config.program.scene,platform);return `<section class="dual-scene-group" data-scene-platform="${platform}" aria-labelledby="dual-scenes-${platform}"><h4 id="dual-scenes-${platform}">${title}<span>${items.length} ${items.length===1?'Szene':'Szenen'}</span></h4><div class="dual-scene-grid">${items.length?items.map(choice=>{const item=scenes.find(s=>s.key===choice.value),partner=scenes.find(s=>s.id===item?.partnerId&&s.platform!==platform),partnerLabel=choice.partnerLabel||partner?.label||partner?.name,isActive=activeScene?.platform===platform&&activeScene.key===choice.value;return `<button type="button" data-imported-scene="${esc(choice.value)}" aria-pressed="${isActive}"><strong>${esc(choice.name||item?.name||choice.label)}${isActive?'<span class="dual-scene-active">Aktiv</span>':''}</strong><small>${esc(item?.width)} × ${esc(item?.height)}</small><small class="dual-scene-partner">${partnerLabel?'Zusammen mit: '+esc(partnerLabel):'Ohne Partner: dieselbe Szene für beide'}</small><small class="dual-scene-voice">Jarvis, ${esc(choice.spokenName||labels[platform]+' '+(choice.name||item?.name||choice.label))}</small></button>`;}).join(''):'<p class="suite-help">Keine Szenen für diese Plattform importiert.</p>'}</div></section>`;}).join('');
 $('collection-warnings').innerHTML=warnings.length?'<details><summary>'+warnings.length+' Hinweise zu Dateien und Quellen</summary><ul>'+warnings.map(note=>'<li>'+esc(note)+'</li>').join('')+'</ul></details>':'<p>Keine Probleme bei den unterstützten Quellen gemeldet.</p>';
}
function adopt(next){state=next;baseRevision=next.revision;config=JSON.parse(JSON.stringify(next.config));dirty=false;conflict=false;invalidatePreview();$('scene').innerHTML=sceneSelectOptions();$('scene').value=config.program.scene;renderCollection();$('transition').value=config.program.transition;$('transition-ms').value=config.program.durationMs;$('chat-overlay').checked=config.program.chat;$('events-overlay').checked=config.program.events;$('profile').value=config.profile;$('kind').value=config.sources.game.kind;fillDevices();editor();canvas();status();}
function fillDevices(){for(const s of pictureSources){const current=config.sources[s],items=state.probe?.devices?.[s==='game'?current.kind:'camera']||[],valid=items.filter(x=>x.id&&!(cameras.includes(s)&&/27b05c2d-93dc-474a-a5da-9bba34cb2a9[cd]/i.test(x.id)));$('target-'+s).innerHTML='<option value="">Bitte auswählen</option>'+valid.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');if(current.target&&!valid.some(x=>x.id===current.target))$('target-'+s).insertAdjacentHTML('beforeend',`<option value="${esc(current.target)}">${esc(current.name||'Gespeicherte Quelle')} · noch nicht geprüft</option>`);$('target-'+s).value=current.target;$('source-'+s).checked=current.enabled;}}
function editor(){const item=config.layouts[selected].find(x=>x.source===layer);$('layer').value=layer;for(const k of ['x','y','width','height'])$(k).value=(item[k]*100).toFixed(1);$('visible').checked=item.visible;$('fit').value=item.fit;}
function canvas(){if(!config)return;const stage=$('canvas');stage.className='dual-canvas '+selected+(snapshot?' has-preview':'');for(const p of ['tiktok','twitch'])$('tab-'+p).setAttribute('aria-selected',String(p===selected));const hd=config.profile==='fullhd_1080p30';$('dimensions').textContent=(selected==='tiktok'?(hd?'1080 × 1920':'720 × 1280'):(hd?'1920 × 1080':'1280 × 720'))+' · 30 FPS';
 const showSources=editingShared();stage.innerHTML=(snapshot?`<img alt="${previewMode==='sources'?'Quellenprüfung':'Ausgabe · '+esc(sceneLabel())} · ${labels[selected]}" src="${snapshot.image}">`:'')+(showSources?config.layouts[selected].filter(x=>x.visible&&(!cameras.slice(1).includes(x.source)||config.sources[x.source].enabled||x.source===layer)).map(x=>`<button type="button" data-dual-source="${x.source}" class="dual-layer ${x.source===layer?'selected':''} ${config.sources[x.source].enabled?'':'disabled'}" style="left:${x.x*100}%;top:${x.y*100}%;width:${x.width*100}%;height:${x.height*100}%" aria-label="${labels[x.source]} verschieben"><span>${labels[x.source]}${config.sources[x.source].enabled?'':' · aus'}</span></button>`).join(''):!snapshot?`<div class="dual-canvas-empty">${esc(sceneLabel())}<small>Vorschau starten</small></div>`:'');
 previewNote();backgroundNote();
}
function invalidatePreview(clear=true){previewEpoch++;clearTimeout(previewTimer);previewTimer=null;if(clear)snapshot=null;}
function previewNote(){
 if(!initialized)return;
 if(!config)return;
 $('preview-title').textContent=previewMode==='sources'?'Nur Quellenprüfung – die ausgegebene Szene bleibt '+outputName()+'.':'Ausgabe: '+outputName()+' · '+labels[selected];
 const imported=importedScene();$('scene-note').hidden=previewMode==='sources'||!imported&&config.program.scene==='Spiel';$('scene-note-text').textContent=imported?'OBS-Szene „'+imported.name+'“ · '+labels[selected]+': Die übernommenen Quellen und ihre Anordnung werden ausgegeben. Kamera und Spiel kannst du getrennt prüfen.':'Aktuell wird „'+sceneLabel()+'“ mit ihrem Hintergrund ausgegeben. Unter „Kamera & Spiel prüfen“ prüfst du die gemeinsamen Bildquellen.';
 $('editor-note').textContent=editingShared()?'Hier ordnest du die gemeinsamen Bildquellen der eingebauten Spiel-Szene an.':'Die Anordnung dieser OBS- oder Hintergrundszene bleibt erhalten. Für die gemeinsame Spiel-Anordnung wähle „Kamera & Spiel prüfen“.';
 let text=snapshot?'Vorschaubild · '+new Date(snapshot.capturedAt).toLocaleTimeString('de-DE')+(previewEnabled?' · 1 Bild/s, pausiert außerhalb dieses Bereichs.':' · angehalten.'):'Noch kein Vorschaubild. Quellen auswählen und einschalten, dann „Vorschau starten“ drücken.';
 const cameraNotes=cameras.map(id=>{
  const camera=snapshot?.sources?.find(item=>item.id===id),source=config.sources[id],item=config.layouts[selected].find(item=>item.source===id),name=labels[id],received=camera?.width>0&&camera?.height>0;let cameraText;
  if(!source.enabled)cameraText=name+': ausgeschaltet · wird nicht aufgenommen.';
  else if(!source.target)cameraText=name+': Bitte oben ein Aufnahmegerät auswählen.';
  else if(!state?.state.prepared)cameraText=name+': ausgewählt; noch nicht gestartet. „Vorschau starten“ drücken.';
  else if(!snapshot)cameraText=name+': Aufnahme vorbereitet; für ein Bild „Vorschau aktualisieren“ drücken.';
  else if(received)cameraText=name+' liefert '+camera.width+' × '+camera.height+'.';
  else cameraText=name+': Noch kein Bild empfangen. Kamera anschließen und gegebenenfalls die Hersteller-App prüfen. Ein anderes Programm kann das Gerät belegen.';
  if(source.enabled&&!imported&&!item?.visible)cameraText+=' Auf '+labels[selected]+' ausgeblendet. Unter „Quelle anordnen“ diese Kamera auswählen und „Auf dieser Leinwand zeigen“ einschalten.';
  const warning=source.enabled&&(!source.target||state?.state.prepared&&snapshot&&!received),row=$('source-status-'+id);row.textContent=cameraText;row.classList.toggle('dual-camera-warning',Boolean(warning));
  return {id,source,text:cameraText,warning};
 });
 $('camera-note').innerHTML=cameraNotes.filter(note=>note.id==='camera'||note.source.enabled).map(note=>'<p'+(note.warning?' class="dual-camera-warning"':'')+'>'+esc(note.text)+'</p>').join('');$('camera-note').classList.toggle('dual-camera-warning',cameraNotes.some(note=>note.warning));
 $('preview-note').textContent=text;$('preview').textContent=state?.state.prepared?'Vorschau aktualisieren':'Vorschau starten';
}
function backgroundNote(){if(!config)return;const scene=$('scene').value,imported=importedScene(scene),platformValue=config.program.platformBackgrounds?.[selected]?.[scene],value=platformValue!==undefined?platformValue:config.program.backgrounds?.[scene];
 if(scene.startsWith('obs:'))$('background-note').textContent='Diese OBS-Szene enthält ihre übernommenen Ebenen. Die Hintergrundtasten gelten für Start, Pause und Ende; die importierte Szene bleibt erhalten.';
 else if(imported)$('background-note').textContent=labels[selected]+' · '+scene+' ruft OBS-Szene „'+imported.name+'“ auf.'+(scene==='Spiel'?' Ihre Anordnung wird aus OBS übernommen.':' Hintergrund wählen oder löschen ersetzt diese Zuordnung nur für '+labels[selected]+'. Die OBS-Szene bleibt in der Sammlung.');
 else $('background-note').textContent=scene==='Spiel'?'Spiel zeigt deine gemeinsamen Bildquellen.':'Hintergrund für '+labels[selected]+' · '+scene+': '+(value===null?'gelöscht – leere Fläche.':value?'eigene Datei.':'mitgeliefertes Bild.');
}
function canPreview(){return initialized&&active()&&previewEnabled&&!dirty&&state?.state.prepared;}
function schedulePreview(ms=1000){
 if(previewTimer||previewBusy||!canPreview())return;
 previewTimer=setTimeout(refreshPreview,ms);
}
async function refreshPreview(){
 previewTimer=null;if(!canPreview())return;if(busy||state.busy){schedulePreview();return;}
 previewBusy=true;const epoch=previewEpoch,platform=selected;
 try{const next=await api('snapshot',{platform,mode:previewMode});if(epoch!==previewEpoch||platform!==selected||!canPreview())return;snapshot=next;const img=$('canvas').querySelector('img');if(img){img.src=next.image;previewNote();}else canvas();}
 catch(e){if(epoch===previewEpoch&&active()){previewEnabled=false;$('auto-preview').checked=false;message('Vorschau angehalten: '+String(e.message).replace(/^Error invoking remote method [^:]+: Error: /,''));previewNote();}}
 finally{previewBusy=false;schedulePreview();}
}
function scheduleSources(){
 clearTimeout(sourceTimer);sourceTimer=setTimeout(run(async()=>{
  if(!active()||live()||!dirty||conflict)return;
  if(pictureSources.some(k=>config.sources[k].enabled&&!config.sources[k].target)){message('Bitte für die eingeschaltete Quelle ein Gerät auswählen.');return;}
  await save();if(pictureSources.some(k=>config.sources[k].enabled)){state=await api('prepare');schedulePreview(150);message('Quelle eingeschaltet. Vorschau wird geladen.');}else message('Bildquellen ausgeschaltet.');
 }),600);
}

function status(){if(!initialized||!state||!config)return;renderCollection();const working=busy||state.busy,streaming=live(),delegated=state.detached&&!detached;$('dirty').textContent=conflict?'In anderem Fenster geändert':dirty?'Ungespeicherte Änderungen':'Gespeichert';
 $('workspace').hidden=delegated;$('detached-note').hidden=!delegated;$('detach').hidden=detached||delegated;$('attach').hidden=!detached;$('top-label').hidden=!detached;$('top').checked=state.alwaysOnTop===true;$('reload').hidden=!conflict;for(const id of ['import','obs-import','export','save','dirty'])$(id).hidden=delegated;
 if(delegated){clearTimeout(sourceTimer);invalidatePreview();if($('canvas').querySelector('img'))canvas();}
 for(const id of ['detach','attach','focus','dock'])$(id).disabled=working;
 $('companion').textContent=state.companionLive?'LIVE-Studio-Sitzung beenden':'LIVE-Studio-Sitzung markieren';$('companion').setAttribute('aria-pressed',String(state.companionLive));
 $('current-scene').textContent='Ausgabe · TikTok: '+outputName('tiktok')+' · Twitch: '+outputName('twitch')+' · '+(state.engineRunning?'im eigenen Sender':'wird beim Vorbereiten übernommen');for(const id of ['scene-apply','program-save','show-game'])$(id).disabled=working||conflict;
 for(const id of ['background','background-clear'])$(id).disabled=working||streaming||conflict||!['Pause','Start','Ende'].includes($('scene').value);backgroundNote();
 for(const id of ['obs-apply','obs-cancel'])$(id).disabled=working;$('obs-dialog').querySelectorAll('select').forEach(select=>{select.disabled=working;});
 $('collection-scenes').querySelectorAll('button').forEach(button=>{button.disabled=working||conflict;});
 $('readiness').textContent=(state.libraryFound?'Videobibliotheken vorhanden. ':'Videobibliotheken fehlen; vorhandenen OBS-Ordner auswählen. ')+(state.engineRunning?'Video-Dienst eingeschaltet.':'Video-Dienst aus – keine laufende Aufnahme.')+' Ton wählst du in LIVE Studio.';
 for(const p of ['tiktok','twitch']){const o=state.state.outputs?.[p],running=['camera','live','connecting','test'].includes(o?.state),camera=state.state.virtualCameras?.[p]||state.probe?.virtualCameras?.[p];$('status-'+p).textContent=running?'Kamera läuft':o?.state==='error'?'Fehler':'Aus';$('status-'+p).classList.toggle('live',running);$('metrics-'+p).textContent=(o?.cameraName||camera?.name||'Batto '+labels[p])+(o?` · ${o.width} × ${o.height} · 30 FPS\n${o.frames} Bilder`:' · noch nicht gestartet');$('error-'+p).textContent=o?.error||(!camera?.ready?camera?.error||'':'');$('start-'+p).disabled=working||running;$('stop-'+p).disabled=working||!running;}
 for(const id of ['save','import','obs-import','probe','library','register','template','prepare','profile','kind','layer','visible','x','y','width','height','fit'])$(id).disabled=working||streaming;
 for(const id of ['template','layer','visible','x','y','width','height','fit'])$(id).disabled=working||streaming||!editingShared();
 $('save').disabled=working||streaming||conflict;$('export').disabled=working||conflict;
 for(const s of pictureSources){$('source-'+s).disabled=working||streaming;$('target-'+s).disabled=working||streaming;}
 $('gaming').disabled=working;previewNote();
 $('release').disabled=working||streaming||!state.engineRunning;$('preview').disabled=working||(!state.state.prepared&&streaming);$('preview-mode').disabled=working;$('start-both').disabled=working||streaming;$('stop-both').disabled=working||!streaming;
}
async function init(){if(initialized)return;if(!visible())return;initialized=true;build();try{adopt(await api('state'));schedulePreview(0);if(state.error)message(state.error);}catch(e){message(e.message);}}
document.addEventListener('batto:view',()=>{if(active()){void init();status();schedulePreview(0);}else invalidatePreview(false);});document.addEventListener('visibilitychange',()=>{if(active()){status();schedulePreview(0);}else invalidatePreview(false);});
window.batto.onPresentationState?.(()=>{if(active())schedulePreview(0);else invalidatePreview(false);});
window.batto.onDualState(next=>{
 const changedRevision=next.revision!==baseRevision;state=next;
 if(initialized&&config){
  if(changedRevision&&!dirty)adopt(next);
  else if(changedRevision&&dirty){conflict=true;clearTimeout(sourceTimer);invalidatePreview();message('Dual Stream wurde inzwischen geändert. Dein Entwurf bleibt erhalten; lade vor dem Speichern den aktuellen Stand.');}
  if(!next.state.prepared){invalidatePreview();canvas();}
  status();if(active())schedulePreview();else invalidatePreview();
 }
});
if(detached)void init();
})();
