(()=>{'use strict';
const root=document.getElementById('dual-root'),$=id=>document.getElementById('dual-'+id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,config,initialized=false,dirty=false,selected='tiktok',layer='game',drag=null,busy=false,snapshot=null;
const labels={tiktok:'TikTok',twitch:'Twitch',game:'Spiel / Bildschirm',camera:'Kamera',microphone:'Mikrofon',desktop:'PC-Ton'};
const active=()=>!window.BattoResources?.suspended&&!document.hidden&&document.getElementById('view-dualstream').classList.contains('active');
const live=()=>Object.values(state?.state.outputs||{}).some(o=>['live','connecting','test'].includes(o.state));
function message(text){$('message').textContent=text;}
async function api(command,value){return window.batto.dual(command,value);}
function run(fn){return async event=>{event?.preventDefault();if(busy)return;busy=true;status();try{await fn(event);}catch(e){message(String(e.message).replace(/^Error invoking remote method [^:]+: Error: /,''));}finally{busy=false;status();}};}
function on(id,fn){$(id).addEventListener('click',run(fn));}
function build(){
 root.innerHTML=`<div class="dual-toolbar"><button id="dual-import">Projekt importieren</button><button id="dual-export">Projekt exportieren</button><button id="dual-save" class="primary">Änderungen speichern</button><span id="dual-dirty" class="suite-help"></span></div>
 <div id="dual-message" class="dual-message" role="status" aria-live="polite"></div>
 <article class="suite-panel"><div class="dual-toolbar"><label>Qualität <select id="dual-profile"><option value="economy_720p30">Sparprofil · 720p / 30 FPS</option><option value="fullhd_1080p30">Full HD · 1080p / 30 FPS</option></select></label><button id="dual-probe">Geräte erkennen</button><button id="dual-library">OBS-Bibliotheken wählen</button></div><div id="dual-readiness" class="dual-readiness"></div><div id="dual-sources">${['game','camera','microphone','desktop'].map(s=>`<div class="dual-source-row"><label class="suite-check"><input id="dual-source-${s}" type="checkbox"> ${labels[s]}</label>${s==='game'?'<select id="dual-kind" aria-label="Aufnahmeart"><option value="game">Spielaufnahme</option><option value="window">Fensteraufnahme</option><option value="screen">Bildschirmaufnahme</option></select>':'<span class="suite-help">Für beide Ziele gemeinsam</span>'}<select id="dual-target-${s}" aria-label="${labels[s]} auswählen"></select></div>`).join('')}</div></article>
 <article class="suite-panel"><h3>Szenen &amp; Einblendungen</h3><div class="dual-toolbar"><label>Szene<select id="dual-scene"><option>Spiel</option><option>Pause</option><option>Start</option><option>Ende</option></select></label><label>Übergang<select id="dual-transition"><option value="fade">Überblenden</option><option value="cut">Schnitt</option></select></label><label>Dauer (ms)<input id="dual-transition-ms" type="number" min="100" max="2000" step="50" value="350"></label><button id="dual-scene-apply" class="primary">Szene auf beide Ausgaben schalten</button><button id="dual-background">Hintergrundbild wählen</button></div><div class="dual-toolbar"><label class="suite-check"><input id="dual-chat-overlay" type="checkbox"> Chat im Stream zeigen</label><label class="suite-check"><input id="dual-events-overlay" type="checkbox"> Ereignisse im Stream zeigen</label><button id="dual-program-save">Einblendungen speichern</button></div><div class="dual-toolbar"><button id="dual-companion">LIVE-Studio-Sitzung markieren</button><button id="dual-chat-url">Chat-Adresse für LIVE Studio kopieren</button><button id="dual-events-url">Ereignis-Adresse kopieren</button></div><p id="dual-current-scene" class="suite-help"></p><p class="suite-help">Start, Pause und Ende verwenden deine Hintergrundbilder. Die Chat-Einblendung zeigt die letzten vier Nachrichten. Für TikTok LIVE Studio kannst du die vorhandene Stream-Ansicht als Browserquelle verwenden; der eigene Video-Dienst kann dabei ausgeschaltet bleiben.</p></article>
 <article class="suite-panel"><div class="dual-toolbar" role="tablist" aria-label="Leinwand"><button id="dual-tab-tiktok" class="dual-tab" role="tab">TikTok · 9:16</button><button id="dual-tab-twitch" class="dual-tab" role="tab">Twitch · 16:9</button><span id="dual-dimensions" class="suite-help"></span></div>
 <div class="dual-editor"><div><div class="dual-canvas-wrap"><div id="dual-canvas" class="dual-canvas tiktok" aria-label="Leinwand mit verschiebbaren Quellen"></div></div><p id="dual-preview-note" class="suite-help">Layoutansicht · Bildquellen auswählen, vorbereiten und ein Vorschaubild abrufen.</p><div class="dual-toolbar"><button id="dual-prepare">Quellen vorbereiten</button><button id="dual-preview">Vorschaubild aktualisieren</button><button id="dual-release">Video-Dienst ausschalten</button></div></div>
 <div><h3>Quelle anordnen</h3><label>Bildquelle<select id="dual-layer"><option value="game">Spiel / Bildschirm</option><option value="camera">Kamera</option></select></label><label class="suite-check"><input id="dual-visible" type="checkbox"> Auf dieser Leinwand zeigen</label><div class="dual-form-grid">${[['x','Links (%)'],['y','Oben (%)'],['width','Breite (%)'],['height','Höhe (%)']].map(([k,t])=>`<label>${t}<input id="dual-${k}" type="number" min="${k==='width'||k==='height'?2:0}" max="100" step="0.1"></label>`).join('')}</div><label>Einpassen<select id="dual-fit"><option value="contain">Vollständig zeigen</option><option value="cover">Fläche füllen / beschneiden</option></select></label><p class="suite-help">Quelle im Bild verschieben oder Prozentwerte eintragen. Beide Leinwände speichern ihre Anordnung getrennt.</p></div></div></article>
 <div class="dual-output-grid">${['tiktok','twitch'].map(p=>`<article class="suite-panel"><div class="dual-output-title"><h3>${labels[p]}</h3><span id="dual-status-${p}" class="dual-status">Aus</span></div><div id="dual-metrics-${p}" class="dual-metrics"></div><label>RTMP-/RTMPS-Server<input id="dual-server-${p}" type="url" autocomplete="off" spellcheck="false" placeholder="Serveradresse des Anbieters"></label><label>Stream-Key <span id="dual-key-state-${p}"></span></label><div class="dual-key"><input id="dual-key-${p}" type="password" autocomplete="new-password" aria-label="${labels[p]} Stream-Key"><button id="dual-key-save-${p}">Schlüssel speichern</button></div><div class="dual-toolbar"><button id="dual-key-clear-${p}">Schlüssel löschen</button><label class="suite-check"><input id="dual-mute-${p}" type="checkbox"> Ton stumm</label></div><div class="dual-toolbar"><button id="dual-start-${p}" class="primary">${labels[p]} starten</button><button id="dual-stop-${p}">Stoppen</button></div><div id="dual-error-${p}" class="suite-help"></div></article>`).join('')}</div>
 <div class="dual-toolbar"><button id="dual-start-both" class="primary">Beide Streams starten</button><button id="dual-stop-both">Beide stoppen</button></div><p class="suite-help">Kein automatischer Sendestart. TikTok benötigt einen freigeschalteten Sendezugang. Schlüssel bleiben mit Windows verschlüsselt auf diesem PC und fehlen im Projektexport. Das Vorschaubild ist eine Momentaufnahme; die Ausgaben laufen mit 30 FPS. Nach 60 Sekunden ohne Ausgabe oder Bildabfrage schaltet sich der Video-Dienst aus.</p>`;
 on('companion',async()=>{await window.batto.suite('control',{action:'companion'});state=await api('state');message('Live-Markierung gilt für Bot-Regeln und Auto-Broadcast. LIVE Studio selbst wird dadurch nicht gestartet oder gestoppt.');});
 for(const kind of ['chat','events'])on(kind+'-url',async()=>{await window.batto.copyText(overlayBase()+'/overlay/'+kind);message('Adresse kopiert. In LIVE Studio als Browserquelle hinzufügen.');});
 on('scene-apply',async()=>{if(dirty)await save();state=await api('scene',{scene:$('scene').value,transition:$('transition').value,durationMs:Number($('transition-ms').value)});config.program=JSON.parse(JSON.stringify(state.config.program));snapshot=null;canvas();message('Szene '+config.program.scene+' ausgewählt.');});
 on('program-save',async()=>{state=await api('program',{...state.config.program,chat:$('chat-overlay').checked,events:$('events-overlay').checked});config.program=JSON.parse(JSON.stringify(state.config.program));message('Einblendungen gespeichert.');});
 on('background',async()=>{const scene=$('scene').value;if(scene==='Spiel')throw Error('Für Spiel wählst du die Bildquelle im oberen Bereich.');const next=await api('background',scene);if(next){state=next;config.program=JSON.parse(JSON.stringify(next.config.program));message('Hintergrund gespeichert.');}});
 on('save',save);on('probe',async()=>{if(dirty)await save();state=await api('probe');fillDevices();status();message(state.probe.encoder?'Geräte und Hardware-Encoder erkannt.':'Keine unterstützten Hardware-Encoder erkannt.');});
 on('library',async()=>{if(dirty)await save();const next=await api('library');if(next)adopt(next);});
 on('import',async()=>{const next=await api('import');if(next){adopt(next);message('Projekt übernommen. Aufnahmequellen und Sendezugänge bitte zuordnen.');}});
 on('export',async()=>{if(dirty)await save();const r=await api('export');if(r.saved)message('Projekt ohne Stream-Keys exportiert.');});
 on('prepare',async()=>{if(dirty)await save();state=await api('prepare');message('Quellen vorbereitet. Es wird noch nicht gesendet.');});
 on('release',async()=>{state=await api('release');snapshot=null;canvas();message('Video-Dienst ausgeschaltet.');});
 on('preview',async()=>{if(dirty)await save();if(!state.state.prepared)state=await api('prepare');snapshot=await api('snapshot',selected);canvas();});
 for(const p of ['tiktok','twitch']){
  $('tab-'+p).onclick=()=>{selected=p;snapshot=null;editor();canvas();};
  on('key-save-'+p,async()=>{const key=$('key-'+p).value;if(!key)throw Error('Bitte zuerst den Stream-Key eintragen.');state=await api('key',{platform:p,key});$('key-'+p).value='';message('Schlüssel verschlüsselt gespeichert.');});
  on('key-clear-'+p,async()=>{state=await api('key',{platform:p,key:''});$('key-'+p).value='';message('Schlüssel entfernt.');});
  on('start-'+p,()=>start(p));on('stop-'+p,async()=>{state=await api('stop',p);});
  $('server-'+p).addEventListener('input',()=>{config.destinations[p].server=$('server-'+p).value;changed();});
  $('mute-'+p).addEventListener('change',run(async()=>{const muted=$('mute-'+p).checked;state=await api('mute',{platform:p,muted});config.destinations[p].muted=muted;}));
 }
 on('start-both',()=>start('both'));on('stop-both',async()=>{state=await api('stop','both');});
 $('profile').onchange=()=>{config.profile=$('profile').value;changed();canvas();};
 $('kind').onchange=()=>{config.sources.game.kind=$('kind').value;config.sources.game.target='';config.sources.game.name='';config.sources.game.enabled=false;changed();fillDevices();canvas();};
 for(const s of ['game','camera','microphone','desktop']){
  $('source-'+s).onchange=()=>{config.sources[s].enabled=$('source-'+s).checked;changed();canvas();};
  $('target-'+s).onchange=()=>{config.sources[s].target=$('target-'+s).value;config.sources[s].name=$('target-'+s).selectedOptions[0]?.textContent||'';changed();};
 }
 $('layer').onchange=()=>{layer=$('layer').value;editor();canvas();};
 for(const k of ['x','y','width','height','visible','fit'])$(''+k).addEventListener('change',()=>{const item=config.layouts[selected].find(x=>x.source===layer);if(k==='visible')item[k]=$('visible').checked;else if(k==='fit')item[k]=$('fit').value;else{const n=Number($(k).value)/100;if(!Number.isFinite(n))return;item[k]=Math.max(k==='width'||k==='height'?.02:0,Math.min(1,n));if(item.x+item.width>1)item.x=1-item.width;if(item.y+item.height>1)item.y=1-item.height;}changed();editor();canvas();});
 const stage=$('canvas');stage.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-dual-source]');if(!el||live())return;layer=el.dataset.dualSource;const item=config.layouts[selected].find(x=>x.source===layer);drag={pointer:e.pointerId,x:e.clientX,y:e.clientY,startX:item.x,startY:item.y,rect:stage.getBoundingClientRect()};stage.setPointerCapture(e.pointerId);editor();e.preventDefault();});
 stage.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;const item=config.layouts[selected].find(x=>x.source===layer);item.x=Math.max(0,Math.min(1-item.width,drag.startX+(e.clientX-drag.x)/drag.rect.width));item.y=Math.max(0,Math.min(1-item.height,drag.startY+(e.clientY-drag.y)/drag.rect.height));changed();editor();canvas();});
 const end=e=>{if(drag?.pointer===e.pointerId){drag=null;if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);}};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);
}
function changed(){dirty=true;snapshot=null;status();}
async function save(){state=await api('save',config);adopt(state);message('Dual-Stream-Einstellungen gespeichert.');}
async function start(p){if(dirty)await save();state=await api('start',p);message('Verbindung wird aufgebaut. „Live“ erscheint erst bei übertragenen Daten.');}
function adopt(next){state=next;config=JSON.parse(JSON.stringify(next.config));dirty=false;snapshot=null;$('scene').value=config.program.scene;$('transition').value=config.program.transition;$('transition-ms').value=config.program.durationMs;$('chat-overlay').checked=config.program.chat;$('events-overlay').checked=config.program.events;$('profile').value=config.profile;$('kind').value=config.sources.game.kind;for(const p of ['tiktok','twitch']){$('server-'+p).value=config.destinations[p].server;$('mute-'+p).checked=config.destinations[p].muted;}fillDevices();editor();canvas();status();}
function fillDevices(){for(const s of ['game','camera','microphone','desktop']){const current=config.sources[s],items=state.probe?.devices?.[s==='game'?current.kind:s]||[],valid=items.filter(x=>x.id);$('target-'+s).innerHTML='<option value="">Bitte auswählen</option>'+valid.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');if(current.target&&!valid.some(x=>x.id===current.target))$('target-'+s).insertAdjacentHTML('beforeend',`<option value="${esc(current.target)}">${esc(current.name||'Gespeicherte Quelle')} · noch nicht geprüft</option>`);$('target-'+s).value=current.target;$('source-'+s).checked=current.enabled;}}
function editor(){const item=config.layouts[selected].find(x=>x.source===layer);$('layer').value=layer;for(const k of ['x','y','width','height'])$(k).value=(item[k]*100).toFixed(1);$('visible').checked=item.visible;$('fit').value=item.fit;}
function canvas(){if(!config)return;const stage=$('canvas');stage.className='dual-canvas '+selected;for(const p of ['tiktok','twitch'])$('tab-'+p).setAttribute('aria-selected',String(p===selected));const hd=config.profile==='fullhd_1080p30';$('dimensions').textContent=(selected==='tiktok'?(hd?'1080 × 1920':'720 × 1280'):(hd?'1920 × 1080':'1280 × 720'))+' · 30 FPS';
 stage.innerHTML=(snapshot?`<img alt="Letztes Vorschaubild von ${labels[selected]}" src="${snapshot.image}">`:'')+config.layouts[selected].filter(x=>x.visible).map(x=>`<button type="button" data-dual-source="${x.source}" class="dual-layer ${x.source===layer?'selected':''} ${config.sources[x.source].enabled?'':'disabled'}" style="left:${x.x*100}%;top:${x.y*100}%;width:${x.width*100}%;height:${x.height*100}%" aria-label="${labels[x.source]} verschieben"><span>${labels[x.source]}${config.sources[x.source].enabled?'':' · aus'}</span></button>`).join('');
 $('preview-note').textContent=snapshot?'Momentaufnahme von '+new Date(snapshot.capturedAt).toLocaleTimeString('de-DE')+' · keine laufende Vorschau.':'Layoutansicht · „Vorschaubild aktualisieren“ zeigt das echte Ausgangsbild. Änderungen zuerst speichern.';
}
function status(){if(!initialized||!state||!config)return;const working=busy||state.busy,streaming=live();$('dirty').textContent=dirty?'Ungespeicherte Änderungen':'Gespeichert';
 $('companion').textContent=state.companionLive?'LIVE-Studio-Sitzung beenden':'LIVE-Studio-Sitzung markieren';$('companion').setAttribute('aria-pressed',String(state.companionLive));
 $('current-scene').textContent='Ausgewählt: '+state.config.program.scene+' · '+(state.engineRunning?'im eigenen Sender':'wird beim Vorbereiten übernommen');for(const id of ['scene-apply','program-save','background'])$(id).disabled=working;
 const encoder=state.probe?.encoder||state.state.encoder;$('readiness').textContent=(state.libraryFound?'OBS-Bibliotheken vorhanden. ':'OBS-Bibliotheken fehlen; vorhandenen OBS-Ordner auswählen. ')+(encoder?'Hardware-Encoder: '+(encoder.includes('nvenc')?'NVIDIA NVENC':encoder.includes('amf')?'AMD AMF':'Intel QSV')+'. ':'Mit „Geräte erkennen“ die Aufnahmequellen prüfen. ')+(state.engineRunning?'Video-Dienst eingeschaltet.':'Video-Dienst aus – keine laufende Aufnahme.')+' Rechnerischer Upload: '+(config.profile==='fullhd_1080p30'?'10,76':'6,46')+' Mbit/s plus Reserve; noch kein Verbindungstest.';
 for(const p of ['tiktok','twitch']){const o=state.state.outputs?.[p],running=['live','connecting','test'].includes(o?.state),label={live:'Live',connecting:'Verbinden…',test:'Lokaler Test',error:'Fehler',stopped:'Aus'}[o?.state]||'Aus';$('status-'+p).textContent=label;$('status-'+p).classList.toggle('live',o?.state==='live');$('metrics-'+p).textContent=o?`${o.width} × ${o.height} · 30 FPS · ${o.bitrate} kbit/s\n${o.frames} Bilder · ${o.droppedFrames} verworfen · ${(o.bytes/1048576).toFixed(1)} MiB übertragen`:'Sendezugang einrichten. Noch keine Ausgabe gestartet.';$('key-state-'+p).textContent=state.keys[p]?'· gespeichert':'· fehlt';$('error-'+p).textContent=o?.error||'';$('start-'+p).disabled=working||running||!state.keys[p]||!config.destinations[p].server;$('stop-'+p).disabled=working||!running;$('server-'+p).disabled=streaming||working;}
 for(const id of ['save','import','probe','library','prepare','profile','kind','layer','visible','x','y','width','height','fit'])$(id).disabled=working||streaming;
 for(const p of ['tiktok','twitch'])for(const id of ['mute-','key-','key-save-','key-clear-'])$(id+p).disabled=working;
 $('export').disabled=working;
 for(const s of ['game','camera','microphone','desktop']){$('source-'+s).disabled=working||streaming;$('target-'+s).disabled=working||streaming;}
 $('release').disabled=working||streaming||!state.engineRunning;$('preview').disabled=working||(!state.state.prepared&&streaming);$('start-both').disabled=working||streaming||!state.keys.tiktok||!state.keys.twitch||!config.destinations.tiktok.server||!config.destinations.twitch.server;$('stop-both').disabled=working||!streaming;
}
async function init(){if(initialized)return;if(!active())return;initialized=true;build();try{adopt(await api('state'));if(state.error)message(state.error);}catch(e){message(e.message);}}
document.addEventListener('batto:view',()=>{if(active()){void init();status();}});document.addEventListener('visibilitychange',()=>{if(active())status();});
window.batto.onDualState(next=>{const previous=state?.config.program;state=next;if(initialized&&config){const fields={scene:'scene',transition:'transition',durationMs:'transition-ms',chat:'chat-overlay',events:'events-overlay'};for(const [key,id]of Object.entries(fields)){const el=$(id),check=['chat','events'].includes(key),current=check?el.checked:el.value;if(previous&&String(current)===String(previous[key])){if(check)el.checked=next.config.program[key];else el.value=next.config.program[key];}}config.program=JSON.parse(JSON.stringify(next.config.program));for(const p of ['tiktok','twitch']){$('mute-'+p).checked=next.config.destinations[p].muted;config.destinations[p].muted=next.config.destinations[p].muted;}}if(active())status();});
})();
