(()=>{'use strict';
const nav=document.getElementById('mainNav'),content=document.querySelector('[data-view-panel="fans"]')?.parentElement;
if(!nav||!content)return;
const panel=document.getElementById('view-rgb');if(!panel)return;
panel.innerHTML='<div class="suite-rgb-heading"><div><h2>RGB-Steuerung</h2><p>Dein PC, deine Farben. Effekte, Geräte und Lichtprofile mit der RGB-Steuerung.</p></div><button id="rgb-start" type="button">RGB öffnen</button><button id="rgb-stop" type="button">RGB-Dienst beenden</button></div><p id="rgb-error" role="alert" hidden></p><details class="suite-rgb-help"><summary>RGB mit Jarvis steuern</summary><p>„Jarvis, RGB rot.“ · „RGB Effekt Regenbogen.“ · „RGB Helligkeit 50 Prozent.“ · „RGB aus.“ · „RGB an.“</p><p>Jarvis verwendet die zuletzt angewendeten RGB-Geräte. Ohne vorherige Auswahl werden alle unterstützten RGB-Geräte angesprochen. Normale Lüfterdrehzahlen stellst du unter „iCUE LINK Lüfter“ dar.</p></details><iframe id="rgb-frame" title="RGB-Steuerung" hidden></iframe>';
const frame=panel.querySelector('#rgb-frame'),error=panel.querySelector('#rgb-error'),start=panel.querySelector('#rgb-start'),stop=panel.querySelector('#rgb-stop');let state=null,pending=false,revision=-1;
function showError(value){const message=String(value||'').replace(/^Error invoking remote method '[^']+':\s*(?:Error:\s*)?/,'');error.textContent=message;error.hidden=!message;}
function update(next){state=next?.rgb||next;if(!state)return;stop.disabled=!state.running;start.textContent=state.running?'RGB erneut laden':'RGB öffnen';showError(state.error);if(!state.running){frame.hidden=true;frame.removeAttribute('src');revision=-1;return;}if(state.revision!==revision&&state.revision>0){revision=state.revision;if(frame.contentWindow&&state.url)frame.contentWindow.postMessage({type:'suite:rgb-settings',settings:state.lastSettings,off:!state.active?.length},new URL(state.url).origin);}}
async function open(){if(pending)return;pending=true;start.disabled=true;showError('');try{const result=await window.batto.suite('rgb-start');update(result);const url=new URL(result.url);if(url.protocol!=='http:'||url.hostname!=='127.0.0.1')throw Error('Die lokale RGB-Oberfläche ist nicht erreichbar.');if(frame.src!==url.href)frame.src=url.href;frame.hidden=false;}catch(e){showError(e.message);}finally{pending=false;start.disabled=false;}}
start.addEventListener('click',open);stop.addEventListener('click',async()=>{stop.disabled=true;try{await window.batto.suite('rgb-stop');update(await window.batto.suite('rgb-state'));}catch(e){showError(e.message);stop.disabled=false;}});
document.addEventListener('batto:view',e=>{if(e.detail==='rgb')void open();});
window.batto.onSuiteState(next=>update(next));
frame.addEventListener('load',()=>{if(state?.running&&state.revision>0){revision=-1;update(state);}});
})();
