(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,settings={},selectedSensor='',selectedFan='',scene=null,drag=null,curve=null,curvesKey='',sceneNames=[],toastTimer,initialized=false,fanBusy=false,lastSelection='';
const clone=x=>JSON.parse(JSON.stringify(x)),sensors=()=>state?.fan?.state?.sensors||[],fan=()=>scene?.tiles.find(t=>t.id===selectedFan);
const fmt=s=>s?.fresh&&Number.isFinite(s.value)?s.value.toLocaleString('de-DE',{maximumFractionDigits:['V','A'].includes(s.unit)?2:1})+' '+s.unit:'—';
function toast(text){let el=$('suite-toast');if(!el){el=document.createElement('div');el.id='suite-toast';el.className='suite-toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,6500);}
async function api(command,value,quiet=false){try{return await window.batto.suite(command,value);}catch(e){if(!quiet)toast(String(e.message).replace(/^Error invoking remote method [^:]+: Error: /,''));throw e;}}
function run(fn){return e=>{e?.preventDefault();Promise.resolve().then(()=>fn(e)).catch(()=>{});};}
function click(id,fn){$(id).addEventListener('click',run(fn));}
async function saveSettings(value){settings=await api('settings',value);toast('Einstellungen gespeichert.');return settings;}
function optionList(list,current,empty='Nicht zugeordnet'){let result=`<option value="">${esc(empty)}</option>`+list.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} · ${esc(s.unit)}</option>`).join('');if(current&&!list.some(s=>s.id===current))result+=`<option value="${esc(current)}">Quelle zurzeit nicht verfügbar</option>`;return result;}
function renderLog(){const log=$('j-log');const wasBottom=log.scrollHeight-log.scrollTop-log.clientHeight<60;log.innerHTML=(state?.jarvis?.history||[]).slice(-60).map(m=>`<div class="suite-message ${esc(m.kind)}"><small>${esc(new Date(m.time).toLocaleTimeString('de-DE'))} · ${esc(m.kind==='chat'?'MODERATOR-CHAT':m.kind==='user'?'DU':m.kind==='alert'?'MESSWERTMELDUNG':'JARVIS')}</small>${esc(m.text)}</div>`).join('')||'<div class="suite-empty">„Jarvis, GPU-Temperatur.“<br>Frage nur nach dem, was dich gerade interessiert.</div>';if(wasBottom)log.scrollTop=log.scrollHeight;}
function fillSettings(){
 for(const [id,key] of Object.entries({'j-address':'address','j-rate':'speechRate','j-chat-mode':'chatMode','j-chat-length':'chatMaxLength','j-chat-cooldown':'chatCooldown','j-model':'aiModel','j-port':'aiPort'}))$(id).value=settings[key]??'';
 for(const [id,key] of Object.entries({'j-speech':'voiceEnabled','j-mic':'microphoneEnabled','j-wake':'wakeWord','j-headphones':'headphones','j-chat':'chatEnabled','j-learn':'learn','j-ai':'localAi'}))$(id).checked=!!settings[key];
 $('j-allowlist').value=(settings.chatAllowlist||[]).join('\n');$('j-platforms').innerHTML=['twitch','youtube','tiktok','cng'].map(p=>`<label class="suite-check"><input type="checkbox" value="${p}" ${settings.chatPlatforms?.includes(p)?'checked':''}> ${p}</label>`).join('');
 $('j-runtime').textContent=settings.voiceRuntime||'Mitgeliefertes Sprachpaket';renderScenes();
}
function renderScenes(){const labels={pause:'„Jarvis Pause“',spiel:'„Jarvis Spiel / Weiter“',start:'„Jarvis Start“',ende:'„Jarvis Ende“'};$('j-scenes').innerHTML=Object.entries(labels).map(([key,label])=>{const current=settings.sceneAliases?.[key]||'';const all=[...new Set([...sceneNames,...(current?[current]:[])])];return `<label>${label}<select data-scene="${key}"><option value="">Noch nicht zugeordnet</option>${all.map(n=>`<option ${n===current?'selected':''} value="${esc(n)}">${esc(n)}</option>`).join('')}</select></label>`;}).join('');}
async function command(text){if(!text?.trim())return;state.jarvis.history.push({kind:'user',text,time:Date.now()});renderLog();const result=await api('command',text);if(!result.ok)toast(result.text);}
$('j-command-form').addEventListener('submit',run(async()=>{const text=$('j-command').value;$('j-command').value='';await command(text);}));
document.querySelectorAll('[data-jarvis]').forEach(b=>b.addEventListener('click',run(()=>command(b.dataset.jarvis))));
click('j-listen',()=>api('listen'));click('j-stop',()=>api('stop'));click('j-devices',()=>api('devices'));
click('j-save-voice',()=>saveSettings({address:$('j-address').value,voiceEnabled:$('j-speech').checked,microphoneEnabled:$('j-mic').checked,wakeWord:$('j-wake').checked,headphones:$('j-headphones').checked,speechRate:Number($('j-rate').value),microphone:$('j-device').value===''?null:Number($('j-device').value)}));
click('j-folder',async()=>{const s=await api('voice-folder');if(s){settings=s;fillSettings();}});
click('j-save-chat',()=>saveSettings({chatEnabled:$('j-chat').checked,chatMode:$('j-chat-mode').value,chatPlatforms:[...$('j-platforms').querySelectorAll('input:checked')].map(e=>e.value),chatAllowlist:$('j-allowlist').value.split(/\s+/).filter(Boolean),chatMaxLength:Number($('j-chat-length').value),chatCooldown:Number($('j-chat-cooldown').value)}));
click('j-refresh-scenes',async()=>{sceneNames=await api('scenes');renderScenes();if(!sceneNames.length)toast('OBS zuerst verbinden, damit seine Szenen geladen werden können.');});
click('j-save-scenes',()=>saveSettings({sceneAliases:Object.fromEntries([...$('j-scenes').querySelectorAll('select')].map(e=>[e.dataset.scene,e.value]))}));
$('j-learn').addEventListener('change',run(()=>saveSettings({learn:$('j-learn').checked})));
click('j-forget',async()=>{await api('forget-memory');toast('Gespeicherte Befehle gelöscht.');});
click('j-save-ai',()=>saveSettings({localAi:$('j-ai').checked,aiModel:$('j-model').value,aiPort:Number($('j-port').value)}));click('j-plugin',()=>api('plugin'));
function renderSensors(){const all=sensors(),q=$('s-search').value.toLowerCase(),showHidden=$('s-show-hidden').checked;$('s-count').textContent=`${all.filter(s=>s.fresh).length} aktuelle Messwerte · ${all.length} erkannt`;
 const visible=all.filter(s=>(showHidden||settings.sensorRules?.[s.id]?.visible!==false)&&`${s.name} ${s.device} ${s.unit} ${settings.sensorRules?.[s.id]?.alias||''}`.toLowerCase().includes(q));
 $('s-list').innerHTML=visible.map(s=>{const r=settings.sensorRules?.[s.id]||{};return `<button class="suite-sensor ${s.id===selectedSensor?'selected':''} ${!s.fresh?'stale':''} ${r.visible===false?'hidden-rule':''}" data-sensor="${esc(s.id)}"><span>${esc(r.alias||s.name)}<small>${esc(s.device)} · ${esc(s.name)}${r.alert?' · Meldung aktiv':''}${!s.fresh?' · Quelle veraltet':''}</small></span><strong>${esc(fmt(s))}</strong></button>`;}).join('')||'<div class="suite-empty">Keine passenden Messwerte.<br>Weitere Sensoren über ein laufendes Protokoll oder HWiNFO verbinden.</div>';
 const s=all.find(s=>s.id===selectedSensor);if(s)$('s-reading').textContent=`${fmt(s)} · ${s.fresh?'Aktuell':'Nicht verfügbar'} · ${s.unit}`;
 const sources=state?.fan?.sources;$('s-sources').textContent=state?.fanError?state.fanError:[sources?.nvidia,sources?.hwinfo,...(sources?.csv||[])].filter(Boolean).join('\n');
 const paths=state?.fan?.csvPaths||[];const signature=JSON.stringify(paths);if($('s-csv-list').dataset.paths!==signature){$('s-csv-list').dataset.paths=signature;$('s-csv-list').innerHTML=paths.map((p,i)=>`<div class="suite-csv-item"><span>${esc(p)}</span><button data-remove-csv="${i}">Trennen</button></div>`).join('');}
}
function selectSensor(id){selectedSensor=id;const s=sensors().find(s=>s.id===id);if(!s)return;const r={alias:'',visible:true,readable:true,alert:false,mode:'above',threshold:s.unit==='°C'?80:s.value||0,delta:s.unit==='V'?.2:5,hysteresis:s.unit==='V'?.05:2,cooldown:60,...settings.sensorRules?.[id]};$('s-rule').hidden=false;$('s-name').textContent=s.name;for(const k of ['alias','mode','threshold','delta','hysteresis','cooldown'])$('s-'+k).value=r[k];for(const k of ['visible','readable','alert'])$('s-'+k).checked=r[k];renderSensors();}
$('s-list').addEventListener('click',e=>{const b=e.target.closest('[data-sensor]');if(b)selectSensor(b.dataset.sensor);});$('s-search').addEventListener('input',renderSensors);$('s-show-hidden').addEventListener('change',renderSensors);
click('s-save',async()=>{if(!selectedSensor)return;const r={};for(const k of ['alias','mode'])r[k]=$('s-'+k).value;for(const k of ['threshold','delta','hysteresis','cooldown'])r[k]=Number($('s-'+k).value);for(const k of ['visible','readable','alert'])r[k]=$('s-'+k).checked;await saveSettings({sensorRules:{...settings.sensorRules,[selectedSensor]:r}});renderSensors();});
click('s-speak',()=>{const s=sensors().find(s=>s.id===selectedSensor);if(s)return command(settings.sensorRules?.[s.id]?.alias||s.name);});
click('s-csv',()=>api('csv'));click('s-profile',()=>api('profile'));
$('s-csv-list').addEventListener('click',run(async e=>{const b=e.target.closest('[data-remove-csv]');if(b)await api('fan-config',{command:'csv',value:{paths:state.fan.csvPaths.filter((_,i)=>i!==Number(b.dataset.removeCsv))}});}));
function resizeStage(){const w=$('f-wrap').clientWidth;$('f-stage').style.transform=`scale(${w/1920})`;}
new ResizeObserver(resizeStage).observe($('f-wrap'));
function renderStage(){if(!scene)return;const el=$('f-stage');el.style.backgroundImage=scene.background?`url('./assets/${scene.background==='stream-startet.jpg'?'stream-startet.jpg':'bin-gleich-zurueck.jpg'}')`:'none';$('f-background').value=scene.background;
 if(!drag){el.innerHTML=scene.tiles.map(t=>{const temp=sensors().find(s=>s.id===t.temperatureSensorId),rpm=sensors().find(s=>s.id===t.rpmSensorId);return `<div class="suite-fan ${t.id===selectedFan?'selected':''}" data-fan="${esc(t.id)}" aria-hidden="${!t.visible}" style="left:${t.x}px;top:${t.y}px;width:${t.size}px;height:${t.size}px"><img src="./assets/fan.png" alt=""><span class="temp" style="font-size:${t.size*.115}px">${esc(fmt(temp))}</span><div class="caption">${esc(t.name)}<br><small>${esc(fmt(rpm))}</small></div></div>`;}).join('');}
 $('f-state').textContent=state?.fanError||`${scene.tiles.length} Lüfterkacheln · Layout wird lokal gespeichert`;resizeStage();}
function selectFan(id){selectedFan=id;const t=fan();$('f-edit').hidden=!t;if(!t)return;for(const k of ['name','x','y','size'])$('f-'+k).value=t[k];$('f-visible').checked=t.visible;$('f-temp').innerHTML=optionList(sensors().filter(s=>s.unit==='°C'),t.temperatureSensorId);$('f-temp').value=t.temperatureSensorId;$('f-rpm').innerHTML=optionList(sensors().filter(s=>s.unit==='RPM'||s.unit==='%'),t.rpmSensorId);$('f-rpm').value=t.rpmSensorId;renderStage();}
async function saveStage(){if(!scene)return;fanBusy=true;try{await api('fan-config',{command:'stage',value:scene});}finally{fanBusy=false;}}
$('f-stage').addEventListener('pointerdown',e=>{const el=e.target.closest('[data-fan]');if(!el)return;e.preventDefault();selectFan(el.dataset.fan);const t=fan();drag={id:t.id,x:e.clientX,y:e.clientY,originalX:t.x,originalY:t.y,pointer:e.pointerId};$('f-stage').setPointerCapture(e.pointerId);});
$('f-stage').addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;const t=fan(),scale=$('f-wrap').clientWidth/1920;t.x=Math.max(0,Math.min(1920-t.size,Math.round(drag.originalX+(e.clientX-drag.x)/scale)));t.y=Math.max(0,Math.min(1080-t.size-64,Math.round(drag.originalY+(e.clientY-drag.y)/scale)));const el=[...$('f-stage').children].find(n=>n.dataset.fan===t.id);if(el){el.style.left=t.x+'px';el.style.top=t.y+'px';}$('f-x').value=t.x;$('f-y').value=t.y;});
for(const event of ['pointerup','pointercancel'])$('f-stage').addEventListener(event,run(async()=>{if(!drag)return;drag=null;renderStage();await saveStage();}));
$('f-background').addEventListener('change',run(async()=>{if(scene){scene.background=$('f-background').value;renderStage();await saveStage();}}));
click('f-add',async()=>{if(!scene)return;if(scene.tiles.length>=32){toast('Bis zu 32 Lüfter pro Layout.');return;}const t={id:crypto.randomUUID().replaceAll('-',''),name:'Mein Lüfter',x:150,y:150,size:210,visible:true,rpmSensorId:'',temperatureSensorId:'',fromProfile:false};scene.tiles.push(t);selectFan(t.id);await saveStage();});
click('f-save',async()=>{const t=fan();if(!t)return;Object.assign(t,{name:$('f-name').value,x:Number($('f-x').value),y:Number($('f-y').value),size:Number($('f-size').value),visible:$('f-visible').checked,rpmSensorId:$('f-rpm').value,temperatureSensorId:$('f-temp').value});await saveStage();toast('Lüfter gespeichert.');});
click('f-delete',async()=>{if(!fan())return;scene.tiles=scene.tiles.filter(t=>t.id!==selectedFan);selectedFan='';$('f-edit').hidden=true;renderStage();await saveStage();});
for(const [id,cmd] of Object.entries({'f-copy':'copy-obs','f-preview':'open-obs','f-import':'import-layout','f-export':'export-layout'}))click(id,async()=>{await api(cmd);if(cmd==='copy-obs')toast('OBS-Adresse kopiert. Browserquelle auf 1920 × 1080 einstellen.');});
function renderCurve(){if(!curve)return;$('f-curve-name').value=curve.name;$('f-curve-sensor').value=curve.sensorLabel;$('f-points').innerHTML=curve.points.map((p,i)=>`<div class="suite-point"><input aria-label="Temperatur Punkt ${i+1}" data-point="${i}" data-field="temperature" type="number" min="0" max="120" step="any" value="${p.temperature}"><input aria-label="Leistung Punkt ${i+1}" data-point="${i}" data-field="duty" type="number" min="0" max="100" step="any" value="${p.duty}"><button data-delete-point="${i}" aria-label="Punkt entfernen">×</button></div>`).join('');$('f-curve-note').textContent=curve.isCustom?'Eigener Entwurf. Speichern ändert keine Hardware.':'Importierte Kurve. Speichern erstellt einen eigenen Entwurf.';drawCurve();}
function drawCurve(){const svg=$('f-graph'),points=curve?.points||[];svg.innerHTML=[0,25,50,75,100].map(v=>`<line x1="45" y1="${215-v*1.9}" x2="570" y2="${215-v*1.9}" stroke="#284259"/><text x="8" y="${220-v*1.9}" fill="#93b9d5" font-size="12">${v}%</text>`).join('')+[0,30,60,90,120].map(v=>`<text x="${39+v*4.35}" y="239" fill="#93b9d5" font-size="12">${v}°</text>`).join('')+`<polyline points="${points.map(p=>`${45+p.temperature*4.35},${215-p.duty*1.9}`).join(' ')}" fill="none" stroke="#46dcff" stroke-width="3"/>`+points.map(p=>`<circle cx="${45+p.temperature*4.35}" cy="${215-p.duty*1.9}" r="4" fill="#b6f4ff"/>`).join('');}
function syncCurves(){const curves=state?.fan?.curves||[],key=JSON.stringify(curves.map(c=>[c.id,c.name]));if(curvesKey!==key){const id=$('f-curves').value;curvesKey=key;$('f-curves').innerHTML='<option value="">Eigene Kurve erstellen …</option>'+curves.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}${c.isCustom?' · Eigene':''}</option>`).join('');$('f-curves').value=id;}
 const selected=state?.fan?.state?.selectedCurveId;if(selected&&selected!==lastSelection){lastSelection=selected;const found=curves.find(c=>c.id===selected);if(found&&document.activeElement?.closest('#view-fans')===null){curve=clone(found);$('f-curves').value=selected;renderCurve();}}
 const rows=state?.fan?.fans||[];$('f-assignments').innerHTML=rows.length?'<table class="suite-table"><thead><tr><th>Lüfter im Profil</th><th>Gespeicherte Kurve</th></tr></thead><tbody>'+rows.map(f=>`<tr><td>${esc(f.name)}</td><td>${esc(f.curveName)}</td></tr>`).join('')+'</tbody></table>':'<p class="suite-help">Noch kein iCUE-Profil importiert. Im Bereich PC-Messwerte kannst du ein exportiertes Profil laden.</p>';}
$('f-curves').addEventListener('change',()=>{const c=state?.fan?.curves?.find(c=>c.id===$('f-curves').value);if(c){curve=clone(c);renderCurve();}});
function newCurve(){curve={id:'',name:'Meine Lüfterkurve',sensorLabel:'GPU-Temperatur',isCustom:true,points:[{temperature:30,duty:30},{temperature:50,duty:50},{temperature:70,duty:80},{temperature:85,duty:100}]};$('f-curves').value='';renderCurve();}
click('f-new-curve',newCurve);click('f-duplicate-curve',()=>{if(curve){curve.id='';curve.name+=' – Kopie';curve.isCustom=true;renderCurve();}else newCurve();});
$('f-points').addEventListener('input',e=>{if(!e.target.dataset.field||!curve)return;curve.points[Number(e.target.dataset.point)][e.target.dataset.field]=Number(e.target.value);drawCurve();});
$('f-points').addEventListener('click',e=>{const b=e.target.closest('[data-delete-point]');if(b&&curve){curve.name=$('f-curve-name').value;curve.sensorLabel=$('f-curve-sensor').value;curve.points.splice(Number(b.dataset.deletePoint),1);renderCurve();}});
click('f-add-point',()=>{if(!curve)newCurve();if(curve.points.length>=20){toast('Höchstens 20 Punkte.');return;}curve.name=$('f-curve-name').value;curve.sensorLabel=$('f-curve-sensor').value;const last=curve.points.at(-1);curve.points.push({temperature:Math.min(120,(last?.temperature||20)+5),duty:last?.duty||30});renderCurve();});
click('f-save-curve',async()=>{if(!curve)return;curve.name=$('f-curve-name').value;curve.sensorLabel=$('f-curve-sensor').value;const value=clone(curve);if(!value.isCustom)value.id='';await api('fan-config',{command:'curve',value});state=await api('state');const saved=state.fan.curves.find(c=>c.id===state.fan.state.selectedCurveId);if(saved)curve=clone(saved);syncCurves();renderCurve();toast('Kurvenentwurf gespeichert. Aktive Hardwarekurve bleibt in iCUE.');});
click('f-export-curve',()=>api('export-curve',$('f-curves').value||curve?.id));
function update(next){state=next;settings=next.jarvis.settings;if(!initialized){initialized=true;fillSettings();newCurve();}if(!drag&&!fanBusy&&next.fan?.state?.scene)scene=clone(next.fan.state.scene);$('j-voice-state').textContent=next.voice.status;$('j-memory').textContent=`${next.jarvis.memory.length} erfolgreiche Befehle gemerkt · ${next.jarvis.knownSensors} Sensoren automatisch erkannt. Neue Sensoren und OBS-Szenen werden beim Verbinden erkannt.`;renderLog();renderSensors();renderStage();syncCurves();}
window.batto.onSuiteState(update);window.batto.onJarvisMessage(m=>{if(state){state.jarvis.history.push(m);renderLog();}});window.batto.onJarvisVoice(e=>{$('j-voice-state').textContent=e.text||state?.voice?.status||'';if(e.type==='state')$('j-orb').classList.toggle('speaking',e.state==='speaking');if(e.type==='devices'){$('j-device').innerHTML='<option value="">Windows-Standard</option>'+(e.items||[]).map(d=>`<option value="${d.index}">${esc(d.name)} · ${esc(d.hostapi)}</option>`).join('');$('j-device').value=settings.microphone??'';}if(e.type==='error')toast(e.text);});
async function init(){try{update(await api('state',undefined,true));}catch{setTimeout(init,1000);}}init();
})();
