(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,settings={},selectedSensor='',selectedFan='',scene=null,drag=null,curve=null,curvesKey='',sceneNames=[],toastTimer,initialized=false,fanBusy=false,lastSelection='';
let stageStructure='',logSignature='',assignmentSignature='',sensorStructure='';
let curveDirty=false,curveSaving=false;
let settingsDirty=false,settingsSignature='',commandExamplesSignature='',commandFilterSignature='',commandRenderSignature='',commandPage=0,commandPending=false,microphoneDevices=[];
const fallbackCommandExamples=[{phrase:'Pause',description:'Zur Pause-Szene wechseln'},{phrase:'Öffne das Touch Deck',description:'Touch Deck anzeigen'},{phrase:'Kamera aus',description:'Kamerabild ausblenden'},{phrase:'Auto Broadcast an',description:'Geplante Bot-Nachrichten aktivieren'},{phrase:'Jarvis leiser',description:'Sprachausgabe leiser stellen'},{phrase:'GPU Temperatur',description:'Temperatur der Grafikkarte ansagen'}];
$('view-jarvis').addEventListener('input',e=>{if(!e.target.closest('#j-command-form,.jarvis-command-help'))settingsDirty=true;});
const visibleView=id=>!window.BattoResources?.suspended&&!document.hidden&&$('view-'+id)?.classList.contains('active');
function textOnly(el,text){if(el.textContent!==text)el.textContent=text;}
const clone=x=>JSON.parse(JSON.stringify(x)),sensors=()=>state?.fan?.state?.sensors||[],fan=()=>scene?.tiles.find(t=>t.id===selectedFan);
const fmt=s=>s?.fresh&&Number.isFinite(s.value)?s.value.toLocaleString('de-DE',{maximumFractionDigits:['V','A'].includes(s.unit)?2:1})+' '+s.unit:'—';
function toast(text){let el=$('suite-toast');if(!el){el=document.createElement('div');el.id='suite-toast';el.className='suite-toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,6500);}
async function api(command,value,quiet=false){try{return await window.batto.suite(command,value);}catch(e){if(!quiet)toast(String(e.message).replace(/^Error invoking remote method '[^']+':\s*(?:Error:\s*)?/,''));throw e;}}
function run(fn){return e=>{e?.preventDefault();Promise.resolve().then(()=>fn(e)).catch(()=>{});};}
function click(id,fn){$(id).addEventListener('click',run(fn));}
async function saveSettings(value){settings=await api('settings',value);settingsDirty=false;toast('Einstellungen gespeichert.');return settings;}
function optionList(list,current,empty='Nicht zugeordnet'){let result=`<option value="">${esc(empty)}</option>`+list.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} · ${esc(s.unit)}</option>`).join('');if(current&&!list.some(s=>s.id===current))result+=`<option value="${esc(current)}">Quelle zurzeit nicht verfügbar</option>`;return result;}
function renderLog(){if(!visibleView('jarvis'))return;const messages=(state?.jarvis?.history||[]).slice(-60),key=JSON.stringify(messages);if(key===logSignature)return;logSignature=key;const log=$('j-log');const wasBottom=log.scrollHeight-log.scrollTop-log.clientHeight<60;log.innerHTML=messages.map(m=>`<div class="suite-message ${esc(m.kind)}"><small>${esc(new Date(m.time).toLocaleTimeString('de-DE'))} · ${esc(m.kind==='chat'?'CHAT VORGELESEN':m.kind==='user'?(m.source==='voice'?'ERKANNT':m.source==='streamdeck'?'STREAM DECK':'EINGABE'):m.kind==='alert'?'MESSWERTMELDUNG':m.kind==='error'?'AKTION FEHLGESCHLAGEN':m.kind==='unrecognized'?'NICHT ERKANNT':m.kind==='clarification'?'GENAUER ANGEBEN':'JARVIS')}</small>${esc(m.text)}</div>`).join('')||'<div class="suite-empty">„Jarvis, Pause.“ · „Öffne das Touch Deck.“<br>Hier siehst du deinen Befehl und danach Jarvis’ Antwort.</div>';if(wasBottom)log.scrollTop=log.scrollHeight;}
function microphoneValue(value){return value===null||value===undefined?'':typeof value==='number'?'legacy:'+value:JSON.stringify({name:value.name,hostapi:value.hostapi});}
function renderMicrophones(preserveSelection=false){
 const selected=preserveSelection?$('j-device').value:microphoneValue(settings.microphone),choices=microphoneDevices.map(d=>({value:microphoneValue({name:d.name,hostapi:d.hostapi}),label:`${d.name} · ${d.hostapi}${d.recommended?' · empfohlen':''}${d.available===false?' · '+(d.reason||'nicht nutzbar'):''}`,disabled:d.available===false}));
 if(typeof settings.microphone==='number'&&selected===microphoneValue(settings.microphone)){const old=microphoneDevices.find(d=>d.index===settings.microphone);choices.push({value:selected,label:old?`${old.name} · bisherige Auswahl (wird geprüft)`:'Bisherige Mikrofon-Auswahl · Liste neu laden'});}
 if(selected&&!choices.some(x=>x.value===selected)){let previous;try{previous=JSON.parse(selected);}catch{}choices.push({value:selected,label:previous?`${previous.name} · ${previous.hostapi} · gespeichert`:'Bisherige Mikrofon-Auswahl · wird geprüft'});}
 $('j-device').innerHTML='<option value="">Windows-Standard (gemeinsam mit anderen Programmen)</option>'+choices.map(d=>`<option value="${esc(d.value)}" ${d.disabled?'disabled':''}>${esc(d.label)}</option>`).join('');$('j-device').value=selected;
}
function selectedMicrophone(){const value=$('j-device').value;return !value?null:value.startsWith('legacy:')?Number(value.slice(7)):JSON.parse(value);}
function fillSettings(){
 for(const [id,key] of Object.entries({'j-greeting':'greeting','j-address':'address','j-rate':'speechRate','j-chat-mode':'chatMode','j-chat-length':'chatMaxLength','j-chat-cooldown':'chatCooldown','j-model':'aiModel','j-port':'aiPort'}))$(id).value=settings[key]??'';
 for(const [id,key] of Object.entries({'j-gaming':'gamingMode','j-speech':'voiceEnabled','j-mic':'microphoneEnabled','j-wake':'wakeWord','j-headphones':'headphones','j-chat':'chatEnabled','j-learn':'learn','j-ai':'localAi'}))$(id).checked=!!settings[key];
 for(const key of ['enabled','gifts','follows','likes','subscriptions'])$('j-events-'+key).checked=settings.events?.[key]!==false;for(const key of ['likeThreshold','giftMinimum','cooldown'])$('j-events-'+key).value=settings.events?.[key]??{likeThreshold:1000,giftMinimum:0,cooldown:8}[key];
 $('j-gift-announcement').value=settings.events?.giftAnnouncement||'gift';for(const key of ['follow','like','gift','coins','subscription'])$('j-template-'+key).value=settings.events?.templates?.[key]||'';$('j-chat-source').value=settings.chatSource||'window';$('j-chat-template').value=settings.chatTemplate||'{username} sagt: {message}';
 $('j-allowlist').value=(settings.chatAllowlist||[]).join('\n');$('j-platforms').innerHTML=['twitch','youtube','tiktok','cng'].map(p=>`<label class="suite-check"><input type="checkbox" value="${p}" ${settings.chatPlatforms?.includes(p)?'checked':''}> ${p}</label>`).join('');
 $('j-fan-alert').checked=settings.fanAlerts?.enabled!==false;for(const k of ['threshold','hysteresis','cooldown'])$('j-fan-'+k).value=settings.fanAlerts?.[k]??{threshold:80,hysteresis:5,cooldown:90}[k];
 $('j-runtime').textContent=settings.voiceRuntime||'Mitgeliefertes Sprachpaket';renderMicrophones();renderScenes();
}
function renderScenes(){const labels={pause:'„Jarvis Pause“',spiel:'„Jarvis Spiel / Weiter“',start:'„Jarvis Start“',ende:'„Jarvis Ende“'};$('j-scenes').innerHTML=Object.entries(labels).map(([key,label])=>{const current=settings.sceneAliases?.[key]||'';const all=[...new Set([...sceneNames,...(current?[current]:[])])];return `<label>${label}<select data-scene="${key}"><option value="">Noch nicht zugeordnet</option>${all.map(n=>`<option ${n===current?'selected':''} value="${esc(n)}">${esc(n)}</option>`).join('')}</select></label>`;}).join('');}
function renderCommands(){
 const examples=(Array.isArray(state?.jarvis?.commandExamples)&&state.jarvis.commandExamples.length?state.jarvis.commandExamples:fallbackCommandExamples).map(item=>typeof item==='string'?{phrase:item}:item).filter(item=>item&&typeof item.phrase==='string').map(item=>({...item,category:item.category||'Grundbefehle'})),signature=JSON.stringify(examples),category=$('j-command-category');
 if(signature!==commandExamplesSignature){const selected=category.value;commandExamplesSignature=signature;commandFilterSignature='';commandRenderSignature='';category.innerHTML='<option value="">Alle Bereiche</option>'+[...new Set(examples.map(item=>item.category))].map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');category.value=[...category.options].some(option=>option.value===selected)?selected:'';}
 const normalize=text=>String(text).toLocaleLowerCase('de-DE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss'),query=normalize($('j-command-search').value).trim().split(/\s+/).filter(Boolean),filterSignature=JSON.stringify([query,category.value]);if(filterSignature!==commandFilterSignature){commandPage=0;commandFilterSignature=filterSignature;}const renderSignature=JSON.stringify([filterSignature,commandPage]);if(renderSignature===commandRenderSignature)return;
 const filtered=examples.filter(item=>(!category.value||item.category===category.value)&&query.every(word=>normalize(`${item.phrase} ${item.description||''} ${item.category}`).includes(word))),pageCount=Math.max(1,Math.ceil(filtered.length/40));commandPage=Math.min(commandPage,pageCount-1);commandRenderSignature=JSON.stringify([filterSignature,commandPage]);const first=commandPage*40,last=Math.min(first+40,filtered.length),groups=new Map();for(const item of filtered.slice(first,last)){if(!groups.has(item.category))groups.set(item.category,[]);groups.get(item.category).push(item);}
 const markup=list=>list.map(item=>`<button type="button" data-command-example="${esc(item.phrase)}" data-command-template="${item.template===true}" aria-label="${esc(item.phrase)} – in die Eingabe übernehmen"><strong>${esc(item.phrase)}</strong><small>${esc(item.description||'Verfügbarer Jarvis-Befehl')}</small><span class="jarvis-command-use">${item.template?'Vorlage übernehmen · Platzhalter ersetzen ↑':'In Eingabe übernehmen ↑'}</span></button>`).join('');$('j-command-examples').innerHTML=[...groups].map(([name,items])=>`<section class="jarvis-command-group" data-command-category="${esc(name)}"><h5>${esc(name)} <span>${items.length}</span></h5><div class="jarvis-command-examples">${markup(items)}</div></section>`).join('')||'<p class="suite-empty">Keine passenden Befehle. Suche kürzen oder „Alle anzeigen“ wählen.</p>';
 textOnly($('j-command-count'),`${filtered.length} von ${examples.length} Befehlen gefunden · ${category.value||'Alle Bereiche'}`);textOnly($('j-command-page'),filtered.length?`Anzeige ${first+1}–${last} · Seite ${commandPage+1} von ${pageCount}`:'Keine Treffer');$('j-command-previous').disabled=commandPage===0;$('j-command-next').disabled=commandPage+1>=pageCount;$('j-command-examples').scrollTop=0;
}
async function command(text){if(!text?.trim()||commandPending)return;const placeholders=text.match(/<[A-Za-zÄÖÜäöüß][^<>]{0,79}>/g);if(placeholders){const message=`Ersetze zuerst ${[...new Set(placeholders)].join(', ')} durch deine Angabe. Danach „Ausführen“ drücken.`;textOnly($('j-command-result'),message);$('j-command-result').classList.add('is-error');$('j-command').focus();return {ok:false,kind:'input-required',text:message};}commandPending=true;$('j-execute').disabled=true;$('j-command-form').setAttribute('aria-busy','true');$('j-command-result').classList.remove('is-error');textOnly($('j-command-result'),'Befehl wird ausgeführt …');try{const result=await api('command',text)||{ok:false,text:'Jarvis hat keine Antwort geliefert. Bitte versuche den Befehl erneut.'};textOnly($('j-command-result'),(result.text||(result.ok?'Befehl ausgeführt.':'Der Befehl konnte nicht ausgeführt werden.'))+(result.ok===false&&['unrecognized','clarification'].includes(result.kind)?' Unter „Alle Jarvis-Befehle“ kannst du nach dem Bereich suchen und eine passende Formulierung übernehmen.':''));$('j-command-result').classList.toggle('is-error',result.ok===false);if(!result.ok)toast(result.text);else{clearTimeout(toastTimer);if($('suite-toast'))$('suite-toast').hidden=true;}return result;}catch(error){textOnly($('j-command-result'),String(error.message).replace(/^Error invoking remote method [^:]+: Error: /,''));$('j-command-result').classList.add('is-error');throw error;}finally{commandPending=false;$('j-execute').disabled=false;$('j-command-form').removeAttribute('aria-busy');}}
$('j-command-form').addEventListener('submit',run(async()=>{const text=$('j-command').value;const result=await command(text);if(result?.ok&&$('j-command').value===text)$('j-command').value='';}));
$('view-jarvis').addEventListener('click',e=>{const button=e.target.closest('[data-command-example]');if(!button)return;const input=$('j-command');input.value=button.dataset.commandExample;$('j-command-result').classList.remove('is-error');textOnly($('j-command-result'),button.dataset.commandTemplate==='true'?'Vorlage übernommen. Ersetze die Platzhalter in <…>, dann drücke „Ausführen“.':'Befehl übernommen. Drücke „Ausführen“ oder die Eingabetaste.');input.focus({preventScroll:true});const placeholder=input.value.match(/<[^<>]+>/);if(placeholder)input.setSelectionRange(placeholder.index,placeholder.index+placeholder[0].length);$('j-command-form').scrollIntoView({block:'nearest'});});
$('j-command-search').addEventListener('input',renderCommands);$('j-command-category').addEventListener('change',renderCommands);click('j-command-reset',()=>{$('j-command-search').value='';$('j-command-category').value='';commandPage=0;renderCommands();});
click('j-command-previous',()=>{if(commandPage>0){commandPage--;renderCommands();}});click('j-command-next',()=>{commandPage++;renderCommands();});
document.querySelectorAll('[data-jarvis]').forEach(b=>b.addEventListener('click',run(()=>command(b.dataset.jarvis))));
function importStatus(s){const c=s.counts||{};$('j-import-state').textContent=s.error?'Übernahme fehlgeschlagen: '+s.error:s.pending?'Vorbereitet. Batto 3-in-1 neu starten, um die Einstellungen zu übernehmen.':s.ok?`Übernommen: ${c.broadcasts||c.legacyBroadcasts||0} Auto-Broadcasts, ${c.commands||0} Befehle, ${c.events||0} Ereignisse. Sicherung der vorherigen Suite-Einstellungen vorhanden.`:'Beim ersten Start wird nach dem installierten Original gesucht. Ein Einstellungs-Export lässt sich auch unter Einstellungen laden.';}
click('j-import-obs',async()=>{importStatus(await api('import-obs-settings'));toast('Übernahme vorbereitet. Bitte Batto 3-in-1 neu starten.');});
api('import-status',undefined,true).then(importStatus).catch(()=>{});
function showJarvisSettings(open){$('view-jarvis').classList.toggle('settings-open',open);$('j-settings-toggle').setAttribute('aria-expanded',String(open));$('j-settings-toggle').textContent=open?'Zurück zu Jarvis':'Jarvis-Einstellungen';}
click('j-settings-toggle',()=>showJarvisSettings(!$('view-jarvis').classList.contains('settings-open')));
click('j-show-commands',()=>{showJarvisSettings(false);renderCommands();document.querySelector('.jarvis-command-help').scrollIntoView({block:'start'});$('j-command-search').focus({preventScroll:true});});
click('j-tikfinity',()=>api('control',{action:'tikfinity'}));click('j-tikfinity-connect',()=>api('control',{action:'connect',target:'tikfinity',op:'on'}));
click('j-save-events',()=>{const events={};for(const key of ['enabled','gifts','follows','likes','subscriptions'])events[key]=$('j-events-'+key).checked;for(const key of ['likeThreshold','giftMinimum','cooldown'])events[key]=Number($('j-events-'+key).value);events.giftAnnouncement=$('j-gift-announcement').value;events.templates=Object.fromEntries(['follow','like','gift','coins','subscription'].map(key=>[key,$('j-template-'+key).value]));return saveSettings({events});});
click('j-default-templates',()=>{for(const [key,text]of Object.entries(state?.jarvis?.eventDefaults?.templates||{}))$('j-template-'+key).value=text;settingsDirty=true;toast('Standardtexte eingesetzt. Zum Übernehmen Ansagen speichern.');});
$('view-jarvis').addEventListener('click',e=>{const button=e.target.closest('[data-preview-template]');if(!button)return;run(async()=>{const key=button.dataset.previewTemplate,result=await api('preview-event',{type:key,template:$('j-template-'+key).value});$('j-template-preview').textContent=result.text;})(e);});
click('j-reset-likes',async()=>{await api('reset-likes');toast('Like-Zähler zurückgesetzt.');});
click('j-test-mic',async()=>{const microphone=selectedMicrophone();await api('stop');await saveSettings({microphone});const result=await api('listen');if(result?.ok===false)toast(result.text);return result;});
click('j-listen',()=>api('listen'));click('j-stop',()=>api('stop'));click('j-devices',()=>api('devices'));
click('j-save-voice',()=>saveSettings({address:$('j-address').value,greeting:$('j-greeting').value,voiceEnabled:$('j-speech').checked,microphoneEnabled:$('j-mic').checked,wakeWord:$('j-wake').checked,headphones:$('j-headphones').checked,speechRate:Number($('j-rate').value),microphone:selectedMicrophone()}));
click('j-folder',async()=>{const s=await api('voice-folder');if(s){settings=s;fillSettings();}});
click('j-save-fan-alert',()=>saveSettings({fanAlerts:{enabled:$('j-fan-alert').checked,threshold:Number($('j-fan-threshold').value),hysteresis:Number($('j-fan-hysteresis').value),cooldown:Number($('j-fan-cooldown').value)}}));
click('j-save-chat',()=>saveSettings({chatEnabled:$('j-chat').checked,chatMode:$('j-chat-mode').value,chatSource:$('j-chat-source').value,chatTemplate:$('j-chat-template').value,chatPlatforms:[...$('j-platforms').querySelectorAll('input:checked')].map(e=>e.value),chatAllowlist:$('j-allowlist').value.split(/\s+/).filter(Boolean),chatMaxLength:Number($('j-chat-length').value),chatCooldown:Number($('j-chat-cooldown').value)}));
click('j-refresh-scenes',async()=>{sceneNames=await api('scenes');renderScenes();if(!sceneNames.length)toast('Der eigene Sender startet noch. Bitte erneut laden.');});
click('j-save-scenes',()=>saveSettings({sceneAliases:Object.fromEntries([...$('j-scenes').querySelectorAll('select')].map(e=>[e.dataset.scene,e.value]))}));
$('j-learn').addEventListener('change',run(()=>saveSettings({learn:$('j-learn').checked})));
click('j-forget',async()=>{await api('forget-memory');toast('Gespeicherte Befehle gelöscht.');});
click('j-save-ai',()=>saveSettings({localAi:$('j-ai').checked,gamingMode:$('j-gaming').checked,aiModel:$('j-model').value,aiPort:Number($('j-port').value)}));click('j-plugin',()=>api('plugin'));
function renderSensors(){if(!visibleView('sensors'))return;const all=sensors(),q=$('s-search').value.toLowerCase(),showHidden=$('s-show-hidden').checked;$('s-count').textContent=`${all.filter(s=>s.fresh).length} aktuelle Messwerte · ${all.length} erkannt`;
 const visible=all.filter(s=>(showHidden||settings.sensorRules?.[s.id]?.visible!==false)&&`${s.name} ${s.device} ${s.unit} ${settings.sensorRules?.[s.id]?.alias||''}`.toLowerCase().includes(q));
 const structure=JSON.stringify(visible.map(s=>[s.id,s.name,s.device,s.unit,settings.sensorRules?.[s.id]]));if(structure!==sensorStructure){sensorStructure=structure;$('s-list').innerHTML=visible.map(s=>{const r=settings.sensorRules?.[s.id]||{};return `<button class="suite-sensor ${s.id===selectedSensor?'selected':''} ${!s.fresh?'stale':''} ${r.visible===false?'hidden-rule':''}" data-sensor="${esc(s.id)}"><span>${esc(r.alias||s.name)}<small>${esc(s.device)} · ${esc(s.name)}${r.alert?' · Meldung aktiv':''}${!s.fresh?' · Quelle veraltet':''}</small></span><strong>${esc(fmt(s))}</strong></button>`;}).join('')||'<div class="suite-empty">Keine passenden Messwerte.<br>Weitere Sensoren über ein laufendes Protokoll oder HWiNFO verbinden.</div>';}
 const readings=new Map(visible.map(s=>[s.id,s]));for(const row of $('s-list').querySelectorAll('[data-sensor]')){const item=readings.get(row.dataset.sensor),rule=settings.sensorRules?.[item.id]||{};row.classList.toggle('selected',item.id===selectedSensor);row.classList.toggle('stale',!item.fresh);textOnly(row.querySelector('strong'),fmt(item));textOnly(row.querySelector('small'),`${item.device} · ${item.name}${rule.alert?' · Meldung aktiv':''}${!item.fresh?' · Quelle veraltet':''}`);}
 const s=all.find(s=>s.id===selectedSensor);if(s)$('s-reading').textContent=`${fmt(s)} · ${s.fresh?'Aktuell':'Nicht verfügbar'} · ${s.unit}`;
 const sources=state?.fan?.sources;$('s-sources').textContent=state?.fanError?state.fanError:[sources?.icue,sources?.nvidia,sources?.hwinfo,...(sources?.csv||[])].filter(Boolean).join('\n');
 const paths=state?.fan?.csvPaths||[];const signature=JSON.stringify(paths);if($('s-csv-list').dataset.paths!==signature){$('s-csv-list').dataset.paths=signature;$('s-csv-list').innerHTML=paths.map((p,i)=>`<div class="suite-csv-item"><span>${esc(p)}</span><button data-remove-csv="${i}">Trennen</button></div>`).join('');}
}
function selectSensor(id){selectedSensor=id;const s=sensors().find(s=>s.id===id);if(!s)return;const r={alias:'',visible:true,readable:true,alert:false,mode:'above',threshold:s.unit==='°C'?80:s.value||0,delta:s.unit==='V'?.2:5,hysteresis:s.unit==='V'?.05:2,cooldown:60,...settings.sensorRules?.[id]};$('s-rule').hidden=false;$('s-name').textContent=s.name;for(const k of ['alias','mode','threshold','delta','hysteresis','cooldown'])$('s-'+k).value=r[k];for(const k of ['visible','readable','alert'])$('s-'+k).checked=r[k];renderSensors();}
$('s-list').addEventListener('click',e=>{const b=e.target.closest('[data-sensor]');if(b)selectSensor(b.dataset.sensor);});$('s-search').addEventListener('input',renderSensors);$('s-show-hidden').addEventListener('change',renderSensors);
click('s-save',async()=>{if(!selectedSensor)return;const r={};for(const k of ['alias','mode'])r[k]=$('s-'+k).value;for(const k of ['threshold','delta','hysteresis','cooldown'])r[k]=Number($('s-'+k).value);for(const k of ['visible','readable','alert'])r[k]=$('s-'+k).checked;await saveSettings({sensorRules:{...settings.sensorRules,[selectedSensor]:r}});renderSensors();});
click('s-speak',()=>{const s=sensors().find(s=>s.id===selectedSensor);if(s)return command(settings.sensorRules?.[s.id]?.alias||s.name);});
click('f-sources',()=>setView('sensors'));click('s-csv',()=>api('csv'));click('s-profile',()=>api('profile'));
$('s-csv-list').addEventListener('click',run(async e=>{const b=e.target.closest('[data-remove-csv]');if(b)await api('fan-config',{command:'csv',value:{paths:state.fan.csvPaths.filter((_,i)=>i!==Number(b.dataset.removeCsv))}});}));
function resizeStage(){if(!visibleView('fans'))return;const w=$('f-wrap').clientWidth;$('f-stage').style.transform=`scale(${w/1920})`;}
new ResizeObserver(resizeStage).observe($('f-wrap'));
function renderStage(){if(!scene||!visibleView('fans'))return;const el=$('f-stage');
 if(el.dataset.background!==scene.background){el.dataset.background=scene.background;el.style.backgroundImage=scene.background?`url('./assets/${scene.background==='stream-startet.jpg'?'stream-startet.jpg':'bin-gleich-zurueck.jpg'}')`:'none';}$('f-background').value=scene.background;
 const structure=JSON.stringify(scene.tiles.map(({speedPercent,...tile})=>tile));
 if(!drag&&structure!==stageStructure){stageStructure=structure;el.innerHTML=scene.tiles.map(t=>`<div class="suite-fan" data-fan="${esc(t.id)}" aria-hidden="${!t.visible}" style="left:${t.x}px;top:${t.y}px;width:${t.size}px"><div class="suite-fan-picture"><img src="./assets/fan.png" alt=""><span class="temp" style="font-size:${t.size*.115}px"></span></div><div class="caption"><div class="fan-name">${esc(t.name)}</div><div class="fan-rpm"></div><div class="fan-source"></div></div></div>`).join('');}
 if(!drag){const readings=new Map(sensors().map(s=>[s.id,s])),liveTiles=new Map((state?.fan?.state?.scene?.tiles||[]).map(t=>[t.id,t])),tiles=new Map(scene.tiles.map(t=>[t.id,t]));for(const node of el.children){const t=tiles.get(node.dataset.fan);if(!t)continue;const temp=readings.get(t.temperatureSensorId),rpm=readings.get(t.rpmSensorId),percent=liveTiles.get(t.id)?.speedPercent,center=t.centerMode==='temperature'?temp:t.centerMode==='rpm'?rpm:percent;
  node.classList.toggle('selected',t.id===selectedFan);textOnly(node.querySelector('.temp'),center?.fresh?fmt(center):t.centerMode==='temperature'?'— °C':t.centerMode==='rpm'?'—':'— %');textOnly(node.querySelector('.fan-rpm'),fmt(rpm));textOnly(node.querySelector('.fan-source'),percent?.fresh?(percent.basis==='rpm-reference'?'% der Max.-Drehzahl':'Live · gemessene %'):rpm?.fresh?(t.centerMode==='rpm'?'Live · U/min':'Live · % nicht zugeordnet'):t.fromProfile?'Profil · warte auf Live-Werte':'Quelle fehlt / veraltet');}}
 textOnly($('f-state'),state?.fanError||`${scene.tiles.length} Lüfterkacheln · ${scene.tiles.filter(t=>sensors().some(s=>s.id===t.rpmSensorId&&s.fresh)).length} mit Live-Drehzahl · fehlende Live-Werte bleiben —`);resizeStage();}
function selectFan(id){selectedFan=id;const t=fan();$('f-edit').hidden=!t;if(!t)return;for(const k of ['name','x','y','size'])$('f-'+k).value=t[k];$('f-visible').checked=t.visible;$('f-temp').innerHTML=optionList(sensors().filter(s=>s.unit==='°C'),t.temperatureSensorId);$('f-temp').value=t.temperatureSensorId;$('f-rpm').innerHTML=optionList(sensors().filter(s=>s.isLinkFan&&s.unit==='RPM'),t.rpmSensorId);$('f-rpm').value=t.rpmSensorId;$('f-percent').innerHTML=optionList(sensors().filter(s=>s.isLinkFan&&s.unit==='%'),t.percentSensorId);$('f-percent').value=t.percentSensorId||'';$('f-max-rpm').value=t.maxRpm||'';$('f-center').value=t.centerMode||'percent';$('f-announce').checked=t.announce!==false;renderStage();}
async function saveStage(){if(!scene)return;fanBusy=true;try{await api('fan-config',{command:'stage',value:scene});}finally{fanBusy=false;}}
$('f-stage').addEventListener('pointerdown',e=>{const el=e.target.closest('[data-fan]');if(!el)return;e.preventDefault();selectFan(el.dataset.fan);const t=fan();drag={id:t.id,x:e.clientX,y:e.clientY,originalX:t.x,originalY:t.y,pointer:e.pointerId};$('f-stage').setPointerCapture(e.pointerId);});
$('f-stage').addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;const t=fan(),scale=$('f-wrap').clientWidth/1920;t.x=Math.max(0,Math.min(1920-t.size,Math.round(drag.originalX+(e.clientX-drag.x)/scale)));t.y=Math.max(0,Math.min(1080-t.size-64,Math.round(drag.originalY+(e.clientY-drag.y)/scale)));const el=[...$('f-stage').children].find(n=>n.dataset.fan===t.id);if(el){el.style.left=t.x+'px';el.style.top=t.y+'px';}$('f-x').value=t.x;$('f-y').value=t.y;});
for(const event of ['pointerup','pointercancel'])$('f-stage').addEventListener(event,run(async()=>{if(!drag)return;drag=null;renderStage();await saveStage();}));
$('f-background').addEventListener('change',run(async()=>{if(scene){scene.background=$('f-background').value;renderStage();await saveStage();}}));
click('f-align',async()=>{if(!scene)return;const size=scene.tiles.length>24?150:scene.tiles.length>18?175:210;const columns=scene.tiles.length>24?8:6;scene.tiles.forEach((t,i)=>Object.assign(t,{size,x:40+i%columns*(1840/columns),y:25+Math.floor(i/columns)*(size+70)}));renderStage();await saveStage();toast('Lüfter gleichmäßig ausgerichtet.');});
click('f-add',async()=>{if(!scene)return;if(scene.tiles.length>=32){toast('Bis zu 32 Lüfter pro Layout.');return;}const t={id:crypto.randomUUID().replaceAll('-',''),name:'Mein Lüfter',x:150,y:150,size:210,visible:true,rpmSensorId:'',temperatureSensorId:'',percentSensorId:'',maxRpm:0,centerMode:'percent',announce:true,fromProfile:false};scene.tiles.push(t);selectFan(t.id);await saveStage();});
click('f-save',async()=>{const t=fan();if(!t)return;Object.assign(t,{name:$('f-name').value,x:Number($('f-x').value),y:Number($('f-y').value),size:Number($('f-size').value),visible:$('f-visible').checked,rpmSensorId:$('f-rpm').value,temperatureSensorId:$('f-temp').value,percentSensorId:$('f-percent').value,maxRpm:Number($('f-max-rpm').value),centerMode:$('f-center').value,announce:$('f-announce').checked});await saveStage();toast('Lüfter gespeichert.');});
click('f-delete',async()=>{if(!fan())return;scene.tiles=scene.tiles.filter(t=>t.id!==selectedFan);selectedFan='';$('f-edit').hidden=true;renderStage();await saveStage();});
for(const [id,cmd] of Object.entries({'f-copy':'copy-obs','f-preview':'open-obs','f-import':'import-layout','f-export':'export-layout'}))click(id,async()=>{await api(cmd);if(cmd==='copy-obs')toast('OBS-Adresse kopiert. Browserquelle auf 1920 × 1080 einstellen.');});
function curveValidation(){
 if(!curve)return 'Bitte eine Kurve auswählen.';
 if(!curve.name.trim()||curve.name.length>100)return 'Bitte einen Namen mit 1 bis 100 Zeichen eingeben.';
 if(!curve.sensorLabel.trim()||curve.sensorLabel.length>200)return 'Bitte einen Temperaturbezug mit 1 bis 200 Zeichen eingeben.';
 if(curve.points.length<2||curve.points.length>20)return 'Eine Kurve braucht 2 bis 20 Punkte.';
 if(curve.points.some(p=>!Number.isFinite(p.temperature)||p.temperature<0||p.temperature>120||!Number.isFinite(p.duty)||p.duty<0||p.duty>100))return 'Jeden Punkt ausfüllen: Temperatur 0–120 °C, Lüfterleistung 0–100 %.';
 if(new Set(curve.points.map(p=>p.temperature)).size!==curve.points.length)return 'Jede Temperatur darf nur einmal vorkommen.';
 return '';
}
function curveStatus(){
 const error=curveValidation();$('f-curve-validation').textContent=error;$('f-curve-validation').hidden=!error;
 $('f-curve-note').textContent=(curveDirty?'Ungespeicherte Änderungen · ':'')+`${curve?.points.length||0} von 20 Punkten. `+(curve?.isCustom?'Eigener Entwurf.':'Importierte Kurve. Speichern erstellt einen eigenen Entwurf.');
 for(const field of $('f-points').querySelectorAll('input')){const value=curve?.points[Number(field.dataset.point)]?.[field.dataset.field],max=field.dataset.field==='temperature'?120:100;field.setAttribute('aria-invalid',String(!Number.isFinite(value)||value<0||value>max||(field.dataset.field==='temperature'&&curve.points.filter(p=>p.temperature===value).length>1)));}
 for(const field of document.querySelectorAll('.suite-curves input,.suite-curves select,.suite-curves button'))field.disabled=curveSaving;
 $('f-add-point').disabled=curveSaving||curve?.points.length>=20;
 for(const button of $('f-points').querySelectorAll('button'))button.disabled=curveSaving||curve.points.length<=2;
 $('f-save-curve').textContent=curveSaving?'Wird gespeichert …':'Entwurf speichern';
 $('f-curve-editor').setAttribute('aria-busy',String(curveSaving));
}
function renderCurve(){
 if(!curve)return;$('f-curve-name').value=curve.name;$('f-curve-sensor').value=curve.sensorLabel;
 $('f-points').innerHTML=curve.points.map((p,i)=>`<div class="suite-point"><input aria-label="Temperatur Punkt ${i+1}" data-point="${i}" data-field="temperature" type="number" inputmode="decimal" min="0" max="120" step="any" value="${esc(p.temperature??'')}"><input aria-label="Leistung Punkt ${i+1}" data-point="${i}" data-field="duty" type="number" inputmode="decimal" min="0" max="100" step="any" value="${esc(p.duty??'')}"><button type="button" data-delete-point="${i}" aria-label="Punkt ${i+1} entfernen" title="Punkt ${i+1} entfernen">×</button></div>`).join('');curveStatus();drawCurve();
}
function drawCurve(){const svg=$('f-graph'),points=(curve?.points||[]).filter(p=>Number.isFinite(p.temperature)&&p.temperature>=0&&p.temperature<=120&&Number.isFinite(p.duty)&&p.duty>=0&&p.duty<=100).slice().sort((a,b)=>a.temperature-b.temperature);svg.innerHTML=[0,25,50,75,100].map(v=>`<line x1="45" y1="${215-v*1.9}" x2="570" y2="${215-v*1.9}" stroke="#284259"/><text x="8" y="${220-v*1.9}" fill="#93b9d5" font-size="12">${v}%</text>`).join('')+[0,30,60,90,120].map(v=>`<text x="${39+v*4.35}" y="239" fill="#93b9d5" font-size="12">${v}°</text>`).join('')+`<polyline points="${points.map(p=>`${45+p.temperature*4.35},${215-p.duty*1.9}`).join(' ')}" fill="none" stroke="#46dcff" stroke-width="3"/>`+points.map(p=>`<circle cx="${45+p.temperature*4.35}" cy="${215-p.duty*1.9}" r="4" fill="#b6f4ff"/>`).join('');}
function canReplaceCurve(){return !curveSaving&&(!curveDirty||window.confirm('Ungespeicherte Änderungen an dieser Kurve verwerfen?'));}
function chooseCurve(id){
 const found=state?.fan?.curves?.find(c=>c.id===id);if(!found)return;
 if(!canReplaceCurve()){$('f-curves').value=curve?.id||'';return;}
 curve=clone(found);curveDirty=false;$('f-curves').value=id;renderCurve();
}
function syncCurves(){if(!visibleView('fans'))return;const curves=state?.fan?.curves||[],key=JSON.stringify(curves.map(c=>[c.id,c.name]));if(curvesKey!==key){curvesKey=key;$('f-curves').innerHTML='<option value="">Eigene Kurve erstellen …</option>'+curves.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}${c.isCustom?' · Eigene':''}</option>`).join('');$('f-curves').value=curve?.id||'';}
 const selected=state?.fan?.state?.selectedCurveId;if(selected&&selected!==lastSelection){lastSelection=selected;const found=curves.find(c=>c.id===selected);if(found&&!curveDirty&&!curveSaving){curve=clone(found);$('f-curves').value=selected;renderCurve();}}
 const rows=state?.fan?.fans||[],signature=JSON.stringify([rows,curves.map(c=>c.id)]);if(signature!==assignmentSignature){assignmentSignature=signature;$('f-assignments').innerHTML=rows.length?'<table class="suite-table"><thead><tr><th>Lüfter im Profil</th><th>Gespeicherte Kurve</th></tr></thead><tbody>'+rows.map(f=>`<tr><td>${esc(f.name)}</td><td>${f.curveId&&curves.some(c=>c.id===f.curveId)?`<button type="button" class="suite-assigned-curve" data-assigned-curve="${esc(f.curveId)}" title="Diese gespeicherte Kurve ansehen">${esc(f.curveName)}</button>`:esc(f.curveName)}</td></tr>`).join('')+'</tbody></table>':'<p class="suite-help">Noch kein iCUE-Profil importiert. Im Bereich PC-Messwerte kannst du ein exportiertes Profil laden.</p>';}}
$('f-curves').addEventListener('change',()=>{const id=$('f-curves').value;if(id)chooseCurve(id);else newCurve();});
function newCurve(){if(!canReplaceCurve()){$('f-curves').value=curve?.id||'';return;}curve={id:'',name:'Meine Lüfterkurve',sensorLabel:'Kühlmittel-Temperatur',isCustom:true,points:[{temperature:30,duty:30},{temperature:50,duty:50},{temperature:70,duty:80},{temperature:85,duty:100}]};curveDirty=false;$('f-curves').value='';renderCurve();}
click('f-new-curve',newCurve);click('f-duplicate-curve',()=>{if(curve&&!curveSaving){curve.id='';curve.name=curve.name.slice(0,92)+' – Kopie';curve.isCustom=true;curveDirty=true;$('f-curves').value='';renderCurve();}else if(!curve)newCurve();});
for(const [id,key]of [['f-curve-name','name'],['f-curve-sensor','sensorLabel']])$(id).addEventListener('input',()=>{if(curve){curve[key]=$(id).value;curveDirty=true;curveStatus();}});
$('f-points').addEventListener('input',e=>{if(!e.target.dataset.field||!curve||curveSaving)return;curve.points[Number(e.target.dataset.point)][e.target.dataset.field]=e.target.value===''?null:e.target.valueAsNumber;curveDirty=true;curveStatus();drawCurve();});
$('f-points').addEventListener('click',e=>{const b=e.target.closest('[data-delete-point]');if(b&&curve&&!curveSaving&&curve.points.length>2){curve.points.splice(Number(b.dataset.deletePoint),1);curveDirty=true;renderCurve();}});
click('f-add-point',()=>{if(!curve)newCurve();if(!curve||curveSaving||curve.points.length>=20)return;const sorted=curve.points.filter(p=>Number.isFinite(p.temperature)).sort((a,b)=>a.temperature-b.temperature),last=sorted.at(-1);let temperature=last?Math.min(120,last.temperature+5):30;if(sorted.some(p=>p.temperature===temperature)){const gap=sorted.findIndex((p,i)=>i&&p.temperature-sorted[i-1].temperature>=1);temperature=gap>0?(sorted[gap-1].temperature+sorted[gap].temperature)/2:(sorted[0]?.temperature>0?sorted[0].temperature/2:null);}curve.points.push({temperature,duty:last?.duty??30});curveDirty=true;renderCurve();const field=$('f-points').lastElementChild?.querySelector('input');field?.focus({preventScroll:true});field?.scrollIntoView({block:'nearest'});});
function curvePayload(){const error=curveValidation();if(error){curveStatus();toast(error);$('f-curve-validation').scrollIntoView({block:'nearest'});return null;}const value=clone(curve);value.name=value.name.trim();value.sensorLabel=value.sensorLabel.trim();value.points.sort((a,b)=>a.temperature-b.temperature);return value;}
click('f-save-curve',async()=>{if(curveSaving)return;const value=curvePayload();if(!value)return;if(!value.isCustom)value.id='';curveSaving=true;curveStatus();try{const result=await api('fan-config',{command:'curve',value});const savedId=result?.curveId||value.id;if(!savedId){const message='Die gespeicherte Kurve konnte nicht bestätigt werden. Bitte die Kurvenliste neu laden.';toast(message);throw Error(message);}curve={...value,id:savedId,isCustom:true};curveDirty=false;lastSelection=savedId;if(state?.fan){state.fan.curves=[...(state.fan.curves||[]).filter(c=>c.id!==savedId),clone(curve)];if(state.fan.state)state.fan.state.selectedCurveId=savedId;}syncCurves();$('f-curves').value=savedId;renderCurve();toast('Kurvenentwurf gespeichert. Für die Lüfter in iCUE übernehmen.');}finally{curveSaving=false;curveStatus();}});
click('f-export-curve',async()=>{const value=curvePayload();if(value){const result=await api('export-curve',{curve:value});if(result?.ok)toast('Die angezeigte Kurve wurde exportiert.');}});
click('f-copy-curve',async()=>{const value=curvePayload();if(value){await api('copy-curve',{curve:value});toast('Wertetabelle kopiert. In iCUE die Punkte einer eigenen Kühlkurve entsprechend eintragen.');}});
click('f-open-icue',()=>api('open-icue'));
$('f-assignments').addEventListener('click',e=>{const button=e.target.closest('[data-assigned-curve]');if(button){chooseCurve(button.dataset.assignedCurve);$('f-curve-editor').scrollIntoView({block:'start'});}});
function renderActive(){if(!state||document.hidden)return;if(visibleView('jarvis')){textOnly($('j-voice-state'),state.voice.status);textOnly($('j-listening-mode'),settings.microphoneEnabled?(settings.wakeWord?'Dauerhaftes Zuhören ist eingeschaltet. Beginne deinen Befehl mit „Jarvis“.':'Dauerhaftes Zuhören ist eingeschaltet. Sprich deinen Befehl direkt.'):'Mikrofon nur nach Tastendruck: „Jetzt zuhören“ oder die Jarvis-Taste auf dem Stream Deck drücken. Dauerhaftes Zuhören lässt sich in den Jarvis-Einstellungen einschalten.');renderCommands();textOnly($('j-memory'),`${state.jarvis.memory.length} erfolgreiche Befehle gemerkt · ${state.jarvis.knownSensors} Sensoren automatisch erkannt. Batto-Befehle sind bereits eingebaut. Das Gedächtnis speichert den Verlauf; Szenen legst du unter Dual Stream fest.`);renderLog();}renderSensors();renderStage();syncCurves();}
document.addEventListener('batto:view',renderActive);document.addEventListener('visibilitychange',renderActive);
function update(next){state=next;settings=next.jarvis.settings;const signature=JSON.stringify(settings);if(!initialized){initialized=true;fillSettings();newCurve();}else if(!settingsDirty&&signature!==settingsSignature)fillSettings();settingsSignature=signature;if(!drag&&!fanBusy&&next.fan?.state?.scene)scene=clone(next.fan.state.scene);renderActive();}
window.batto.onSuiteState(update);window.batto.onJarvisMessage(m=>{if(state){if(!m.id||!state.jarvis.history.some(entry=>entry.id===m.id))state.jarvis.history.push(m);state.jarvis.history=state.jarvis.history.slice(-100);renderLog();}});window.batto.onJarvisVoice(e=>{if(['state','ready','notice','error','microphone-ready'].includes(e.type))$('j-voice-state').textContent=e.text||state?.voice?.status||'';if(e.type==='state')$('j-orb').classList.toggle('speaking',e.state==='speaking');if(e.type==='devices'){microphoneDevices=e.items||[];renderMicrophones(true);}if(e.type==='microphone-selected'){$('j-device-status').textContent=e.text||'Mikrofon verbunden.';}if(e.type==='error')toast(e.text);});
async function init(){try{update(await api('state',undefined,true));}catch{setTimeout(init,1000);}}init();
})();
