'use strict';
const MODIFIERS={ctrl:'Control',control:'Control',strg:'Control',alt:'Alt',shift:'Shift',umschalt:'Shift',win:'Super',windows:'Super',super:'Super',meta:'Super',commandorcontrol:'Control'};
const KEYS={numpadenter:'NumPadEnter',mouseleft:'LButton',lbutton:'LButton',mouseright:'RButton',rbutton:'RButton',mousemiddle:'MButton',mbutton:'MButton',mouse4:'XButton1',xbutton1:'XButton1',mouse5:'XButton2',xbutton2:'XButton2',wheelup:'WheelUp',wheeldown:'WheelDown',wheelleft:'WheelLeft',wheelright:'WheelRight',escape:'Escape',esc:'Escape',enter:'Return',return:'Return',space:'Space',tab:'Tab',backspace:'Back',back:'Back',delete:'Delete',insert:'Insert',home:'Home',end:'End',pageup:'Prior',pagedown:'Next',up:'Up',down:'Down',left:'Left',right:'Right',plus:'Oemplus',minus:'OemMinus',comma:'Oemcomma',period:'OemPeriod'};
function inputError(message,field='accelerator'){const error=new Error(message);error.field=field;return error;}
function parseAccelerator(value){
 const parts=String(value||'').trim().split('+').map(x=>x.trim()).filter(Boolean),mods=new Set(),keys=[];let key='';
 for(const part of parts){const lower=part.toLowerCase();if(Object.hasOwn(MODIFIERS,lower)){mods.add(MODIFIERS[lower]);continue;}key=(Object.hasOwn(KEYS,lower)?KEYS[lower]:null)||(/^num(?:pad)?[0-9]$/i.test(part)?'NumPad'+part.slice(-1):/^F(?:[1-9]|1[0-9]|2[0-4])$/i.test(part)?part.toUpperCase():/^[a-z0-9]$/i.test(part)?part.toUpperCase():/^num(?:pad)?(add|sub|mult|div|decimal)$/i.test(part)?({add:'Add',sub:'Subtract',mult:'Multiply',div:'Divide',decimal:'Decimal'}[part.replace(/^num(?:pad)?/i,'').toLowerCase()]):'');if(!key && /^(Prior|Next|Add|Subtract|Multiply|Divide|Decimal|Oem1|Oemplus|Oemcomma|OemMinus|OemPeriod|OemQuestion|Oemtilde|OemOpenBrackets|Oem5|Oem6|Oem7|OemBackslash)$/i.test(part))key=['Prior','Next','Add','Subtract','Multiply','Divide','Decimal','Oem1','Oemplus','Oemcomma','OemMinus','OemPeriod','OemQuestion','Oemtilde','OemOpenBrackets','Oem5','Oem6','Oem7','OemBackslash'].find(x=>x.toLowerCase()===part.toLowerCase());if(!key)throw new Error('Taste nicht erkannt. Aufnahme verwenden; zusätzliche Maustasten über die Maussoftware zuordnen.');if(!keys.includes(key))keys.push(key);}
 if(!keys.length)throw inputError(mods.size?'Die Kombination enthält nur Zusatztasten. Bitte zusätzlich eine Taste oder Maustaste wählen, zum Beispiel Control+K oder Shift+RButton.':'Die Kombination ist leer. Eine Taste eingeben oder „Kombination aufnehmen“ verwenden.');
 if(keys.length>6)throw new Error('Maximal sechs Tasten oder Maustasten pro Kombination.');
 if(keys.filter(k=>k.startsWith('Wheel')).length>1)throw new Error('Nur eine Mausradrichtung pro Kombination verwenden.');
 keys.sort((a,b)=>a.localeCompare(b,'en'));key=keys[0];
 const ordered=['Control','Alt','Shift','Super'].filter(x=>mods.has(x));
 if((keys.includes('L')&&mods.has('Super'))||(keys.includes('Delete')&&mods.has('Control')&&mods.has('Alt')))throw new Error('Diese Windows-Systemkombination ist nicht registrierbar.');
 return {accelerator:[...ordered,...keys].join('+'),key,keys,modifiers:ordered,modifierMask:ordered.reduce((sum,m)=>sum+({Control:1,Alt:2,Shift:4,Super:8}[m]),0),wheel:keys.some(k=>k.startsWith('Wheel'))};
}
function normalizeHotkey(item){const parsed=parseAccelerator(item.accelerator);const triggerMode=item.triggerMode||'down',scope=item.scope||'global';if(!['global','app'].includes(scope))throw inputError('Ungültiger Geltungsbereich.','scope');if(!['down','up','repeat'].includes(triggerMode))throw inputError('Ungültiger Auslösemoment.','triggerMode');if(parsed.wheel&&triggerMode!=='down')throw inputError('Das Mausrad unterstützt einzelne Impulse, kein Halten oder Loslassen.','triggerMode');return {...item,...parsed,scope,triggerMode,passthrough:item.passthrough!==false,debounceMs:Math.min(5000,Math.max(50,Number(item.debounceMs)||300))};}
class InputHotkeys {
 constructor({register,unregister,backend,trigger,stop,onStatus=()=>{}}){Object.assign(this,{register,unregister,backend,trigger,stop,onStatus});this.bound=[];this.states=[];this.last=new Map();this.items=new Map();this.generation=0;this.capturing=false;this.captureGeneration=0;if(backend){const previousError=backend.onError;backend.onError=error=>{this.states=this.states.map(s=>s.registered||s.pending?{...s,registered:false,pending:false,error:error.message||String(error)}:s);this.onStatus({items:this.states});previousError?.(error);};}}
 run(item){if(this.capturing)return;const now=Date.now();if(now-(this.last.get(item.id)||0)<item.debounceMs)return;this.last.set(item.id,now);Promise.resolve(item.stopAll?this.stop():this.trigger(item.chainId,{source:'hotkey',ruleId:item.id,accelerator:item.accelerator})).catch(e=>this.onStatus({error:e.message,id:item.id}));}
 configure(items=[]){this.clear();const generation=++this.generation,used=new Set(),valid=[];this.states=items.filter(x=>x.enabled!==false&&x.accelerator).map(item=>{let key=item.accelerator,error='',normalized;try{normalized=normalizeHotkey(item);key=normalized.accelerator;const signature=normalized.scope+':'+key.toLowerCase();if(used.has(signature))throw new Error('Kombination im gleichen Geltungsbereich doppelt vergeben.');used.add(signature);if(!item.stopAll&&!item.chainId)throw new Error('Aktionskette fehlt.');if(this.backend){valid.push(normalized);this.items.set(item.id,normalized);}else{if(normalized.scope!=='global'||normalized.triggerMode!=='down'||normalized.keys.length!==1||normalized.key.includes('Button')||normalized.wheel)throw new Error('Die Windows-Eingabehilfe ist nicht verfügbar.');if(!this.register?.(key,()=>this.run(normalized)))throw new Error('Tastenkombination ist belegt oder ungültig.');this.bound.push(key);}}catch(e){error=e.message;}return {id:item.id,accelerator:key,scope:normalized?.scope||item.scope||'global',registered:!error&&!this.backend,pending:!error&&!!this.backend,error};});this.onStatus({items:this.states});if(this.backend&&valid.length)this.backend.configure(valid,id=>{const item=this.items.get(id);if(item)this.run(item);}).then(()=>{if(generation!==this.generation)return;this.states=this.states.map(s=>s.pending?{...s,pending:false,registered:true}:s);this.onStatus({items:this.states});}).catch(e=>{if(generation!==this.generation)return;this.states=this.states.map(s=>s.pending?{...s,pending:false,error:e.message}:s);this.onStatus({items:this.states});});return this.states;}
 async capture(){if(!this.backend)throw new Error('Windows-Eingabehilfe ist nicht verfügbar.');const generation=++this.captureGeneration;this.capturing=true;try{return await this.backend.capture();}finally{if(generation===this.captureGeneration)this.capturing=false;}}
 cancelCapture(){this.captureGeneration++;this.backend?.cancelCapture();this.capturing=false;}
 clear(){this.generation++;this.cancelCapture();for(const key of this.bound)this.unregister?.(key);this.bound=[];this.last.clear();this.items.clear();this.backend?.stop();}
}
module.exports={InputHotkeys,parseAccelerator,normalizeHotkey};
