'use strict';
const path=require('node:path'),fs=require('node:fs'),{spawn}=require('node:child_process'),readline=require('node:readline'),crypto=require('node:crypto');
class PhysicalInputBackend{
 constructor({appPid=process.pid,onError=()=>{},spawnImpl=spawn,executable}={}){Object.assign(this,{appPid,onError,spawnImpl});this.executable=executable||path.join(__dirname,'physical-input.exe').replace(/app\.asar([\\/])/,'app.asar.unpacked$1');this.pending=new Map();this.child=null;this.ready=null;this.captureGeneration=0;this.cancelStartingCapture=null;}
 start(){if(this.child)return this.ready;if(!fs.existsSync(this.executable))return Promise.reject(new Error('Windows-Eingabehilfe fehlt. Bitte den aktuellen Installer verwenden.'));const child=this.spawnImpl(this.executable,[],{windowsHide:true,stdio:['pipe','pipe','pipe']});this.child=child;let resolveReady,rejectReady;this.ready=new Promise((resolve,reject)=>{resolveReady=resolve;rejectReady=reject;});this.rejectReady=rejectReady;const timer=this.startupTimer=setTimeout(()=>{rejectReady(new Error('Windows-Eingabehilfe antwortet nicht.'));this.stop();},8000);const fail=error=>{if(this.child!==child)return;clearTimeout(timer);this.child=null;rejectReady(error);for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(error);}this.pending.clear();this.onError(error);};readline.createInterface({input:child.stdout}).on('line',line=>{if(this.child!==child)return;let p;try{p=JSON.parse(line);}catch{return;}if(p.type==='ready'){clearTimeout(timer);resolveReady();}else if(p.type==='trigger')this.onTrigger?.(p.id);else if(p.type==='error'){fail(new Error(p.error||'Windows-Eingabehilfe meldet Fehler.'));child.kill();}else if(p.id&&this.pending.has(p.id)){const task=this.pending.get(p.id);clearTimeout(task.timer);this.pending.delete(p.id);p.ok===false?task.reject(new Error(p.error)):task.resolve(p);}});child.stderr.on('data',()=>{});child.on('error',fail);child.on('exit',()=>fail(new Error('Windows-Eingabehilfe wurde beendet.')));child.stdin.on('error',error=>fail(error));return this.ready;}
 async request(type,data={},timeout=5000){const generation=this.captureGeneration;await this.start();if(type==='capture'&&generation!==this.captureGeneration)throw new Error('Aufnahme beendet.');return new Promise((resolve,reject)=>{const id=crypto.randomUUID(),timer=setTimeout(()=>{this.pending.delete(id);if(type==='capture')this.send({type:'cancelCapture'});reject(new Error(type==='capture'?'Aufnahme nach 15 Sekunden beendet.':'Eingabehilfe antwortet nicht.'));},timeout);this.pending.set(id,{resolve,reject,timer,type});this.send({type,id,...data});});}
 send(value){if(this.child?.stdin.writable)this.child.stdin.write(JSON.stringify(value)+'\n');}
 configure(items,onTrigger){this.onTrigger=onTrigger;return this.request('configure',{appPid:this.appPid,rules:items.map(({id,key,keys,modifierMask,scope,passthrough,triggerMode,debounceMs})=>({id,key,keys,modifierMask,scope,passthrough,triggerMode,debounceMs}))});}
 capture(){
  this.cancelCapture();const generation=this.captureGeneration;
  // Cancel the UI request immediately even while the native helper is starting.
  // The generation guard in request also prevents a late ready event from sending it.
  const cancelled=new Promise((_resolve,reject)=>{this.cancelStartingCapture=()=>reject(new Error('Aufnahme beendet.'));});
  return Promise.race([this.request('capture',{},15000),cancelled]).finally(()=>{if(generation===this.captureGeneration)this.cancelStartingCapture=null;});
 }
 cancelCapture(){this.captureGeneration++;this.cancelStartingCapture?.();this.cancelStartingCapture=null;this.send({type:'cancelCapture'});for(const [id,p] of this.pending)if(p.type==='capture'){clearTimeout(p.timer);p.reject(new Error('Aufnahme beendet.'));this.pending.delete(id);}}
 stop(){clearTimeout(this.startupTimer);this.rejectReady?.(new Error('Eingabehilfe wurde beendet.'));this.rejectReady=null;this.cancelCapture();const child=this.child;if(!child)return;this.send({type:'stop'});this.child=null;this.onTrigger=null;for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error('Belegung wurde geändert.'));}this.pending.clear();child.stdin.end();const timer=setTimeout(()=>child.kill(),1000);timer.unref?.();child.once('exit',()=>clearTimeout(timer));}
}
module.exports={PhysicalInputBackend};
