import {useEffect,useRef,useState} from 'react';
import {RotateCcw,Volume2,VolumeX} from 'lucide-react';
export const APPEARANCE_DEFAULTS={background:'#0b0b0a',opacity:100,accent:'#d5ae5b',border:'#51452a',text:'#f0e7d2',muted:'#b8a988',videoVisible:true,videoHeight:220,videoWidth:100,videoFit:'contain',videoSound:false};
const KEY='batto.rgb.appearance.v1';
export function cleanAppearance(input={}){const next={...APPEARANCE_DEFAULTS};for(const key of ['background','accent','border','text','muted'])if(/^#[a-f0-9]{6}$/i.test(input[key]||''))next[key]=input[key];for(const [key,min,max]of [['opacity',0,100],['videoHeight',80,600],['videoWidth',30,100]])if(Number.isFinite(input[key]))next[key]=Math.max(min,Math.min(max,input[key]));for(const key of ['videoVisible','videoSound'])if(typeof input[key]==='boolean')next[key]=input[key];if(['cover','contain'].includes(input.videoFit))next.videoFit=input.videoFit;return next;}
export function readAppearance(){try{return cleanAppearance(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{return {...APPEARANCE_DEFAULTS};}}
export function saveAppearance(value){localStorage.setItem(KEY,JSON.stringify(cleanAppearance(value)));}
export function appearanceStyle(value){const rgb=hex=>hex.slice(1).match(/../g).map(x=>parseInt(x,16));const rgba=(hex,alpha)=>`rgba(${rgb(hex).join(',')},${alpha})`;return {'--bg':rgba(value.background,value.opacity/100),'--surface':rgba(value.background,Math.max(.08,value.opacity/100)),'--accent':value.accent,'--accent-light':value.accent,'--border':value.border,'--text':value.text,'--muted':value.muted,background:rgba(value.background,value.opacity/100),color:value.text};}
function ColorField({label,value,onChange}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);return <label className="appearance-color"><span>{label}</span><input type="color" aria-label={`${label} Farbauswahl`} value={value} onChange={e=>onChange(e.target.value)}/><input type="text" aria-label={`${label} HEX`} value={draft} maxLength={7} onChange={e=>{setDraft(e.target.value);if(/^#[a-f0-9]{6}$/i.test(e.target.value))onChange(e.target.value);}} onBlur={()=>setDraft(value)}/></label>;}
export function RgbVideoHeader({appearance,onChange}){const ref=useRef(null),[blocked,setBlocked]=useState(false);useEffect(()=>{if(ref.current){ref.current.muted=!appearance.videoSound;ref.current.play()?.then(()=>setBlocked(false)).catch(()=>setBlocked(true));}},[appearance.videoSound,appearance.videoVisible]);if(!appearance.videoVisible)return null;return <section className="rgb-video-header" aria-label="ASUS Kopfvideo" style={{width:`${appearance.videoWidth}%`,height:appearance.videoHeight}}><video ref={ref} src="/asus-header.mp4" autoPlay loop playsInline muted={!appearance.videoSound} style={{objectFit:appearance.videoFit}} aria-label="ASUS Animation"/><button className="video-sound-button" aria-label={appearance.videoSound?'Videoton ausschalten':'Videoton einschalten'} aria-pressed={appearance.videoSound} onClick={()=>onChange({videoSound:!appearance.videoSound})}>{appearance.videoSound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button>{blocked?<button className="video-play-fallback secondary" onClick={()=>ref.current?.play().then(()=>setBlocked(false)).catch(()=>{})}>Video starten</button>:null}</section>;}
export function RgbAppearance({appearance,onChange,onReset}){return <div className="page-content appearance-page"><section className="surface settings-section"><div className="appearance-heading"><div><h2>Farbe anpassen</h2><p>Dein Design wird sofort angezeigt und auf diesem PC gespeichert.</p></div><button className="secondary" onClick={onReset}><RotateCcw size={16}/>Schwarz-Gold wiederherstellen</button></div><div className="appearance-grid">{[['background','Hintergrund'],['accent','Gold / Akzent'],['border','Rahmen'],['text','Schrift'],['muted','Nebenbeschriftungen']].map(([key,label])=><ColorField key={key} label={label} value={appearance[key]} onChange={value=>onChange({[key]:value})}/>)}</div><label className="appearance-range">Hintergrund-Deckkraft <output>{appearance.opacity}%</output><input type="range" aria-label="Hintergrund-Deckkraft" min="0" max="100" value={appearance.opacity} onChange={e=>onChange({opacity:+e.target.value})}/></label></section><section className="surface settings-section"><h2>ASUS Kopfvideo</h2><p>Das mitgelieferte Original läuft automatisch in Schleife. Es enthält keine Audiospur; der Ton-Schalter bleibt für die Wiedergabeeinstellung verfügbar.</p><div className="appearance-video-controls"><label><input type="checkbox" checked={appearance.videoVisible} onChange={e=>onChange({videoVisible:e.target.checked})}/>Video anzeigen</label><label><input type="checkbox" checked={appearance.videoSound} onChange={e=>onChange({videoSound:e.target.checked})}/>Videoton erlauben</label><label>Darstellung<select aria-label="Darstellung" value={appearance.videoFit} onChange={e=>onChange({videoFit:e.target.value})}><option value="contain">Vollständig anzeigen</option><option value="cover">Bereich ausfüllen</option></select></label><label>Höhe in Pixel<input type="number" aria-label="Videohöhe" min="80" max="600" value={appearance.videoHeight} onChange={e=>onChange({videoHeight:+e.target.value})}/></label><label>Breite in Prozent<input type="number" aria-label="Videobreite" min="30" max="100" value={appearance.videoWidth} onChange={e=>onChange({videoWidth:+e.target.value})}/></label></div></section></div>;}
