'use strict';
const path=require('node:path'),{spawn:spawnChild}=require('node:child_process');
function defaultHelperPath(){let packaged=false;if(process.versions.electron)try{packaged=require('electron').app?.isPackaged===true;}catch{}return path.join(packaged?process.resourcesPath:path.resolve(__dirname,'../../..'),'FanAtlas/BattoAudioControl.exe');}
function validId(id){return typeof id==='string'&&id.length<=2048&&!/[\u0000-\u001f]/.test(id)&&(id==='master'||id==='jarvis'||/^(app|device):.+/.test(id));}
function unavailable(id){return {id,name:id==='master'?'Windows-Lautstärke':id==='jarvis'?'Jarvis':'Zurzeit nicht verfügbar',volume:null,muted:false,available:false};}
function normalize(value,id){if(!value||value.id!==id||value.available!==true||typeof value.volume!=='number'||!Number.isFinite(value.volume)||value.volume<0||value.volume>100)return unavailable(id);return {id,name:String(value.name||id).replace(/[\u0000-\u001f]/g,' ').slice(0,160),volume:Math.round(value.volume*10)/10,muted:value.muted===true,available:true};}
class TouchAudio{
 constructor({helperPath,spawn=spawnChild,getJarvis,setJarvis,idleMs=15000,timeoutMs=6000,now=Date.now}={}){this.helperPath=helperPath||defaultHelperPath();this.spawn=spawn;this.getJarvis=getJarvis;this.setJarvis=setJarvis;this.idleMs=idleMs;this.timeoutMs=timeoutMs;this.now=now;this.child=null;this.closed=false;this.sequence=0;this.pending=new Map();this.cache=null;this.reading=null;this.writes=new Map();this.writeCount=0;}
 _error(message,transport=false){const error=Error(message);error.transport=transport;return error;}
 _rejectPending(error){for(const item of this.pending.values()){clearTimeout(item.timer);item.reject(error);}this.pending.clear();}
 _stop(reason='Audioverbindung beendet.'){clearTimeout(this.idleTimer);this.idleTimer=null;const child=this.child;this.child=null;if(child){try{child.stdin.end();}catch{}try{child.kill();}catch{}}this._rejectPending(this._error(reason,true));}
 _idle(){clearTimeout(this.idleTimer);if(!this.child||this.pending.size)return;this.idleTimer=setTimeout(()=>this._stop(),this.idleMs);this.idleTimer.unref?.();}
 _start(){if(this.closed)throw Error('Audiosteuerung ist geschlossen.');if(this.child)return this.child;let child;try{child=this.spawn(this.helperPath,[],{windowsHide:true,stdio:['pipe','pipe','pipe']});}catch{throw this._error('Der Windows-Audiohelfer fehlt oder konnte nicht gestartet werden.',true);}this.child=child;let buffer='';child.stdout.setEncoding('utf8');
  child.stdout.on('data',chunk=>{if(this.child!==child)return;buffer+=chunk;if(buffer.length>1048576){this._stop('Antwort des Audiohelfers ist zu groß.');return;}let newline;while((newline=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,newline).trim();buffer=buffer.slice(newline+1);if(!line)continue;let response;try{response=JSON.parse(line);}catch{this._stop('Ungültige Antwort des Audiohelfers.');return;}const item=this.pending.get(response.id);if(!item)continue;this.pending.delete(response.id);clearTimeout(item.timer);if(response.ok===true)item.resolve(response);else item.reject(this._error(String(response.error||'Audioaktion fehlgeschlagen.').slice(0,500)));}this._idle();});
  child.stderr.on('data',()=>{});const failed=()=>{if(this.child!==child)return;this.child=null;clearTimeout(this.idleTimer);this._rejectPending(this._error('Die Verbindung zum Windows-Audiohelfer wurde beendet.',true));};child.on('error',failed);child.on('exit',failed);child.stdin.on('error',failed);return child;
 }
 _request(command,data={}){if(this.closed)return Promise.reject(Error('Audiosteuerung ist geschlossen.'));if(this.pending.size>=64)return Promise.reject(Error('Zu viele Audioaktionen. Bitte kurz warten.'));clearTimeout(this.idleTimer);return new Promise((resolve,reject)=>{let child;try{child=this._start();}catch(error){reject(error);return;}const id=++this.sequence,timer=setTimeout(()=>{if(this.pending.has(id))this._stop('Windows antwortet auf die Audioanfrage nicht rechtzeitig.');},this.timeoutMs);timer.unref?.();this.pending.set(id,{resolve,reject,timer});try{child.stdin.write(JSON.stringify({id,command,...data})+'\n');}catch{this._stop('Audioanfrage konnte nicht gesendet werden.');}});}
 async _nativeTargets(){if(this.cache&&this.now()-this.cache.at<1000)return this.cache.values;if(this.reading)return this.reading;this.reading=(async()=>{let response;try{response=await this._request('targets');}catch(error){if(!error.transport||this.closed)throw error;response=await this._request('targets');}if(!Array.isArray(response.targets)||response.targets.length>1024)throw Error('Ungültige Liste der Audioprogramme.');const values=response.targets.filter(x=>x&&validId(x.id)&&x.id!=='jarvis').map(x=>normalize(x,x.id));this.cache={at:this.now(),values};return values;})();try{return await this.reading;}finally{this.reading=null;}}
 async _jarvis(){if(typeof this.getJarvis!=='function'||typeof this.setJarvis!=='function')return unavailable('jarvis');const value=await this.getJarvis();return normalize({id:'jarvis',name:'Jarvis',available:true,...value},'jarvis');}
 async targets(){if(this.closed)throw Error('Audiosteuerung ist geschlossen.');const [native,jarvis]=await Promise.all([this._nativeTargets(),this._jarvis()]);return [...native.filter(x=>x.id==='master'),jarvis,...native.filter(x=>x.id!=='master')].map(x=>({...x}));}
 async state(ids){if(!Array.isArray(ids)||ids.length>128||ids.some(id=>!validId(id)))throw Error('Ungültige Auswahl der Audioregler.');if(this.closed)throw Error('Audiosteuerung ist geschlossen.');const unique=[...new Set(ids)],native=unique.some(x=>x!=='jarvis')?await this._nativeTargets():[],result={};for(const id of unique)result[id]=id==='jarvis'?await this._jarvis():{...(native.find(x=>x.id===id)||unavailable(id))};return result;}
 async set(id,patch){if(!validId(id))throw Error('Ungültiges Audioziel.');if(this.closed)throw Error('Audiosteuerung ist geschlossen.');if(!patch||typeof patch!=='object'||Array.isArray(patch)||Object.keys(patch).some(k=>!['volume','muted'].includes(k))||Object.keys(patch).length!==1)throw Error('Genau Lautstärke oder Stummschaltung ändern.');if(Object.hasOwn(patch,'volume')&&(typeof patch.volume!=='number'||!Number.isFinite(patch.volume)||patch.volume<0||patch.volume>100))throw Error('Lautstärke muss zwischen 0 und 100 liegen.');if(Object.hasOwn(patch,'muted')&&typeof patch.muted!=='boolean')throw Error('Ungültige Stummschaltung.');
  // Serialize each target so an older slider command never arrives after its final value.
  if(this.writeCount>=64)throw Error('Zu viele Audioaktionen. Bitte kurz warten.');this.writeCount++;const previous=this.writes.get(id)||Promise.resolve(),operation=previous.catch(()=>{}).then(async()=>{if(this.closed)throw Error('Audiosteuerung ist geschlossen.');if(id==='jarvis'){if(typeof this.setJarvis!=='function')throw Error('Jarvis-Lautstärke ist nicht verfügbar.');await this.setJarvis({...patch});return this._jarvis();}const response=await this._request('set',{target:id,...patch}),value=normalize(response.value,id);this.cache=null;return value;});this.writes.set(id,operation);try{return await operation;}finally{this.writeCount--;if(this.writes.get(id)===operation)this.writes.delete(id);}
 }
 close(){this.closed=true;this._stop();this.cache=null;}
}
module.exports={TouchAudio};
