using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BattoAudio;

internal record TargetValue(string id,string name,double? volume,bool muted,bool available);
internal sealed class VolumeHandle {
 public required string Id,Name;public IAudioEndpointVolume? Endpoint;public ISimpleAudioVolume? Session;
 public (float volume,bool muted) Read(){float value;bool muted;if(Endpoint!=null){Native.Check(Endpoint.GetMasterVolumeLevelScalar(out value));Native.Check(Endpoint.GetMute(out muted));}else{Native.Check(Session!.GetMasterVolume(out value));Native.Check(Session.GetMute(out muted));}return (value,muted);}
 public void Set(double? volume,bool? muted){Guid context=Guid.Empty;if(Endpoint!=null){if(volume.HasValue)Native.Check(Endpoint.SetMasterVolumeLevelScalar((float)volume.Value/100,ref context));if(muted.HasValue)Native.Check(Endpoint.SetMute(muted.Value,ref context));}else{if(volume.HasValue)Native.Check(Session!.SetMasterVolume((float)volume.Value/100,ref context));if(muted.HasValue)Native.Check(Session!.SetMute(muted.Value,ref context));}}
}
internal sealed class Catalog:IDisposable {
 private readonly List<object> owned=[];private readonly Dictionary<string,List<VolumeHandle>> groups=new(StringComparer.Ordinal);
 private T Own<T>(T value)where T:class{owned.Add(value);return value;}
 private void Add(VolumeHandle handle){if(!groups.TryGetValue(handle.Id,out var list))groups[handle.Id]=list=[];list.Add(handle);}
 public Catalog(){try{
  var enumerator=Own((IMMDeviceEnumerator)new DeviceEnumerator());string defaultId="";IMMDevice? defaultDevice=null;try{if(enumerator.GetDefaultAudioEndpoint(0,0,out defaultDevice)>=0)Native.Check(defaultDevice.GetId(out defaultId));}finally{Native.Release(defaultDevice);}
  Native.Check(enumerator.EnumAudioEndpoints(0,1,out var collection));Own(collection);Native.Check(collection.GetCount(out var count));
  for(uint i=0;i<Math.Min(count,64);i++){IMMDevice? device=null;try{Native.Check(collection.Item(i,out device));Native.Check(device.GetId(out var id));var name=FriendlyName(device);
   try{var iid=Native.EndpointVolume;Native.Check(device.Activate(ref iid,23,IntPtr.Zero,out var value));Own(value);var endpoint=(IAudioEndpointVolume)value;Add(new(){Id="device:"+id,Name=name,Endpoint=endpoint});if(id==defaultId)Add(new(){Id="master",Name="Windows-Lautstärke",Endpoint=endpoint});}catch(COMException){}
   try{var iid=Native.SessionManager;Native.Check(device.Activate(ref iid,23,IntPtr.Zero,out var managerObject));Own(managerObject);var manager=(IAudioSessionManager2)managerObject;Native.Check(manager.GetSessionEnumerator(out var sessions));Own(sessions);Native.Check(sessions.GetCount(out var total));
    for(int n=0;n<Math.Min(total,256);n++){object? sessionObject=null;try{Native.Check(sessions.GetSession(n,out sessionObject));var control=(IAudioSessionControl2)sessionObject;Native.Check(control.GetState(out var state));if(state==2)continue;Native.Check(control.GetProcessId(out var pid));string appId,appName;if(control.IsSystemSoundsSession()==0){appId="app:system";appName="Windows-Systemklänge";}else{var executable=Native.ProcessPath(pid);if(string.IsNullOrWhiteSpace(executable))continue;appId="app:"+Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(executable.ToLowerInvariant()))).ToLowerInvariant();appName=Path.GetFileNameWithoutExtension(executable);}
     var volume=(ISimpleAudioVolume)sessionObject;Native.Check(volume.GetMasterVolume(out _));Own(sessionObject);sessionObject=null;Add(new(){Id=appId,Name=appName,Session=volume});
    }catch(COMException){}catch(InvalidCastException){}finally{Native.Release(sessionObject);}}
   }catch(COMException){}
  }catch(COMException){}finally{Native.Release(device);}}
 }catch{Dispose();throw;}}
 private static string FriendlyName(IMMDevice device){IPropertyStore? store=null;var value=new PropVariant();try{Native.Check(device.OpenPropertyStore(0,out store));var key=new PropertyKey{Format=new Guid("A45C254E-DF1C-4EFD-8020-67D146A850E0"),Id=14};Native.Check(store.GetValue(ref key,out value));return value.Type==31?Marshal.PtrToStringUni(value.Value)??"Audiogerät":"Audiogerät";}catch(COMException){return "Audiogerät";}finally{Native.PropVariantClear(ref value);Native.Release(store);}}
 public TargetValue Value(string id){if(!groups.TryGetValue(id,out var handles))return new(id,id=="master"?"Windows-Lautstärke":"Zurzeit nicht verfügbar",null,false,false);var readings=new List<(float volume,bool muted)>();foreach(var handle in handles)try{readings.Add(handle.Read());}catch(COMException){}if(readings.Count==0)return new(id,handles[0].Name,null,false,false);return new(id,handles[0].Name,Math.Round(Math.Clamp(readings.Average(x=>x.volume)*100,0,100),1),readings.All(x=>x.muted),true);}
 public List<TargetValue> Targets(){var values=groups.Keys.Select(Value).OrderBy(x=>x.id=="master"?0:x.id.StartsWith("device:")?1:2).ThenBy(x=>x.name,StringComparer.CurrentCultureIgnoreCase).ToList();if(!groups.ContainsKey("master"))values.Insert(0,Value("master"));return values;}
 public TargetValue Set(string id,double? volume,bool? muted){if(!groups.TryGetValue(id,out var handles))throw new InvalidOperationException("Dieses Audioprogramm oder Gerät ist zurzeit nicht verfügbar. Es wurde nichts anderes geändert.");int successful=0;foreach(var handle in handles)try{handle.Set(volume,muted);successful++;}catch(COMException){}if(successful==0)throw new InvalidOperationException("Windows konnte diese Lautstärke nicht ändern.");return Value(id);}
 public void Dispose(){for(int i=owned.Count-1;i>=0;i--)Native.Release(owned[i]);owned.Clear();groups.Clear();}
}
internal static class Program {
 [MTAThread]static int Main(string[] args){Console.InputEncoding=Encoding.UTF8;Console.OutputEncoding=new UTF8Encoding(false);if(args.SequenceEqual(new[]{"--self-test"}))return SelfTest();while(true){var line=ReadBoundedLine();if(line==null)break;JsonElement request=default;long id=0;try{using var document=JsonDocument.Parse(line);request=document.RootElement;if(request.ValueKind!=JsonValueKind.Object)throw new InvalidOperationException("Ungültige Audioanfrage.");id=request.GetProperty("id").GetInt64();if(id<1)throw new InvalidOperationException("Ungültige Anfrage-ID.");var command=request.GetProperty("command").GetString();string? target=null;double? volume=null;bool? muted=null;List<string>? targets=null;
   if(command=="set"){target=ValidTarget(request.GetProperty("target"));if(request.TryGetProperty("volume",out var v)){volume=v.GetDouble();if(!double.IsFinite(volume.Value)||volume<0||volume>100)throw new InvalidOperationException("Lautstärke muss zwischen 0 und 100 liegen.");}if(request.TryGetProperty("muted",out var m))muted=m.GetBoolean();if(volume.HasValue==muted.HasValue)throw new InvalidOperationException("Genau Lautstärke oder Stummschaltung ändern.");}
   else if(command=="state"){var items=request.GetProperty("targets");if(items.ValueKind!=JsonValueKind.Array||items.GetArrayLength()>128)throw new InvalidOperationException("Zu viele Audioziele.");targets=items.EnumerateArray().Select(ValidTarget).Distinct().ToList();}else if(command!="targets")throw new InvalidOperationException("Unbekannte Audioaktion.");
   using var catalog=new Catalog();object response=command=="targets"?new{id,ok=true,targets=catalog.Targets()}:command=="state"?new{id,ok=true,values=targets!.ToDictionary(t=>t,catalog.Value)}:new{id,ok=true,value=catalog.Set(target!,volume,muted)};Console.WriteLine(JsonSerializer.Serialize(response));
  }catch(Exception error){if(Environment.GetEnvironmentVariable("BATTO_AUDIO_DIAGNOSTICS")=="1")Console.Error.WriteLine(error);var text=error is InvalidOperationException?error.Message:error is COMException?"Windows-Audiogeräte sind momentan nicht erreichbar.":"Ungültige Audioanfrage.";Console.WriteLine(JsonSerializer.Serialize(new{id,ok=false,error=text}));}}return 0;}
 private static int SelfTest(){IMMDeviceEnumerator? enumerator=null;IMMDevice? device=null;object? managerObject=null;ISimpleAudioVolume? volume=null;float previous=0;bool wasMuted=false,restore=false;try{enumerator=(IMMDeviceEnumerator)new DeviceEnumerator();Native.Check(enumerator.GetDefaultAudioEndpoint(0,0,out device));var managerId=Native.SessionManager;Native.Check(device.Activate(ref managerId,23,IntPtr.Zero,out managerObject));var manager=(IAudioSessionManager2)managerObject;var sessionId=Guid.NewGuid();Native.Check(manager.GetSimpleAudioVolume(ref sessionId,0,out volume));Native.Check(volume.GetMasterVolume(out previous));Native.Check(volume.GetMute(out wasMuted));restore=true;Guid context=Guid.Empty;Native.Check(volume.SetMasterVolume(.37f,ref context));Native.Check(volume.GetMasterVolume(out var actual));if(Math.Abs(actual-.37f)>.001)throw new InvalidOperationException("Eigene Testsitzung: Lautstärkeprüfung fehlgeschlagen.");Native.Check(volume.SetMute(true,ref context));Native.Check(volume.GetMute(out var muted));if(!muted)throw new InvalidOperationException("Eigene Testsitzung: Stummschaltung fehlgeschlagen.");Console.WriteLine(JsonSerializer.Serialize(new{ok=true,scope="isolated audio session",volumeVerified=true,muteVerified=true}));return 0;}catch(Exception error){Console.Error.WriteLine(error.Message);return 1;}finally{if(restore&&volume!=null){Guid context=Guid.Empty;volume.SetMasterVolume(previous,ref context);volume.SetMute(wasMuted,ref context);}Native.Release(volume);Native.Release(managerObject);Native.Release(device);Native.Release(enumerator);}}
 private static string ValidTarget(JsonElement value){var id=value.GetString();if(string.IsNullOrWhiteSpace(id)||id.Length>2048||id.Any(char.IsControl)||!(id=="master"||id.StartsWith("app:",StringComparison.Ordinal)||id.StartsWith("device:",StringComparison.Ordinal)))throw new InvalidOperationException("Ungültiges Audioziel.");return id;}
 private static string? ReadBoundedLine(){var result=new StringBuilder();int current;bool over=false;while((current=Console.Read())!=-1&&current!='\n'){if(result.Length>=16384)over=true;else if(current!='\r')result.Append((char)current);}if(current==-1&&result.Length==0)return null;return over?"{}":result.ToString();}
}
