const { contextBridge, ipcRenderer } = require('electron');

const on = (channel, callback) => {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};

contextBridge.exposeInMainWorld('batto', {
  suite: (command,value) => {if(!['control','catalog','reset-likes','import-status','import-obs-settings','state','command','settings','listen','stop','devices','scenes','fan-config','profile','csv','voice-folder','copy-obs','open-obs','export-layout','import-layout','export-curve','plugin','forget-memory'].includes(command))throw Error('Unbekannte Aktion');return ipcRenderer.invoke('suite:'+command,value);},
  onSuiteState:cb=>on('suite:state',cb),onJarvisMessage:cb=>on('suite:message',cb),onJarvisVoice:cb=>on('suite:voice',cb),
  dual:(command,value)=>{if(!['register-cameras','program','scene','background','state','save','probe','prepare','release','start','stop','mute','key','snapshot','library','import','export'].includes(command))throw Error('Unbekannte Aktion');return ipcRenderer.invoke('dual:action',{command,value});},
  onDualState:cb=>on('dual:state',cb),onPresentationState:cb=>on('suite:presentation',cb),
  communityStatus:()=>ipcRenderer.invoke('community:status'),
  archiveSearch:payload=>ipcRenderer.invoke('archive:search',payload),
  archiveSessions:()=>ipcRenderer.invoke('archive:sessions'),
  archiveContext:payload=>ipcRenderer.invoke('archive:context',payload),
  archiveExport:payload=>ipcRenderer.invoke('archive:export',payload),
  archiveConfig:payload=>ipcRenderer.invoke('archive:config',payload),
  archiveChooseDirectory:()=>ipcRenderer.invoke('archive:chooseDirectory'),
  moderationCapabilities:payload=>ipcRenderer.invoke('moderation:capabilities',payload),
  moderationResolve:payload=>ipcRenderer.invoke('moderation:resolve',payload),
  moderationState:payload=>ipcRenderer.invoke('moderation:state',payload),
  moderationHistory:payload=>ipcRenderer.invoke('moderation:history',payload),
  moderationLoginStatus:()=>ipcRenderer.invoke('moderation:loginStatus'),
  moderationOpenLogin:payload=>ipcRenderer.invoke('moderation:openLogin',payload),
  moderationRefresh:payload=>ipcRenderer.invoke('moderation:refresh',payload),
  moderationPerform:payload=>ipcRenderer.invoke('moderation:perform',payload),
  moderationConnect:payload=>ipcRenderer.invoke('moderation:connect',payload),
  moderationDisconnect:payload=>ipcRenderer.invoke('moderation:disconnect',payload),
  viewersStatus:()=>ipcRenderer.invoke('viewers:status'),
  viewersConfig:payload=>ipcRenderer.invoke('viewers:config',payload),
  onCommunityStatus:cb=>on('community:status',cb),
  onViewersStatus:cb=>on('viewers:status',cb),
  onModerationStatus:cb=>on('moderation:state',cb),
  onModerationLoginStatus:cb=>on('moderation:loginStatus',cb),
  giftLibrary:payload=>ipcRenderer.invoke('gifts:library',payload),
  giftCatalog:payload=>ipcRenderer.invoke('gifts:catalog',payload),
  resolveGiftItems:payload=>ipcRenderer.invoke('gifts:resolve',payload),
  onGiftCatalogChanged:cb=>on('gifts:catalog-changed',cb),
  chooseGiftFolder:()=>ipcRenderer.invoke('gifts:folder'),
  chatWidgetTest:payload=>ipcRenderer.invoke('chat-widgets:test',payload),
  onChatWidgetTrigger:cb=>on('chat-widgets:trigger',cb),
  openExternal:url=>ipcRenderer.invoke('external:open',url),
  openLiveCenter:()=>ipcRenderer.invoke('livecenter:open'),
  hotkeyCapture:()=>ipcRenderer.invoke('hotkeys:capture'),
  hotkeyCancelCapture:()=>ipcRenderer.invoke('hotkeys:cancel-capture'),
  onHotkeyStatus:cb=>on('hotkeys:status',cb),
  audioReady: () => ipcRenderer.send('audio:ready'),
  audioResult: result => ipcRenderer.send('audio:result', result),
  onAudioPlay: cb => on('audio:play', cb),
  onAudioCancel: cb => on('audio:cancel', cb),
  testAudioOutput: output => ipcRenderer.invoke('audio:testOutput', output),
  navigationState:view=>ipcRenderer.send('navigation:state',view),
  copyNavigationConnection:()=>ipcRenderer.invoke('navigation:copy'),
  streamerbotConnect:()=>ipcRenderer.invoke('streamerbot:connect'),
  streamerbotDisconnect:()=>ipcRenderer.invoke('streamerbot:disconnect'),
  streamerbotStatus:()=>ipcRenderer.invoke('streamerbot:status'),
  streamerbotActions:()=>ipcRenderer.invoke('streamerbot:actions'),
  streamerbotPassword:password=>ipcRenderer.invoke('streamerbot:password',password),
  testCustomEvent:payload=>ipcRenderer.invoke('events:custom',payload),
  triggerChain:id=>ipcRenderer.invoke('chains:trigger',id),
  chainStatus:()=>ipcRenderer.invoke('chains:status'),
  hotkeyStatus:()=>ipcRenderer.invoke('hotkeys:status'),
  onStreamerbotStatus:cb=>on('streamerbot:status',cb),
  onChainStatus:cb=>on('chains:status',cb),
  getState: () => ipcRenderer.invoke('state:get'),
  saveConfig: (patch) => ipcRenderer.invoke('config:save', patch),
  resetConfig: (section) => ipcRenderer.invoke('config:reset', section),
  settingsDraft: (patch) => ipcRenderer.invoke('settings:draft', patch),
  settingsApply: () => ipcRenderer.invoke('settings:apply'),
  settingsDiscard: () => ipcRenderer.invoke('settings:discard'),
  settingsReset: (section) => ipcRenderer.invoke('settings:reset', section),
  settingsTest: (section) => ipcRenderer.invoke('settings:test', section),

  connectAdapter: (name) => ipcRenderer.invoke('adapter:connect', name),
  disconnectAdapter: (name) => ipcRenderer.invoke('adapter:disconnect', name),
  adapterHealth: (name) => ipcRenderer.invoke('adapter:health', name),

  testMessage: (payload) => ipcRenderer.invoke('chat:test', payload),
  sendMessage: (payload) => ipcRenderer.invoke('chat:send', payload),
  moderate: (payload) => ipcRenderer.invoke('moderation:act', payload),
  addFilter: (payload) => ipcRenderer.invoke('filter:add', payload),
  removeFilter: (id) => ipcRenderer.invoke('filter:remove', id),
  clearChat: () => ipcRenderer.invoke('chat:clear'),
  clearLogs: () => ipcRenderer.invoke('logs:clear'),

  obsConnect: (payload) => ipcRenderer.invoke('obs:connect', payload),
  obsDisconnect: () => ipcRenderer.invoke('obs:disconnect'),
  obsTest: () => ipcRenderer.invoke('obs:test'),
  youtubeSaveKey: (key) => ipcRenderer.invoke('youtube:saveKey', key),
  platformSaveWriteToken: payload => ipcRenderer.invoke('platform:saveWriteToken', payload),
  copyTikTokBridge: () => ipcRenderer.invoke('platform:copyTikTokBridge'),
  discordSaveWebhook: (url) => ipcRenderer.invoke('discord:saveWebhook', url),
  discordTest: (text) => ipcRenderer.invoke('discord:test', text),

  cngSaveChatUrl: (url) => ipcRenderer.invoke('cng:saveChatUrl', url),
  cngClearChatUrl: () => ipcRenderer.invoke('cng:clearChatUrl'),
  cngCopyUrl: (kind) => ipcRenderer.invoke('cng:copyUrl', kind),
  cngOpenUrl: (kind) => ipcRenderer.invoke('cng:openUrl', kind),

  ttsListVoices: () => ipcRenderer.invoke('tts:listVoices'),
  ttsSynthesize: (payload) => ipcRenderer.invoke('tts:synthesize', payload),
  ttsCleanup: (filePath) => ipcRenderer.invoke('tts:cleanup', filePath),
  onTtsCancel: cb => on('tts:cancel', cb),
  battleGetState: () => ipcRenderer.invoke('battle:getState'),
  battleSaveKey: value => ipcRenderer.invoke('battle:saveKey', value),
  battleReconnect: () => ipcRenderer.invoke('battle:reconnect'),
  onBattleState: cb => on('battle:state', cb),
  onBattlePreview: cb => on('battle:preview', cb),

  importFont: () => ipcRenderer.invoke('dialog:font'),
  importMedia: () => ipcRenderer.invoke('dialog:media'),
  importChatBackground: () => ipcRenderer.invoke('dialog:chatBackground'),
  resetChatBackground: () => ipcRenderer.invoke('chat-background:reset'),
  importLocalChatIcon: () => ipcRenderer.invoke('dialog:localChatIcon'),
  resetLocalChatIcon: () => ipcRenderer.invoke('local-chat-icon:reset'),
  removeMedia: (id) => ipcRenderer.invoke('media:remove', id),
  testAutomationSequence: payload=>ipcRenderer.invoke('automation:testSequence',payload),
  testAutomationAction: (action) => ipcRenderer.invoke('automation:testAction', action),
  cancelAutomation: (ruleId) => ipcRenderer.invoke('automation:cancel', ruleId),
  cancelAllAutomations: () => ipcRenderer.invoke('automation:cancelAll'),
  activeAutomations: () => ipcRenderer.invoke('automation:active'),
  twitchLogin: () => ipcRenderer.invoke('twitch:login'),
  twitchLoginStatus: () => ipcRenderer.invoke('twitch:loginStatus'),
  twitchOpenLogin: () => ipcRenderer.invoke('twitch:openLogin'),
  twitchCancelLogin: () => ipcRenderer.invoke('twitch:cancelLogin'),
  resetWelcome: () => ipcRenderer.invoke('welcome:reset'),
  testBroadcast: () => ipcRenderer.invoke('broadcast:test'),
  broadcastUpsert: x=>ipcRenderer.invoke('broadcast:upsert',x),
  broadcastDelete: x=>ipcRenderer.invoke('broadcast:delete',x),
  broadcastDuplicate: x=>ipcRenderer.invoke('broadcast:duplicate',x),
  broadcastMaster: x=>ipcRenderer.invoke('broadcast:master',x),
  broadcastTest: x=>ipcRenderer.invoke('broadcast:testItem',x),
  broadcastStatus: ()=>ipcRenderer.invoke('broadcast:status'),
  onBroadcastStatus: cb=>on('broadcast:status',cb),

  openOverlay: (route) => ipcRenderer.invoke('overlay:open', route),
  testEvent: (event) => ipcRenderer.invoke('overlay:testEvent', event),
  copyText: (text) => ipcRenderer.invoke('clipboard:write', text),

  ffmpegDetect: () => ipcRenderer.invoke('ffmpeg:detect'),
  ffmpegTestEncoder: (encoder) => ipcRenderer.invoke('ffmpeg:testEncoder', encoder),
  ffmpegStart: (args, options) => ipcRenderer.invoke('ffmpeg:start', args, options),
  ffmpegStop: () => ipcRenderer.invoke('ffmpeg:stop'),
  ffmpegStatus: () => ipcRenderer.invoke('ffmpeg:status'),
  healthGet: () => ipcRenderer.invoke('health:get'),
  diagnosticsGet: () => ipcRenderer.invoke('diagnostics:get'),
  diagnosticsExport: () => ipcRenderer.invoke('diagnostics:export'),

  backupNow: () => ipcRenderer.invoke('backup:now'),
  listBackups: () => ipcRenderer.invoke('backup:list'),
  restoreBackup: (path) => ipcRenderer.invoke('backup:restore', path),
  exportConfig: () => ipcRenderer.invoke('dialog:exportConfig'),
  importConfig: () => ipcRenderer.invoke('dialog:importConfig'),
  detachChat: () => ipcRenderer.invoke('window:detach'),
  closeDetached: () => ipcRenderer.invoke('window:closeDetached'),

  onChatMessage: (cb) => on('chat:message', cb),
  onChatHistory: (cb) => on('chat:history', cb),
  onAdapterStatus: (cb) => on('adapter:status', cb),
  onModerationEvent: (cb) => on('moderation:event', cb),
  onFilterHit: (cb) => on('filter:hit', cb),
  onLogEvent: (cb) => on('log:event', cb),
  onPlatformEvent: (cb) => on('platform:event', cb),
  onObsStatus: (cb) => on('obs:status', cb),
  onSystemStatus: (cb) => on('system:status', cb),
  onTtsSpeak: (cb) => on('tts:speak', cb),
  onConfigChanged: (cb) => on('config:changed', cb),
  onChatBackgroundChanged: (cb) => on('chat-background:changed', cb),
  onLocalChatIconChanged: (cb) => on('local-chat-icon:changed', cb),
  onHealthStatus: (cb) => on('health:status', cb),
  onFfmpegStatus: (cb) => on('ffmpeg:status', cb),
  onDatabaseStatus: (cb) => on('database:status', cb)
});
