'use strict';
// Explicit release QA: separate settings, no platform requests, no generated input.
const {app,BrowserWindow,session}=require('electron');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const dir=process.env.BATTO_QA_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'batto-go-qa-'));
fs.mkdirSync(dir,{recursive:true});const profile=path.join(dir,'isolated-profile');fs.mkdirSync(profile,{recursive:true});
app.setPath('userData',profile);app.disableHardwareAcceleration();
const {ConfigStore}=require('../src/core/config-store.cjs');
const config=new ConfigStore(profile);
// One documented public catalogue row, kept only in this isolated QA profile.
fs.mkdirSync(config.dataDir,{recursive:true});
fs.writeFileSync(path.join(config.dataDir,'gift-catalog-cache.json'),JSON.stringify({items:[{giftId:'5655',name:'Rose',coins:1,source:'https://www.eulerstream.com/tools/tiktok-gifts-calculator'}]}));
config.merge({http:{port:Number(process.env.BATTO_QA_PORT||29877)},obs:{enabled:false,autoConnect:false},navigation:{enabled:false},windows:{detachedOpen:false},appearance:{programBackground:false,chatWidgets:{enabled:false}},general:{startView:'dashboard'},
  platforms:{tikfinity:{autoConnect:false},twitch:{autoConnect:false},youtube:{autoConnect:false},cng:{autoOpenGhost:false}},streamerbot:{autoConnect:false},community:{archive:{enabled:false,moderationEnabled:true,excerptsEnabled:false}},
  autoBroadcast:{enabled:false,showInMultiChat:true,items:[]},hotkeys:[],commands:[],actionChains:[],
  events:[{id:'qa-follow',name:'Follower begrüßen',platform:'tiktok',event:'follow',enabled:true,actions:[{type:'overlay',text:'Danke {user}!'}],cooldownSeconds:5}],
  chatExtras:{widgets:[{id:'qa-follow-widget',name:'Follow-Einblendung',url:'https://example.invalid/widget?cid=676051&mode=follow',enabled:true,platform:'tiktok',event:'follow',width:320,height:100,scale:1,anchor:'top-right',x:8,y:8,durationMs:1000,permanent:false,fadeInMs:0,fadeOutMs:0,queueMode:'queue',maxQueue:10,keepAspect:true}],wishlist:{enabled:false,items:[],folderPath:''}}
});
const checks=[],rendererErrors=[],navigationChecks=[];let finished=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function finish(ok,error){if(finished)return;finished=true;fs.writeFileSync(path.join(dir,'result.json'),JSON.stringify({ok,version:app.getVersion(),environment:{browserPlugin:'not available',fallback:'repository Electron E2E',mainViewport:[1480,1020],detachedViewport:[1020,920],obsViewport:[1920,1080],isolation:'separate settings; external HTTP blocked; no platform sends or input execution'},checks,navigationChecks,rendererErrors,error:error?.stack},null,2));console.log(ok?'GO desktop QA passed.':error?.stack);app.quit();setTimeout(()=>app.exit(ok?0:1),3000).unref();}
setTimeout(()=>finish(false,new Error('GO QA timeout')),180000).unref();
async function capture(win,file){await win.webContents.capturePage();await sleep(250);fs.writeFileSync(path.join(dir,file),(await win.webContents.capturePage()).toPNG());}
async function waitFor(fn,label){const end=Date.now()+20000;while(Date.now()<end){try{const r=await fn();if(r)return r;}catch{}await sleep(100);}throw Error('Timeout: '+label);}
app.on('web-contents-created',(_e,wc)=>wc.on('console-message',(_event,level,message)=>{if(level===3&&!/ERR_BLOCKED_BY_CLIENT|example.invalid|Content Security Policy|Potential permissions policy violation/i.test(message))rendererErrors.push(message);}));
app.whenReady().then(async()=>{
 session.defaultSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(details,cb)=>{let host='';try{host=new URL(details.url).hostname;}catch{}cb({cancel:!['127.0.0.1','localhost'].includes(host)});});
 const win=await waitFor(()=>BrowserWindow.getAllWindows()[0],'main window');
 const run=code=>win.webContents.executeJavaScript(`(async()=>{${code}})()`,true);
 await waitFor(()=>run("return typeof S!=='undefined'&&!!S.config&&!!window.BattoChatExtras&&!!window.BattoActionEditor;"),'renderer initialized');
 win.setSize(1480,1020);
 const state=await run('return await batto.getState();');
 assert.equal(state.config.schemaVersion,7);assert.equal('axelchat' in state.config.platforms,false);
 assert.equal(await run("return document.querySelectorAll('[data-view=cohost]').length;"),0);
 assert.equal(await run("return document.querySelectorAll('[data-view-panel=cohost],#cohostModule,#cohostCard,[data-open-cohost]').length;"),0);
 assert.ok(await run("setView('cohost');return document.querySelector('[data-view-panel=dashboard]')?.classList.contains('active');"),'legacy Co-Host route redirects to dashboard');
 assert.ok(await run("return /index\\.html/.test(location.href)&&document.title.length>0&&document.body.textContent.includes('Multi-Chat');"),'real populated app page');
 for(const view of ['wishlist','widgets','livecenter','chatarchive','streamerbot'])assert.ok(await run(`return !!document.querySelector('[data-view=${view}]');`),view);
 checks.push('Schema 7; new navigation; AxelChat absent; Co-Host data retained without menu');
 const rejected=await run("try{await batto.saveConfig({hotkeys:[{id:'qa-invalid',name:'Ungültige Kombination',enabled:true,accelerator:'Control+KeineTaste',actions:[{type:'overlay',text:'QA'}]}]});return false;}catch(e){return e.message;}");
 assert.equal(typeof rejected,'string');assert.match(rejected,/taste|hotkey|aktion/i);
 assert.equal((await run('return (await batto.getState()).config.hotkeys;')).length,0);
 const recovered=await run("return await batto.saveConfig({platforms:{twitch:{channel:'qa_unconnected'}}});");
 assert.equal(recovered.platforms.twitch.channel,'qa_unconnected');
 assert.equal((await run('return (await batto.getState()).config.hotkeys;')).length,0);
 await run("await batto.saveConfig({community:{viewers:{enabled:false}}});await batto.saveConfig({community:{viewers:{enabled:true}}});");
 await run("await batto.settingsDraft({hotkeys:[{id:'qa-old-draft',name:'Alter Entwurf',enabled:true,accelerator:'Control+KeineTaste',stopAll:true}]});");
 const resetAfterDraft=await run("return await batto.resetConfig('chatColors');");
 assert.equal(resetAfterDraft.chatColors.enabled,false);assert.equal(resetAfterDraft.hotkeys.length,0);
 await run('await batto.settingsDiscard();');
 checks.push('Invalid hotkey rejected without poisoning state; next Twitch and viewer saves succeed through real IPC');
 const library=await run('return await batto.giftLibrary({});');assert.equal(library.ok,true);assert.equal(library.items.length,797);assert.ok(library.items.every(x=>x.giftId===null||x.giftId==='5655'));
 const rose=library.items.find(x=>x.name==='Rose');assert.equal(rose.giftId,'5655');assert.equal(rose.giftIdVerified,true);assert.equal(rose.coins,1);
 await run("setView('wishlist');");await waitFor(()=>run("return document.querySelectorAll('[data-gift-add]').length===60;"),'paged gifts');
 await run("const x=document.querySelector('[data-gift-search]');x.value='Rose';x.dispatchEvent(new Event('input'));");
 assert.ok(await run("return [...document.querySelectorAll('[data-gift-add]')].every(x=>/rose/i.test(x.textContent));"));
 checks.push('797 bundled gift PNGs; paged selection/search; authentic cached Rose ID; no fabricated IDs');
 await run(`document.querySelector('[data-gift-add='+CSS.escape(${JSON.stringify(rose.key)})+']').click();`);
 await waitFor(()=>run("return !!document.querySelector('[data-wish-field=giftId]');"),'selected gift form');
 assert.equal(await run("return document.querySelectorAll('[data-wish-field=giftIdVerified]').length;"),0);
 await run("const f=document.querySelector('#wishlistModule form');f.querySelector('[data-wish-field=name]').value='QA unbekanntes Bild';f.querySelector('[data-wish-field=giftId]').value='';f.elements.enabled.checked=true;f.elements.permanent.checked=false;f.elements.durationMs.value='1';f.elements.fadeInMs.value='0';f.elements.fadeOutMs.value='0';await f.onsubmit({preventDefault(){}});");
 let savedWish=await run('return (await batto.getState()).config.chatExtras.wishlist;');
 assert.equal(savedWish.items[0].giftIdVerified,false);assert.ok(!savedWish.items[0].giftId);assert.equal(savedWish.enabled,true);
 await run("setView('dashboard');await batto.chatWidgetTest({kind:'wishlist',durationMs:1000});");
 await waitFor(()=>run("return document.querySelector('[data-extra-id=wishlist]')?.style.visibility==='visible';"),'wishlist without ID shows');
 await waitFor(()=>run("return document.querySelector('[data-extra-id=wishlist] img')?.naturalWidth>0;"),'wishlist PNG loaded');
 checks.push('Gift selection saves without an ID or confirmation checkbox; local preview displays real image');
 await run("setView('wishlist');");await waitFor(()=>run("return !!document.querySelector('[data-wish-field=giftId]');"),'wishlist reload');
 await run("const f=document.querySelector('#wishlistModule form');f.querySelector('[data-wish-field=name]').value='Rose';f.querySelector('[data-wish-field=giftId]').value='';await f.onsubmit({preventDefault(){}});");
 savedWish=await run('return (await batto.getState()).config.chatExtras.wishlist;');
 assert.equal(savedWish.items[0].giftId,'5655');assert.equal(savedWish.items[0].giftIdVerified,true);
 await waitFor(()=>run("return document.querySelector('[data-wish-field=giftId]')?.value==='5655';"),'automatic gift ID rendered');
 await capture(win,'wishlist.png');
 await run("const f=document.querySelector('#wishlistModule form');f.querySelector('[data-wish-field=giftId]').value='ungueltig';await f.onsubmit({preventDefault(){}});");
 assert.equal((await run('return (await batto.getState()).config.chatExtras.wishlist;')).items[0].giftId,'5655');
 assert.equal(await run("return document.querySelector('[data-wish-field=giftId]').value;"),'ungueltig');
 await run("document.querySelector('[data-wish-reset]').click();");
 checks.push('Known gift ID resolves on save; malformed ID retains draft and does not corrupt saved selection');
 await waitFor(()=>run("return !!document.querySelector('[data-wish-compact]');"),'wishlist reset rendered');
 await run("document.querySelector('[data-wish-compact]').click();");
 await waitFor(()=>run("return document.querySelector('#wishlistModule form')?.elements.width.value==='180';"),'compact preset');
 await run("const f=document.querySelector('#wishlistModule form');f.elements.title.value='Meine Wünsche';f.elements.caption.value='Danke fürs Unterstützen';f.elements.enabled.checked=true;f.elements.permanent.checked=false;f.elements.durationMs.value='2';f.elements.fadeInMs.value='0';f.elements.fadeOutMs.value='0';await f.onsubmit({preventDefault(){}});");
 savedWish=await run('return (await batto.getState()).config.chatExtras.wishlist;');
 assert.equal(savedWish.width,180);assert.equal(savedWish.height,80);assert.equal(savedWish.title,'Meine Wünsche');assert.equal(savedWish.caption,'Danke fürs Unterstützen');
 const obs=new BrowserWindow({show:false,width:1920,height:1080,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true}});
 const obsRun=code=>obs.webContents.executeJavaScript(`(async()=>{${code}})()`);
 try{
  const url=await run("return document.querySelector('[data-wish-obs-url]').textContent;");assert.equal(new URL(url).pathname,'/overlay/wishlist');
  await obs.loadURL(url);await waitFor(()=>obsRun("return document.querySelector('#wishlist img')?.naturalWidth>0;"),'real OBS page loads local PNG');
  assert.ok(await obsRun("return location.protocol==='http:'&&document.title.length>0;"));
  assert.equal(await obsRun("return document.querySelector('.wish-overlay-title').textContent;"),'Meine Wünsche');
  assert.equal(await obsRun("return document.querySelector('.wish-overlay-caption').textContent;"),'Danke fürs Unterstützen');
  const imageResponse=await obsRun("const r=await fetch(document.querySelector('#wishlist img').src);return {status:r.status,type:r.headers.get('content-type'),size:(await r.arrayBuffer()).byteLength};");
  assert.equal(imageResponse.status,200);assert.match(imageResponse.type,/image\/png/);assert.ok(imageResponse.size>100);
  await run("setView('dashboard');await batto.chatWidgetTest({kind:'wishlist',durationMs:2000});");
  await waitFor(()=>run("return document.querySelector('[data-extra-id=wishlist]')?.style.visibility==='visible';"),'native compact wishlist');
  await waitFor(()=>obsRun("return document.querySelector('#wishlist').style.visibility==='visible';"),'OBS trigger visible');
  assert.deepEqual(await run("const r=document.querySelector('[data-extra-id=wishlist]').getBoundingClientRect();return [r.width,r.height];"),[180,80]);
  await Promise.all([capture(win,'wishlist-native-compact.png'),capture(obs,'wishlist-obs-compact.png')]);
  await waitFor(()=>obsRun("return document.querySelector('#wishlist').style.visibility==='hidden';"),'OBS timed hide');
  await run("await batto.saveConfig({chatExtras:{wishlist:{enabled:false}}});");
  assert.equal((await run("return await batto.chatWidgetTest({kind:'wishlist',durationMs:1000});")).ok,false);
  const preview=await run("return await batto.chatWidgetTest({kind:'wishlist',preview:true,durationMs:1000});");assert.equal(preview.ok,true);
  await waitFor(()=>run("return document.querySelector('[data-extra-id=wishlist]')?.style.visibility==='visible';"),'disabled native wishlist temporary preview');
  await waitFor(()=>obsRun("return document.querySelector('#wishlist').style.visibility==='visible';"),'disabled OBS wishlist temporary preview');
  assert.equal((await run('return (await batto.getState()).config.chatExtras.wishlist;')).enabled,false);
  await waitFor(()=>obsRun("return document.querySelector('#wishlist').style.visibility==='hidden';"),'disabled OBS preview expires');
  await waitFor(()=>run("return !document.querySelector('[data-extra-id=wishlist]');"),'disabled native preview removed');
 }finally{obs.destroy();}
 checks.push('Compact 180x80 wishlist title/text persist; real HTTP OBS page and PNG; shared native/OBS trigger; disabled temporary preview expires without changing enabled');
 await run("setView('widgets');");
 assert.equal(await run("return document.querySelector('[data-battlebar-form] [name=widgetUrl]').value;"),'');
 assert.match(await run("return document.querySelector('[data-battlebar-status]').textContent;"),/ausgeschaltet|getrennt|warte/i);
 await run("await document.querySelector('[data-battlebar-test]').onclick();");
 assert.equal((await run('return (await batto.getState()).config.chatExtras.widgets;')).some(x=>x.id==='batto-battlebar'),false);
 await capture(win,'battlebar-missing-url.png');
 checks.push('Battle-Bar without live data shows honest disabled/waiting state; preview does not invent widget URL or points');
 await run("setView('events');");
 assert.equal(await run("return document.querySelectorAll('[data-rule-form]').length;"),0);
 await run("document.querySelector('[data-rule-edit=qa-follow]').click();const x=document.querySelector('[data-rule-form] [name=name]');x.value='Follower – Entwurf';x.dispatchEvent(new Event('input',{bubbles:true}));setView('dashboard');setView('events');document.querySelector('[data-rule-edit=qa-follow]').click();");
 assert.equal(await run("return document.querySelector('[data-rule-form] [name=name]').value;"),'Follower – Entwurf');
 await run("await document.querySelector('[data-rule-form]').onsubmit({preventDefault(){}});");
 assert.equal(await run("return document.querySelectorAll('[data-rule-form]').length;"),0);
 assert.equal((await run('return (await batto.getState()).config.events;'))[0].name,'Follower – Entwurf');
 await run("document.querySelector('[data-rule-edit=qa-follow]').click();document.querySelector('[data-step-remove]').click();await document.querySelector('[data-rule-form]').onsubmit({preventDefault(){}});");
 assert.equal(await run("return document.querySelectorAll('[data-rule-form]').length;"),1);
 assert.equal((await run('return (await batto.getState()).config.events;'))[0].actions.length,1);
 await capture(win,'events.png');
 checks.push('Events collapsed; edit survives navigation; valid save collapses; invalid empty actions retain draft');
 await run("setView('dashboard');");
 await waitFor(()=>run("return !!document.querySelector('[data-extra-id=qa-follow-widget] iframe');"),'widget frame');
 await run("window.qaFrame=document.querySelector('[data-extra-id=qa-follow-widget] iframe');applyAppearance();");
 assert.equal(await run("return qaFrame===document.querySelector('[data-extra-id=qa-follow-widget] iframe');"),true);
 assert.equal(await run("return qaFrame.getAttribute('src');"),'https://example.invalid/widget?cid=676051&mode=follow');
 const preview=await run("return await batto.chatWidgetTest({widgetId:'qa-follow-widget',durationMs:1000});");assert.equal(preview.ok,true,JSON.stringify(preview));
 await waitFor(()=>run("return document.querySelector('[data-extra-id=qa-follow-widget]').style.visibility==='visible';"),'widget visible');
 await waitFor(()=>run("return document.querySelector('[data-extra-id=qa-follow-widget]').style.visibility==='hidden';"),'widget timed hide');
 checks.push('Widget query preserved, frame retained, test shows and expires through real IPC');
 await run("await batto.sendMessage({platform:'local',text:'QA NICHT AUFZEICHNEN'});");
 assert.equal((await run("return await batto.archiveSearch({query:'NICHT'});")).total,0);
 const enable=await run('return await batto.archiveConfig({enabled:true});');assert.notEqual(enable.ok,false,JSON.stringify(enable));
 await waitFor(()=>run('return (await batto.communityStatus()).archive.recording;'),'archive recording');
 const sent=await run("return await batto.sendMessage({platform:'local',text:'QA Grüße 🚨 Suchwort'});");assert.notEqual(sent.ok,false,JSON.stringify(sent));
 await waitFor(()=>run("return (await batto.archiveSearch({query:'Suchwort'})).total===1;"),'archive stored');
 assert.equal((await run("return await batto.archiveSearch({query:'Grüße'});")).items[0].text,'QA Grüße 🚨 Suchwort');
 await run('await batto.archiveConfig({enabled:false});');
 await run("await batto.sendMessage({platform:'local',text:'QA NACHHER NICHT'});");await sleep(150);
 assert.equal((await run("return await batto.archiveSearch({query:'NACHHER'});")).total,0);
 checks.push('Archive off omits text; on writes/searches Unicode; off stops new records');
 await run("setView('chatarchive');");await sleep(250);await capture(win,'archive.png');
 for(const p of ['tiktok','cng']){const r=await run(`return await batto.moderationCapabilities({platform:'${p}'});`);assert.ok(Object.values(r.state.actions).every(x=>x===false||x?.enabled===false),JSON.stringify(r));}
 checks.push('Unavailable TikTok/CNG moderation explicitly disabled, no platform action sent');
 await run("setView('streamerbot');");await waitFor(()=>run("return document.querySelector('#streamerbotModule').textContent.includes('Streamer.bot');"),'central streamerbot');
 await capture(win,'streamerbot.png');
 await run("setView('hotkeys');");assert.equal(await run("return !!document.querySelector('#inputRecord');"),true);
 checks.push('Central Streamer.bot settings and physical input capture controls rendered');
 await run("document.querySelector('#chainName').value='QA gespeicherte Eingaben';document.querySelector('#chainName').dispatchEvent(new Event('input'));document.querySelector('#chainEnabled').checked=false;document.querySelector('#chainEnabled').dispatchEvent(new Event('input'));document.querySelector('#chainType').value='hotkey';document.querySelector('#chainType').onchange();document.querySelector('#stepProcess').value='QA_Never_Execute';document.querySelector('#stepKeys').value='K+RButton';document.querySelector('#stepKeys').dispatchEvent(new Event('input'));setView('dashboard');setView('hotkeys');");
 assert.equal(await run("return document.querySelector('#stepKeys').value;"),'K+RButton');
 assert.equal(await run("return document.querySelector('#stepProcess').value;"),'QA_Never_Execute');
 await run("document.querySelector('#chainType').value='delay';document.querySelector('#chainType').onchange();document.querySelector('#stepDelay').value='123';document.querySelector('#stepDelay').dispatchEvent(new Event('input'));document.querySelector('#chainType').value='hotkey';document.querySelector('#chainType').onchange();");
 assert.equal(await run("return document.querySelector('#stepKeys').value;"),'K+RButton');
 assert.equal(await run("return document.querySelector('#stepKeyFormat').value;"),'chord');
 await run("await document.querySelector('#chainAdd').onclick();document.querySelector('#chainType').value='hotkey';document.querySelector('#chainType').onchange();document.querySelector('#stepProcess').value='QA_Never_Execute';document.querySelector('#stepKeys').value='A+B';document.querySelector('#stepKeys').dispatchEvent(new Event('input'));await document.querySelector('#chainAdd').onclick();await document.querySelector('#chainSave').onclick();");
 let chains=await run('return (await batto.getState()).config.actionChains;');
 const chain=chains.find(x=>x.name==='QA gespeicherte Eingaben');assert.ok(chain);assert.equal(chain.enabled,false);assert.deepEqual(chain.actions.map(x=>x.keys),['K+RButton','A+B']);assert.ok(chain.actions.every(x=>x.keyFormat==='chord'));
 await run("document.querySelector('#chainNew').click();");assert.equal(await run("return document.querySelector('#chainName').value;"),'');
 await run(`document.querySelector('[data-chain-edit="${chain.id}"]').click();document.querySelector('[data-step-edit="0"]').click();`);
 assert.equal(await run("return document.querySelector('#stepKeys').value;"),'K+RButton');
 await run("document.querySelector('#chainCancelStep').click();");
 for(const keys of ['K+RButton','A+B']){
  await run("document.querySelector('#inputNew').click();");
  await run(`document.querySelector('#inputKeyName').value=${JSON.stringify('QA '+keys)};document.querySelector('#inputKey').value=${JSON.stringify(keys)};document.querySelector('#inputChain').value=${JSON.stringify(chain.id)};document.querySelector('#inputEnabled').checked=false;document.querySelector('#inputKey').dispatchEvent(new Event('input'));`);
  if(keys==='K+RButton'){await run("setView('dashboard');setView('hotkeys');");assert.equal(await run("return document.querySelector('#inputKey').value;"),keys);}
  await run("await document.querySelector('#inputSave').onclick();");
  assert.equal(await run("return document.querySelector('#inputKey').value;"),keys);
  await run("await document.querySelector('#inputSave').onclick();");
  assert.equal((await run('return (await batto.getState()).config.hotkeys;')).filter(x=>x.accelerator===keys).length,1);
 }
 const hotkeys=await run('return (await batto.getState()).config.hotkeys;');
 assert.equal(hotkeys.length,2);assert.ok(hotkeys.every(x=>x.enabled===false&&x.chainId===chain.id));assert.deepEqual(hotkeys.map(x=>x.accelerator),['K+RButton','A+B']);
 await run(`document.querySelector('[data-key-edit="${hotkeys[0].id}"]').click();`);
 assert.equal(await run("return document.querySelector('#inputKey').value;"),'K+RButton');
 assert.equal(await run("return document.querySelector('#inputEnabled').checked;"),false);
 assert.equal((await run('return await batto.hotkeyStatus();')).length,0);
 await capture(win,'hotkeys-disabled.png');
 checks.push('K+RButton and A+B chains/hotkeys saved through forms while disabled; repeated save keeps selected values and one ID; drafts survive navigation/type changes; explicit new/reopen preserve values; no input registered or executed');
 await run("setView('livecenter');");assert.ok(await run("return document.querySelector('#livecenterModule').textContent.includes('LIVE Center');"));
 await capture(win,'livecenter.png');
 await run("setView('dashboard');await batto.detachChat();");
 const detached=await waitFor(()=>BrowserWindow.getAllWindows().find(x=>x!==win),'detached chat');
 await waitFor(()=>detached.webContents.executeJavaScript("typeof S!=='undefined'&&!!S.config&&!!window.BattoChatExtras"),'detached ready');
 detached.setSize(1020,920);await run("await batto.saveConfig({appearance:{chatWidgets:{enabled:true,likesEnabled:true,likesUrl:'https://tikfinity.zerody.one/widget/goal?cid=676051&metric=likes',snowEnabled:true,snowUrl:'https://tikfinity.zerody.one/widget/fallingsnow?cid=676051'}}});");await sleep(150);assert.ok(await detached.webContents.executeJavaScript("document.querySelector('#chatList').getBoundingClientRect().height>400"),'Detached chat must fill window');
 await run("await batto.chatWidgetTest({widgetId:'qa-follow-widget',durationMs:1000});");
 await waitFor(()=>detached.webContents.executeJavaScript("document.querySelector('[data-extra-id=qa-follow-widget]')?.style.visibility==='visible'"),'detached widget');
 assert.ok(await detached.webContents.executeJavaScript("!!document.querySelector('.community-viewers')"));
 await capture(detached,'detached.png');
 const runDetached=code=>detached.webContents.executeJavaScript(`(async()=>{${code}})()`);
 const broadcastText='QA Auto-Broadcast identischer Text';
 const countBroadcast=async runner=>runner(`return [...document.querySelectorAll('#chatList .chat-text')].filter(x=>x.textContent===${JSON.stringify(broadcastText)}).length;`);
 const broadcast={id:'qa-local-broadcast',name:'QA nur lokale Ziele',enabled:false,onlyWhenLive:true,onlyWhenChatActive:true,targets:['local','cng'],messages:[broadcastText],intervalSeconds:600,soundMediaId:'',chainId:''};
 assert.equal((await run('return (await batto.getState()).config.autoBroadcast;')).enabled,false);
 for(let number=1;number<=2;number++){
  const result=await run(`return await batto.broadcastTest(${JSON.stringify(broadcast)});`);assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.results.length,2);assert.ok(result.results.every(x=>x.ok&&['local','cng'].includes(x.target)));
  await waitFor(async()=>await countBroadcast(run)===number&&await countBroadcast(runDetached)===number,'one broadcast row per logical run in both chats');
 }
 assert.equal((await run('return (await batto.getState()).config.autoBroadcast;')).enabled,false);
 await run("setView('broadcast');");
 await waitFor(()=>run("return !!document.querySelector('#bcShowInChat');"),'broadcast visibility switch');
 await run("document.querySelector('#bcShowInChat').checked=false;await document.querySelector('#bcMasterSave').onclick();setView('dashboard');");
 await waitFor(async()=>await countBroadcast(run)===0&&await countBroadcast(runDetached)===0,'hide broadcast history in both windows');
 await run("setView('broadcast');document.querySelector('#bcShowInChat').checked=true;await document.querySelector('#bcMasterSave').onclick();setView('dashboard');");
 await waitFor(async()=>await countBroadcast(run)===2&&await countBroadcast(runDetached)===2,'restore both broadcast history rows');
 assert.equal((await run('return (await batto.getState()).config.autoBroadcast;')).enabled,false);
 await Promise.all([capture(win,'broadcast-main.png'),capture(detached,'broadcast-detached.png')]);
 checks.push('Real local/CNG broadcast IPC works manually with master off; two destinations give one Multi-Chat row; two identical runs give two rows; persisted visibility switch refreshes main and detached history');
 await run('await batto.closeDetached();');
 checks.push('Detached chat receives same widget trigger and viewer controls');
 const menu=await run("return [...document.querySelectorAll('#mainNav [data-view]')].filter(x=>x.getClientRects().length&&getComputedStyle(x).visibility!=='hidden').map(x=>({view:x.dataset.view,label:x.querySelector('span')?.textContent.trim()||x.textContent.trim()}));");
 assert.ok(menu.length>=20,'all primary menu items available');
 for(const item of menu){
  await run(`document.querySelector('#mainNav [data-view="${item.view}"]').click();`);
  await waitFor(()=>run(`const active=document.querySelectorAll('.view.active');if(active.length!==1||active[0].dataset.viewPanel!==${JSON.stringify(item.view)})return false;const card=active[0].querySelector('.module-card');return !card||card.children.length>0&&card.textContent.trim().length>5;`),'navigation content: '+item.label);
  await sleep(150);
  const page=await run(`const p=document.querySelector('.view.active'),title=p.querySelector('h1,h2')?.textContent.trim()||p.querySelector('img')?.alt||'',image=p.querySelector('img');return {view:p.dataset.viewPanel,title,textLength:p.textContent.trim().length,imageLoaded:!!image?.naturalWidth,selected:document.querySelector('#mainNav [data-view="${item.view}"]').classList.contains('active'),frameworkError:!!document.querySelector('vite-error-overlay,nextjs-portal [data-nextjs-dialog]')};`);
  assert.equal(page.view,item.view);assert.equal(page.selected,true);assert.ok(page.title.length>0,item.label+' has a title');assert.ok(page.textLength>5||page.imageLoaded,item.label+' is populated');assert.equal(page.frameworkError,false);assert.deepEqual(rendererErrors,[],item.label+' console health');
  navigationChecks.push({...item,...page});
 }
 checks.push('Every visible main menu item opens one populated active page with matching selection/title and no renderer errors ('+navigationChecks.length+' pages)');
 await run("setView('settings');");
 await waitFor(()=>run("return !!document.querySelector('#settingsModule [data-audio-save]')&&!document.querySelector('#settingsModule [data-audio-save]').disabled;"),'settings audio ready');
 await run("const host=document.querySelector('#settingsModule [data-audio-output-settings]');host.querySelector('[data-audio-mode]').value='app';host.querySelector('[data-audio-mode]').dispatchEvent(new Event('change'));host.querySelector('[data-audio-device]').value='default';host.querySelector('[data-audio-device]').dispatchEvent(new Event('change'));host.querySelector('[data-audio-volume]').value='37';host.querySelector('[data-audio-volume]').dispatchEvent(new Event('input'));await host.querySelector('[data-audio-save]').onclick();");
 assert.equal((await run('return (await batto.getState()).config.audioOutput;')).volume,0.37);
 await run("setView('dashboard');setView('settings');");
 await waitFor(()=>run("return document.querySelector('#settingsModule [data-audio-volume]')?.value==='37';"),'audio volume reload');
 assert.equal(await run("return document.querySelector('#settingsModule [data-audio-device]').value;"),'default');
 assert.equal(await run("return document.querySelector('#settingsModule [data-audio-mode]').value;"),'app');
 await capture(win,'settings-audio.png');
 checks.push('Audio settings save system output and 37 percent volume through real form/IPC and restore after navigation; no sound played');
 await run("setView('dashboard');");
 await capture(win,'dashboard.png');
 const persisted=new ConfigStore(profile).get();assert.equal(persisted.community.archive.enabled,false);assert.equal(persisted.events[0].name,'Follower – Entwurf');
 assert.equal(persisted.audioOutput.volume,0.37);
 checks.push('New store instance reloads saved event and archive settings');
 assert.deepEqual(rendererErrors,[]);
 finish(true);
}).catch(e=>finish(false,e));
