import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { pbkdf2Sync } from 'node:crypto';
import { KingstonCodec, KINGSTON_CODEC_LIMITS } from '../server/kingston-codec.mjs';

const require = createRequire(new URL('../../desktop/package.json', import.meta.url));
const Rijndael = require('rijndael-js');

// Fixed independent fixtures generated by the existing .NET compatibility
// codec during QA. These contain only public test text, random salt and IV.
// Production and this test suite do not execute that codec or contact FURY.
const vectors = [
  ['', 'Z7YPUa6zVxtllR2XFQMdTdcx0RFRX1dL6KogVnmnJB32mz1hMZD1/lzrL2mFkTjNpcf98nXtslI/r+9APloqX2MJF9iczBYk+7+86jBFH9kxU3VwGjyJBP+Toa/34D0t'],
  ['{"root":{"api":"get_dram_info","name":"Kingston üß 🐉"}}', 'jtw7Ac8zHbPcqiVus94i9pfXXBA3yiom46cpmnstcHLdZMIkUqduaFIOC2kyVUCZcv2AmpdSP4/QBWMpqie0roym5wBTt6/v+ud28NtJEJFLbxUtlL3p5TbOHMjpK1d6YYzMRxRsa9WRXLHUtsAiCqwlhSH8b6+U4/Xzj30iRnk='],
  ['12345678901234567890123456789012', '+dE6WU3df+CJQOnREQmTQbstNtz+bg6H7wvCqd+hgtRGOwPqql15n7Z6McwOzU4Z+KDnk6rJaSGonW3Af+GN0CR0ei3j1KVGt8nx2DOwZLJg09asA3oleSQlOez9DYsU+6mQr3zJlvl6DFMGN0SE/k0pBC6wdpHCfdVZZSm4teE='],
];

function codecFromPacket(packetText) {
  const packet = Buffer.from(packetText, 'base64');
  let sequence = 0;
  return new KingstonCodec({ Rijndael, randomBytes(size) {
    assert.equal(size, 32);
    return packet.subarray(sequence++ * 32, sequence * 32);
  } });
}
function packetFromPadded(padded) {
  const salt = Buffer.alloc(32, 0x24), iv = Buffer.alloc(32, 0x42);
  const key = pbkdf2Sync('3m23s45i599', salt, 1000, 32, 'sha1');
  const cipher = Buffer.from(new Rijndael(key, 'cbc').encrypt(padded, 256, iv));
  return Buffer.concat([salt, iv, cipher]).toString('base64');
}

test('pure Kingston codec decrypts independent .NET vectors and re-encrypts them byte for byte', async () => {
  for (const [plain, packet] of vectors) {
    const codec = codecFromPacket(packet);
    assert.equal(await codec.decrypt(packet), plain);
    assert.equal(await codec.encrypt(plain), packet);
    codec.close();
  }
});

test('wire format uses 32-byte salt, 32-byte IV and full PKCS7 block at aligned boundaries', async () => {
  const codec = new KingstonCodec({ Rijndael });
  for (const count of [0, 1, 31, 32, 33, 63, 64, 65]) {
    const plain = 'a'.repeat(count);
    const packet = await codec.encrypt(plain), bytes = Buffer.from(packet, 'base64');
    assert.equal(bytes.length, 64 + (Math.floor(count / 32) + 1) * 32);
    assert.equal(await codec.decrypt(packet), plain);
  }
});

test('entropy changes equal messages and Unicode, NUL and leading BOM survive exactly', async () => {
  const codec = new KingstonCodec();
  const plain = '\ufeffBatto 👾 üß 🐉\u0000尾';
  const first = await codec.encrypt(plain), second = await codec.encrypt(plain);
  assert.notEqual(first, second);
  assert.equal(await codec.decrypt(first), plain);
  assert.equal(await codec.decrypt(second), plain);
  assert.equal(codec.child, undefined);
});

test('malformed packet sizes and noncanonical Base64 are rejected before key derivation', async () => {
  let derivations = 0;
  const codec = new KingstonCodec({ Rijndael, deriveKey: async () => { derivations++; return Buffer.alloc(32); } });
  const good = vectors[0][1];
  const packets = ['', 'not encrypted', good + '\n', good.replace(/\+/g, '-'), good.slice(1), good + '=',
    Buffer.alloc(64).toString('base64'), Buffer.alloc(97).toString('base64'), 'a'.repeat(KINGSTON_CODEC_LIMITS.maximumTextBytes + 4)];
  for (const value of packets) await assert.rejects(codec.decrypt(value), { code: 'KINGSTON_INVALID_DATA' });
  assert.equal(derivations, 0);
  // Reject nonzero unused Base64 pad bits, although Buffer.from accepts them.
  const canonical = vectors[1][1], alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const index = canonical.length - 2;
  const altered = canonical.slice(0, index) + alphabet[alphabet.indexOf(canonical[index]) | 1] + '=';
  assert.notEqual(altered, canonical);
  await assert.rejects(codec.decrypt(altered), { code: 'KINGSTON_INVALID_DATA' });
  assert.equal(derivations, 0);
});

test('strict PKCS7 rejects zero, oversized and inconsistent padding instead of stripping bytes', async () => {
  const codec = new KingstonCodec({ Rijndael });
  for (const padded of [Buffer.alloc(32), Buffer.alloc(32, 33), Buffer.from([...Buffer.alloc(29, 65), 3, 2, 3])])
    await assert.rejects(codec.decrypt(packetFromPadded(padded)), { code: 'KINGSTON_INVALID_DATA' });
});

test('invalid UTF-8 is rejected after valid decryption and padding', async () => {
  const padded = Buffer.from([0xc0, 0xaf, ...Buffer.alloc(30, 30)]);
  await assert.rejects(new KingstonCodec({ Rijndael }).decrypt(packetFromPadded(padded)), { code: 'KINGSTON_INVALID_DATA' });
});

test('input types, unpaired UTF-16 surrogates, unsupported commands and invalid entropy fail uniformly', async () => {
  const codec = new KingstonCodec({ Rijndael });
  for (const value of [null, {}, 42, Buffer.from('text'), '\ud800', '\udc00', 'a'.repeat(KINGSTON_CODEC_LIMITS.maximumPlainBytes + 1)])
    await assert.rejects(codec.encrypt(value), { code: 'KINGSTON_INVALID_DATA' });
  await assert.rejects(codec.request('execute', 'text'), { code: 'KINGSTON_INVALID_DATA' });
  await assert.rejects(new KingstonCodec({ Rijndael, randomBytes: () => Buffer.alloc(31) }).encrypt('text'), { code: 'KINGSTON_INVALID_DATA' });
  await assert.rejects(new KingstonCodec({ Rijndael, randomBytes: () => Array(32).fill(-1) }).encrypt('text'), { code: 'KINGSTON_INVALID_DATA' });
});

test('largest supported plaintext remains inside existing transport bound and one more byte fails', async () => {
  const codec = new KingstonCodec({ Rijndael });
  const plain = 'x'.repeat(KINGSTON_CODEC_LIMITS.maximumPlainBytes);
  const packet = await codec.encrypt(plain);
  assert.equal(packet.length, KINGSTON_CODEC_LIMITS.maximumTextBytes);
  assert.equal(Buffer.from(packet, 'base64').length, KINGSTON_CODEC_LIMITS.maximumPacketBytes);
  assert.equal(await codec.decrypt(packet), plain);
  await assert.rejects(codec.encrypt(plain + 'x'), { code: 'KINGSTON_INVALID_DATA' });
});

test('close cancels in-flight derivation while a later reconnect can use the same codec', async () => {
  let entered, release;
  const enteredPromise = new Promise(resolve => entered = resolve), gate = new Promise(resolve => release = resolve);
  const codec = new KingstonCodec({ Rijndael, deriveKey: async (...args) => {
    entered(); await gate; return pbkdf2Sync(...args);
  } });
  const pending = codec.encrypt('pending');
  await enteredPromise; codec.close(); release();
  await assert.rejects(pending, { code: 'KINGSTON_DISCONNECTED' });
  const packet = await codec.encrypt('reconnected');
  assert.equal(await codec.decrypt(packet), 'reconnected');
});

test('cipher failures are sanitized and a missing integrated dependency has a specific error', async () => {
  class BrokenCipher { encrypt() { throw Error('private payload must not leak'); } }
  await assert.rejects(new KingstonCodec({ Rijndael: BrokenCipher }).encrypt('text'), error =>
    error.code === 'KINGSTON_INVALID_DATA' && !error.message.includes('private payload'));
  await assert.rejects(new KingstonCodec({ Rijndael: {} }).encrypt('text'), { code: 'KINGSTON_CODEC_UNAVAILABLE' });
});
