'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {BattoHardware}=require('../src/services/batto-hardware.cjs');
function fixture(reply){const root=fs.mkdtempSync(path.join(os.tmpdir(),'batto-hardware-'));fs.writeFileSync(path.join(root,'Batto.Hardware.dll'),'test');let freed=0,loads=0;const pointers=new Map();let next=0;const component={invoke:{async:(input,size,out,length,done)=>{const request=JSON.parse(input.toString());Promise.resolve().then(()=>reply(request)).then(value=>{const data=Buffer.from(JSON.stringify(value)),pointer=++next;pointers.set(pointer,data);out[0]=pointer;length[0]=data.length;done(null,0);},error=>done(error));}},ffi:{decode:pointer=>pointers.get(pointer)},free:pointer=>{freed++;pointers.delete(pointer);}};return {root,hardware:new BattoHardware({root,platform:'win32',load:()=>{loads++;return component;}}),get freed(){return freed;},get loads(){return loads;},dispose(){fs.rmSync(root,{recursive:true,force:true});}};}
const ok=request=>({requestId:request.requestId,ok:true,result:{command:request.command}});
test('direct requests load once and free every returned native allocation',async()=>{const f=fixture(ok);try{for(let i=0;i<5;i++)assert.equal((await f.hardware.request('wireless','status')).command,'status');assert.equal(f.loads,1);assert.equal(f.freed,5);assert.equal(f.hardware.status.pending,0);assert.equal(f.hardware.status.processId,process.pid);}finally{f.dispose();}});
test('native failures keep their actual error code and free native memory',async()=>{const f=fixture(request=>({requestId:request.requestId,ok:false,error:{code:'WIRELESS_ACCESS_DENIED',message:'blocked'}}));try{await assert.rejects(f.hardware.request('wireless','enumerate'),error=>error.code==='WIRELESS_ACCESS_DENIED'&&error.message==='blocked');assert.equal(f.freed,1);}finally{f.dispose();}});
test('invalid reply ownership is rejected and freed',async()=>{const f=fixture(()=>({requestId:999,ok:true,result:{}}));try{await assert.rejects(f.hardware.request('fan','status'),/zugeordnet/);assert.equal(f.freed,1);}finally{f.dispose();}});
test('a long wireless operation cannot delay a fan heartbeat',async()=>{let finish;const waiting=new Promise(resolve=>finish=resolve);const f=fixture(async request=>{if(request.provider==='wireless')await waiting;return ok(request);});try{const wireless=f.hardware.request('wireless','enumerate');await Promise.resolve();const fan=await f.hardware.request('fan','heartbeat');assert.equal(fan.command,'heartbeat');finish();await wireless;}finally{finish?.();f.dispose();}});
test('failed close attempts every release and retains the actual lease for retry',async()=>{
 const commands=[];let failing=true;const state={active:true,retryRequired:true,remaining:['LConnectService']};
 const f=fixture(request=>{commands.push([request.provider,request.command]);return failing&&request.command==='close'&&request.provider==='wireless'?{requestId:request.requestId,ok:false,result:state,error:{message:'release failed'}}:ok(request);});
 try{await f.hardware.request('wireless','status');await f.hardware.request('fan','status');await assert.rejects(f.hardware.close(),error=>error.message==='release failed'&&error.state.active===true);assert(commands.some(([p,c])=>p==='fan'&&c==='shutdown'));assert.equal(f.hardware.closed,false);failing=false;await f.hardware.close();assert.equal(f.hardware.closed,true);await assert.rejects(f.hardware.request('fan','status'),/geschlossen/);}finally{f.dispose();}
});
