const test=require('node:test'),assert=require('node:assert/strict'),os=require('node:os'),fs=require('node:fs'),path=require('node:path');
const {JarvisCore,AlertEngine,allowedChat,cleanSettings}=require('../src/services/jarvis-core.cjs');
const now=()=>Date.now();
function sensor(id,name,unit,value,device='NVIDIA GPU'){return {id,name,unit,value,device,fresh:true,updatedUtc:new Date().toISOString()};}
function setup(extra={}){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'batto-jarvis-test-'));const said=[],switched=[];const core=new JarvisCore({directory,getSensors:()=>[sensor('t','GPU-Temperatur','°C',40),sensor('c','CPU-Auslastung','%',15,'CPU'),sensor('p1','12V-2x6 Pin 1 Strom','A',3.1),sensor('p2','12V-2x6 Pin 2 Strom','A',3.2)],obs:{scenes:async()=>['Spiel','Bin gleich zurück'],setScene:async s=>switched.push(s)},speak:t=>said.push(t),...extra});return{core,said,switched,directory};}
test('moderator-only default rejects normal chat and matches platform role',()=>{const s=cleanSettings({});assert(!allowedChat({platform:'twitch',message:'Hallo',role:'viewer'},s));assert(allowedChat({platform:'twitch',message:'Hallo',badges:['moderator']},s));assert(!allowedChat({platform:'other',message:'Hallo',role:'moderator'},s));});
test('allowlist uses platform user ID, never display name',()=>{const s=cleanSettings({chatMode:'allowlist',chatAllowlist:['twitch:123']});assert(allowedChat({platform:'twitch',userId:'123',message:'Hi'},s));assert(!allowedChat({platform:'youtube',userId:'123',message:'Hi'},s));assert(!allowedChat({platform:'twitch',username:'123',message:'Hi'},s));});
test('reading chat never executes voice commands',()=>{const{core,said,switched}=setup();core.onChat([{id:'1',platform:'twitch',role:'moderator',username:'Mod',message:'Jarvis Pause'}]);assert.equal(said.length,1);assert.equal(switched.length,0);core.onChat([{id:'1',platform:'twitch',role:'moderator',message:'Jarvis Pause'}]);assert.equal(said.length,1);});
test('asked GPU temperature reports only that measurement',async()=>{const{core}=setup();const r=await core.execute('Jarvis wie warm ist die Grafikkarte');assert(r.text.includes('40 Grad Celsius'));assert(!r.text.includes('15'));assert(!r.text.includes('Ampere'));});
test('requested pin never mixes voltage and current',async()=>{const{core}=setup();const a=await core.execute('Jarvis Stromstärke Pin 2');assert(a.text.includes('3,2 Ampere'));assert(!a.text.includes('3,1'));const v=await core.execute('Spannung Pin 2');assert(v.text.includes('keinen passenden'));});
test('GPU core voltage is never substituted for a connector measurement',async()=>{const{core}=setup({getSensors:()=>[sensor('core','GPU Spannung','V',.95)]});for(const question of ['GPU Spannung am Anschluss','Spannung am 16-Pin der Grafikkarte','GPU 12V-2x6 Spannung']){const r=await core.execute(question);assert.match(r.text,/keinen passenden/);assert(!r.text.includes('0,95'));}});
test('plain Strom request selects amperes only',async()=>{const{core}=setup({getSensors:()=>[sensor('a','GPU Pin 1 current','A',6),sensor('v','GPU Pin 1 voltage','V',12)]});const r=await core.execute('Strom an Pin 1');assert.match(r.text,/6 Ampere/);assert(!r.text.includes('Volt'));});
test('stale data is not spoken as current',async()=>{const{core}=setup({getSensors:()=>[{...sensor('t','GPU-Temperatur','°C',90),updatedUtc:new Date(Date.now()-60000).toISOString()}]});const r=await core.execute('GPU Temperatur');assert(r.text.includes('keine aktuellen'));assert(!r.text.includes('90'));});
test('OBS confirms requested pause scene before success',async()=>{const{core,switched}=setup();const r=await core.execute('Jarvis Pause');assert.deepEqual(switched,['Bin gleich zurück']);assert(r.ok);assert(core.memory.some(m=>m.intent==='scene:Bin gleich zurück'));});
test('failed OBS switch does not report success or learn success',async()=>{const{core}=setup({obs:{scenes:async()=>['Pause'],setScene:async()=>{throw Error('OBS getrennt')}}});const r=await core.execute('Pause');assert.equal(r.ok,false);assert.equal(core.memory.length,0);});
test('sensor aliases persist and only requested sensor is read',async()=>{const{core,directory}=setup();core.update({sensorRules:{p1:{alias:'Mein Stecker',readable:true}}});const r=await core.execute('Mein Stecker');assert(r.text.includes('3,1 Ampere'));const saved=JSON.parse(fs.readFileSync(path.join(directory,'jarvis-settings.json')));assert.equal(saved.sensorRules.p1.alias,'Mein Stecker');});
test('alert uses hysteresis and requires reset before another crossing',()=>{const e=new AlertEngine();const rule=cleanSettings({sensorRules:{x:{alert:true,threshold:80,hysteresis:3,cooldown:10}}}).sensorRules;let time=Date.now();const read=v=>e.evaluate([{...sensor('x','GPU Temperatur','°C',v),updatedUtc:new Date(time).toISOString()}],rule,time);assert.equal(read(70).length,0);assert.equal(read(81).length,1);time+=20000;assert.equal(read(82).length,0);read(76);assert.equal(read(81).length,1);});
test('change alerts establish baseline and ignore missing sensors',()=>{const e=new AlertEngine();const rules=cleanSettings({sensorRules:{x:{alert:true,mode:'change',delta:.5,cooldown:10}}}).sensorRules;const one=sensor('x','Pin 1','A',1);assert.equal(e.evaluate([one],rules).length,0);assert.equal(e.evaluate([{...one,value:1.6}],rules).length,1);assert.equal(e.evaluate([{...one,fresh:false,value:99}],rules).length,0);});
test('settings reject non-finite thresholds and unknown modes',()=>{const s=cleanSettings({aiPort:NaN,chatMode:'unsafe',sensorRules:{x:{threshold:Infinity,mode:'execute'}}});assert.equal(s.aiPort,11435);assert.equal(s.chatMode,'moderators');assert.equal(s.sensorRules.x.threshold,80);assert.equal(s.sensorRules.x.mode,'above');});
