'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {JarvisCore,cleanSettings}=require('../src/services/jarvis-core.cjs');
const {cleanVoice,identity}=require('../src/services/jarvis-customization.cjs');
const catalog={actions:[{id:'navigate',choices:[{id:'rgb',name:'RGB-Steuerung'},{id:'dashboard',name:'Multi-Chat'}]},{id:'scene',choices:[{id:'Pause',name:'Pause'},{id:'Spiel',name:'Spiel'}]},{id:'broadcast',name:'Broadcast',choices:[{id:'fictional',name:'Beispiel'}]}],sceneMode:'suite'};
function core(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'batto-customization-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const calls=[],speech=[];let now=1000;const jarvis=new JarvisCore({directory,getCommandCatalog:()=>catalog,control:async action=>{calls.push(action);return {ok:true};},speak:(text,options)=>speech.push({text,options}),clock:()=>now});return {jarvis,calls,speech,directory,advance:()=>now+=46000};}
test('own phrase executes only an available canonical command and survives restart',async t=>{const x=core(t);x.jarvis.update({commandCustomization:{aliases:[{id:'test',phrase:'Lichtzentrale',target:'Öffne RGB-Steuerung',enabled:true}]}});assert.equal((await x.jarvis.execute('Jarvis, Lichtzentrale')).ok,true);assert.deepEqual(x.calls,[{action:'navigate',target:'rgb'}]);const reloaded=new JarvisCore({directory:x.directory,getCommandCatalog:()=>catalog});assert.equal(reloaded.settings.commandCustomization.aliases[0].phrase,'Lichtzentrale');});
test('disabled action blocks another recognized phrase and its aliases',async t=>{const x=core(t),entry=x.jarvis.commandExamples().find(item=>item.expectedAction?.action==='scene'&&item.expectedAction.target==='Pause');assert.ok(entry);x.jarvis.update({commandCustomization:{disabled:[entry.id],aliases:[{id:'a',phrase:'Pause bitte jetzt',target:entry.phrase}]}});assert.equal((await x.jarvis.execute('Wechsle zur Pause')).ok,false);assert.equal((await x.jarvis.execute('Pause bitte jetzt')).ok,false);assert.equal(x.calls.length,0);});
test('conflicting custom aliases and collisions with built-ins ask for clarification',async t=>{const x=core(t);x.jarvis.update({commandCustomization:{aliases:[{id:'a',phrase:'Mein Modus',target:'Öffne RGB-Steuerung'},{id:'b',phrase:'Mein Modus',target:'Öffne Multi-Chat'},{id:'c',phrase:'Öffne RGB-Steuerung',target:'Öffne Multi-Chat'}]}});for(const phrase of ['Mein Modus','Öffne RGB-Steuerung']){const result=await x.jarvis.execute(phrase);assert.equal(result.ok,false);assert.equal(result.kind,'clarification');}assert.equal(x.calls.length,0);});
test('confirmation executes once, expires, and stopping discards it',async t=>{const x=core(t);x.jarvis.update({commandCustomization:{confirmation:'external'}});const phrase=x.jarvis.commandExamples().find(item=>item.expectedAction?.action==='broadcast').phrase;await x.jarvis.execute(phrase);assert.equal(x.calls.length,0);await x.jarvis.execute('Bestätigen');assert.equal(x.calls.length,1);assert.equal((await x.jarvis.execute('Bestätigen')).ok,false);await x.jarvis.execute(phrase);x.advance();assert.equal((await x.jarvis.execute('Bestätigen')).ok,false);await x.jarvis.execute(phrase);await x.jarvis.execute('Stopp');assert.equal((await x.jarvis.execute('Bestätigen')).ok,false);assert.equal(x.calls.length,1);});
test('voice draft test does not save settings or enable microphone',t=>{const x=core(t),before=structuredClone(x.jarvis.settings);x.jarvis.previewVoice({text:'Eigener Testtext.',speechRate:140,speechVolume:40,voiceCustomization:{style:'natural',pauseMs:300,dictionary:[{word:'CNG',spoken:'Ce En Ge'}]}});assert.deepEqual(x.jarvis.settings,before);assert.equal(x.speech[0].options.voiceSettings.speechRate,140);assert.equal(x.speech[0].options.voiceSettings.voiceCustomization.dictionary[0].spoken,'Ce En Ge');assert.equal(fs.existsSync(path.join(x.directory,'jarvis-settings.json')),false);assert.equal(x.jarvis.settings.microphoneEnabled,false);});
test('customization validation bounds fields and stable identity ignores key order',()=>{assert.equal(cleanVoice({pauseMs:1e6}).pauseMs,1500);assert.equal(cleanSettings({voiceCustomization:null,commandCustomization:null}).voiceCustomization.style,'synthetic');assert.equal(identity({kind:'action',action:{target:'Pause',action:'scene'}}),identity({kind:'action',action:{action:'scene',target:'Pause'}}));});
