'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{EventEmitter}=require('node:events');
const {StreamerBotLocal,executable,localServer}=require('../src/services/streamerbot-local.cjs');
function fixture(t,settings={autoStart:true,address:'127.0.0.1',port:8080,endpoint:'/',enableAuth:true,authPassword:'must-never-leak'}){const home=fs.mkdtempSync(path.join(os.tmpdir(),'batto-bot-')),root=path.join(home,'Desktop','Streamer.bot-x64-1.0.7');fs.mkdirSync(path.join(root,'data'),{recursive:true});const file=path.join(root,'Streamer.bot.exe');fs.writeFileSync(file,Buffer.alloc(2048));fs.writeFileSync(path.join(root,'data','settings.json'),JSON.stringify({websockets:settings}));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));return {home,file};}
test('discovers supplied desktop install without executing it or exposing password',async t=>{const f=fixture(t),bot=new StreamerBotLocal({...f,getConfig:()=>({}),listProcesses:async()=>[{path:f.file,pid:7}]});const result=await bot.discover();assert.equal(result.installations.length,1);assert.equal(result.installations[0].running,true);assert.equal(result.installations[0].server.url,'ws://127.0.0.1:8080/');assert.equal(result.installations[0].server.requiresPassword,true);assert(!JSON.stringify(result).includes('must-never-leak'));});
test('setup preserves provider and configured automation choices',async t=>{const f=fixture(t);let config={url:'ws://localhost:9000/',tipProvider:'streamlabs',tiktokEvents:'bridge',tiktokActionId:'keep',autoConnect:true};const bot=new StreamerBotLocal({...f,getConfig:()=>config,saveConfig:patch=>{config=patch.streamerbot;},listProcesses:async()=>[]});await bot.setup();assert.equal(config.executablePath,f.file);assert.equal(config.url,'ws://127.0.0.1:8080/');assert.equal(config.tiktokActionId,'keep');assert.equal(config.tiktokEvents,'bridge');});
test('does not replace url with a remote or malformed local config',t=>{for(const setting of [{address:'elsewhere',port:8080},{address:'127.0.0.1',port:1},{address:'127.0.0.1',port:8080,endpoint:'//remote'},{address:'127.0.0.1',port:8080,endpoint:'/bad?secret=yes'}]){const f=fixture(t,setting);assert.equal(localServer(f.file),null);}});
test('rejects arbitrary binaries and nonexistent selections',t=>{const f=fixture(t);assert.throws(()=>executable(path.join(path.dirname(f.file),'Other.exe')),/Streamer.bot.exe/);assert.throws(()=>executable('Streamer.bot.exe'),/auswählen/);});
test('start avoids duplicate instance and never closes existing bot',async t=>{const f=fixture(t);let launches=0;const bot=new StreamerBotLocal({...f,getConfig:()=>({executablePath:f.file}),listProcesses:async()=>[{path:f.file}],launch:()=>{launches++;}});assert.deepEqual(await bot.start(),{alreadyRunning:true,started:false});assert.equal(launches,0);});
test('concurrent start shares one process launch, with hidden window and literal arguments',async t=>{const f=fixture(t);let launches=0;const bot=new StreamerBotLocal({...f,getConfig:()=>({executablePath:f.file}),listProcesses:async()=>[],launch:(file,args,options)=>{launches++;assert.equal(file,f.file);assert.deepEqual(args,[]);assert.equal(options.shell,false);assert.equal(options.windowsHide,true);const child=new EventEmitter();child.unref=()=>{};setImmediate(()=>child.emit('spawn'));return child;}});await Promise.all([bot.start(),bot.start()]);assert.equal(launches,1);});
test('process inventory failure blocks launch rather than opening duplicate',async t=>{const f=fixture(t),bot=new StreamerBotLocal({...f,getConfig:()=>({executablePath:f.file}),listProcesses:async()=>{throw Error('denied');},launch:()=>assert.fail('must not launch')});await assert.rejects(bot.start(),/Instanzen/);});
test('spawn failure is visible and subsequent retry remains possible',async t=>{const f=fixture(t);let attempts=0;const bot=new StreamerBotLocal({...f,getConfig:()=>({executablePath:f.file}),listProcesses:async()=>[],launch:()=>{attempts++;const child=new EventEmitter();child.unref=()=>{};setImmediate(()=>child.emit(attempts===1?'error':'spawn',Error('fail')));return child;}});await assert.rejects(bot.start(),/gestartet/);assert.equal((await bot.start()).started,true);});
