'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {defaults,validate}=require('../src/dual-stream/config.cjs');
const {DualStream}=require('../src/dual-stream/service.cjs');
const {JarvisCore,cleanSettings}=require('../src/services/jarvis-core.cjs');
test('old portrait factory layout migrates, custom arrangement stays intact',()=>{const old=defaults();delete old.layoutRevision;old.layouts.tiktok=[{source:'game',x:0,y:.22,width:1,height:.56,fit:'contain',visible:true},{source:'camera',x:.53,y:.02,width:.44,height:.19,fit:'contain',visible:true}];assert.deepEqual(validate(old).layouts.tiktok,defaults().layouts.tiktok);old.layouts.tiktok[1].x=.5;assert.equal(validate(old).layouts.tiktok[1].x,.5);assert.equal(validate(old).layoutRevision,2);});
test('legacy personal address and empty address stay silent without leading comma',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'batto150-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));fs.writeFileSync(path.join(directory,'jarvis-settings.json'),JSON.stringify({address:'Sir Crazy',voiceEnabled:false}));const j=new JarvisCore({directory});assert.equal(j.settings.address,'');assert.equal(cleanSettings({address:''}).address,'');assert.equal(cleanSettings({address:'Sir'}).address,'Sir');const r=await j.execute('Hilfe');assert(!/Crazy|^,/.test(r.text));});
test('keyless starts use raw camera output, keep idle service alive and never imply public live',async t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'batto150-'));const d=new DualStream({directory,executable:'missing',safeStorage:{}});t.after(async()=>{await d.release();fs.rmSync(directory,{recursive:true,force:true});});const calls=[];d.state={prepared:true,outputs:{},virtualCameras:{tiktok:{ready:true},twitch:{ready:true}}};d.native={request:async(k,v)=>{calls.push([k,v]);if(k==='camera-start')d.state.outputs[v.platform]={state:'camera'};return d.state;},close:async()=>{}};await d.start('both');assert.deepEqual(calls,[['camera-start',{platform:'tiktok'}],['camera-start',{platform:'twitch'}]]);assert(d.running());assert(!d.live());assert.equal((await d.obs('GetStreamStatus')).outputActive,false);await assert.rejects(d.save(defaults()),/stoppen/);});
test('virtual camera settings never capture audio or their own output',()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'batto150-'));try{const d=new DualStream({directory,executable:'missing',safeStorage:{}});d.config.sources.microphone.enabled=true;assert(!d.nativeConfig().sources.microphone.enabled);assert(d.config.sources.microphone.enabled);d.config.sources.camera={enabled:true,target:'{27B05C2D-93DC-474A-A5DA-9BBA34CB2A9C}',name:'Batto TikTok'};assert.throws(()=>d.nativeConfig(),/echte Kamera/);}finally{fs.rmSync(directory,{recursive:true,force:true});}});
