'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {importStreamDeckProfiles}=require('../src/services/touch-profiles.cjs');
const {TouchPluginHost,resolveNodeExecutable}=require('../src/services/touch-plugin-host.cjs');
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX5cAAAAASUVORK5CYII=';
function crc32(data){let crc=0xffffffff;for(const byte of data){crc^=byte;for(let bit=0;bit<8;bit++)crc=crc&1?(crc>>>1)^0xedb88320:crc>>>1;}return(crc^0xffffffff)>>>0;}
function zip(entries){let offset=0;const local=[],central=[];for(const entry of entries){const name=Buffer.from(entry.name),data=Buffer.from(entry.data||''),crc=crc32(data),a=Buffer.alloc(30),b=Buffer.alloc(46);a.writeUInt32LE(0x04034b50);a.writeUInt16LE(20,4);a.writeUInt16LE(0x800,6);a.writeUInt32LE(crc,14);a.writeUInt32LE(data.length,18);a.writeUInt32LE(data.length,22);a.writeUInt16LE(name.length,26);b.writeUInt32LE(0x02014b50);b.writeUInt16LE(0x314,4);b.writeUInt16LE(20,6);b.writeUInt16LE(0x800,8);b.writeUInt32LE(crc,16);b.writeUInt32LE(data.length,20);b.writeUInt32LE(data.length,24);b.writeUInt16LE(name.length,28);b.writeUInt32LE(entry.attributes??0,38);b.writeUInt32LE(offset,42);local.push(a,name,data);central.push(b,name);offset+=a.length+name.length+data.length;}const center=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(center.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,center,end]);}
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'batto-profile-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return directory;}
const root='Profiles/source.sdProfile',entry=(name,value)=>({name:root+'/'+name,data:JSON.stringify(value)});
function plugin(settings={token:'PRIVATE_PROFILE_TOKEN'}){return {UUID:'bot.example.action',Plugin:{UUID:'bot.example'},Name:'Bot',Settings:settings,States:[{Title:'Bot auslösen',Image:'Images/key.png'}]};}
function profile({actions={'0,0':plugin(),'2,3':{UUID:'com.elgato.streamdeck.profile.openchild',Name:'Ordner',Settings:{ProfileUUID:'child'}}},child={'1,0':plugin()},pages={Default:'empty',Current:'missing',Pages:['main']},extra=[]}={}){return zip([entry('manifest.json',{Name:'Mein importiertes Deck',Pages:pages}),entry('Profiles/main/manifest.json',{Controllers:[{Type:'Keypad',Actions:actions},{Type:'Encoder',Actions:{'0,0':plugin()}}]}),entry('Profiles/child/manifest.json',{Controllers:[{Type:'Keypad',Actions:child}]}),entry('Profiles/empty/manifest.json',{Controllers:[{Type:'Keypad',Actions:null}]}),{name:root+'/Profiles/main/Images/key.png',data:Buffer.from(PNG.split(',')[1],'base64')},{name:root+'/Profiles/child/Images/key.png',data:Buffer.from(PNG.split(',')[1],'base64')},...extra]);}
const installed={getPlugin:id=>{if(id!=='bot.example')throw Error('missing');return {supported:true,actions:[{id:'bot.example.action',supported:true}]};},convert:async()=>PNG};
test('Stream Deck import preserves coordinates, folders and images with fresh IDs and isolated private plugin settings',async t=>{
 const directory=fixture(t),file=path.join(directory,'profile.streamDeckProfile');fs.writeFileSync(file,profile());const first=await importStreamDeckProfiles(file,{packages:installed}),second=await importStreamDeckProfiles(file,{packages:installed});
 assert.equal(first.profiles.length,1);const p=first.profiles[0];assert.equal(p.columns,3);assert.equal(p.rows,4);assert.equal(p.buttons.length,12);assert.equal(p.buttons[0].title,'Bot auslösen');assert.equal(p.buttons[0].icon,PNG);assert.equal(p.buttons[11].type,'folder');assert.equal(p.buttons[11].buttons[1].actionId,'bot.example.action');
 assert.notEqual(p.id,second.profiles[0].id);assert.notEqual(p.buttons[0].id,second.profiles[0].buttons[0].id);assert.equal(first.settingsByButton[p.buttons[0].id].settings.token,'PRIVATE_PROFILE_TOKEN');assert(!JSON.stringify(first.profiles).includes('PRIVATE_PROFILE_TOKEN'));assert(first.warnings.some(w=>w.includes('Drehregler')));assert(first.warnings.some(w=>w.includes('zuletzt')));assert(first.warnings.some(w=>w.includes('Leere Startseiten')));assert(!JSON.stringify(first.warnings).includes('PRIVATE_PROFILE_TOKEN'));
});
test('Windows profiles inside a wrapper ZIP are preferred over duplicated macOS variants',async t=>{
 const directory=fixture(t),file=path.join(directory,'bundle.zip');fs.writeFileSync(file,zip([{name:'Bundle/Windows/deck.streamDeckProfile',data:profile()},{name:'Bundle/MacOS/deck.streamDeckProfile',data:profile()}]));const result=await importStreamDeckProfiles(file,{packages:installed});assert.equal(result.profiles.length,1);assert(result.warnings.some(w=>w.includes('macOS')));
});
test('missing plugin and native Elgato actions stay visible and produce explicit non-executable warnings',async t=>{
 const directory=fixture(t),file=path.join(directory,'profile.streamDeckProfile');fs.writeFileSync(file,profile({actions:{'0,0':plugin(),'1,0':{UUID:'com.elgato.streamdeck.system.hotkey',Plugin:{UUID:'com.elgato.streamdeck.system.hotkey'},Name:'Hotkey',Settings:{Hotkeys:[{key:12}]}}}}));const result=await importStreamDeckProfiles(file);assert.equal(result.profiles[0].buttons[0].pluginId,'bot.example');assert.equal(result.profiles[0].buttons[1].actionId,'com.elgato.streamdeck.system.hotkey');assert(result.warnings.some(w=>w.includes('nicht ausführbar')));assert(result.warnings.some(w=>w.includes('originale Stream-Deck-Laufzeit')));
});
test('malformed coordinates, folder cycles, traversal, symlinks, duplicate paths and protected manifests fail without modifying inputs',async t=>{
 const directory=fixture(t);const variants=[profile({actions:{'8,0':plugin()}}),profile({child:{'0,0':{UUID:'com.elgato.streamdeck.profile.openchild',Settings:{ProfileUUID:'main'}}}}),profile({extra:[{name:'../escape',data:'bad'}]}),profile({extra:[{name:root+'/link',data:'../outside',attributes:(0xa000<<16)>>>0}]}),profile({extra:[{name:root+'/Profiles/main/images/KEY.PNG',data:'duplicate'}]}),zip([{name:root+'/manifest.json',data:'ELGATOprotected'}])];
 for(let i=0;i<variants.length;i++){const file=path.join(directory,i+'.streamDeckProfile');fs.writeFileSync(file,variants[i]);await assert.rejects(importStreamDeckProfiles(file));assert(fs.readFileSync(file).equals(variants[i]));}assert(!fs.existsSync(path.join(directory,'escape')));
});
test('profile settings import is atomic, preserves existing settings, rejects collisions and starts no plugin runtime',async t=>{
 const directory=fixture(t),host=new TouchPluginHost({packages:{directory},launchProcess(){throw Error('must not start');}});t.after(()=>host.close());host.stored.buttons.previous={pluginId:'old',actionId:'old.key',settings:{keep:true}};
 assert.deepEqual(host.importSettingsByButton({fresh:{pluginId:'bot.example',actionId:'bot.example.action',settings:{token:'PRIVATE_PROFILE_TOKEN'}}}),{count:1});assert.equal(host.stored.buttons.fresh.settings.token,'PRIVATE_PROFILE_TOKEN');assert.equal(host.stored.buttons.previous.settings.keep,true);assert.equal(host.server,null);assert.equal(host.plugins.size,0);
 const before=JSON.stringify(host.stored);for(const invalid of [{valid:{pluginId:'bot',actionId:'bot.action',settings:{}},bad:{pluginId:'bad/id',actionId:'bad',settings:{}}},{previous:{pluginId:'bot',actionId:'bot.action',settings:{}}},{bad:{pluginId:'bot',actionId:'bot.action',settings:{tooLarge:'x'.repeat(131073)}}},JSON.parse('{"__proto__":{"pluginId":"bot","actionId":"bot.key","settings":{}}}')]){assert.throws(()=>host.importSettingsByButton(invalid));assert.equal(JSON.stringify(host.stored),before);}
});
test('Node plugin selects its declared major runtime without pretending that a different major matches',t=>{
 const directory=fixture(t),plugin={manifest:{Nodejs:{Version:'20'}}};for(const version of ['20.19.0','20.20.0','24.13.1']){fs.mkdirSync(path.join(directory,version));fs.writeFileSync(path.join(directory,version,'node.exe'),'fixture only');}
 assert.equal(resolveNodeExecutable(plugin,{nodeExecutable:'current-node',nodeVersion:'24.19.0',nodeRuntimeDirectory:directory}),path.join(directory,'20.20.0','node.exe'));assert.equal(resolveNodeExecutable(plugin,{nodeExecutable:'current-node20',nodeVersion:'20.19.0',nodeRuntimeDirectory:null}),'current-node20');assert.throws(()=>resolveNodeExecutable(plugin,{nodeExecutable:'current-node',nodeVersion:'24.19.0',nodeRuntimeDirectory:null}),/Node.js 20/);assert.throws(()=>resolveNodeExecutable({manifest:{Nodejs:{Version:'../../evil'}}}),/unbekannte/);
});
