'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{PassThrough,Writable}=require('node:stream'),{TouchAudio}=require('../src/services/touch-audio.cjs');
const pause=ms=>new Promise(r=>setTimeout(r,ms)),target=(id='master',volume=40)=>({id,name:id,volume,muted:false,available:true});
function fake(handler){const children=[],requests=[];function spawn(file,args,options){const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.killed=false;child.kill=()=>{child.killed=true;child.emit('exit',0);};child.stdin=new Writable({write(data,_enc,cb){const req=JSON.parse(data);requests.push(req);Promise.resolve().then(()=>handler(req,child,children.length)).then(value=>{if(value)child.stdout.write(JSON.stringify({id:req.id,...value})+'\n');}).catch(e=>child.emit('error',e));cb();}});children.push(child);child.options=options;return child;}return {spawn,children,requests};}
test('native helper remains lazy and Jarvis-only controls never launch it',async()=>{let calls=0,current={volume:61,muted:false};const a=new TouchAudio({spawn:()=>{calls++;throw Error('not needed');},getJarvis:()=>current,setJarvis:patch=>Object.assign(current,patch)});assert.equal(a.child,null);assert.equal((await a.state(['jarvis'])).jarvis.volume,61);assert.equal((await a.set('jarvis',{volume:23})).volume,23);assert.equal((await a.set('jarvis',{muted:true})).muted,true);assert.equal(calls,0);a.close();});
test('concurrent reads share one hidden helper request and cache is isolated from consumers',async()=>{let now=0;const f=fake(async()=>({ok:true,targets:[target(),target('app:test',30)]})),a=new TouchAudio({spawn:f.spawn,now:()=>now});try{const [list,read]=await Promise.all([a.targets(),a.state(['master','app:test'])]);assert.equal(f.requests.length,1);assert.equal(f.children[0].options.windowsHide,true);assert.equal(read['app:test'].volume,30);list[0].volume=99;assert.equal((await a.state(['master'])).master.volume,40);now=1001;await a.targets();assert.equal(f.requests.length,2);}finally{a.close();}});
test('offline app is unavailable and a write never falls back to master',async()=>{const f=fake(req=>req.command==='targets'?{ok:true,targets:[target()]}:{ok:false,error:'App ist nicht verfügbar'}),a=new TouchAudio({spawn:f.spawn});try{const read=await a.state(['app:offline']);assert.deepEqual(read['app:offline'],{id:'app:offline',name:'Zurzeit nicht verfügbar',volume:null,muted:false,available:false});await assert.rejects(a.set('app:offline',{volume:40}),/nicht verfügbar/);assert.equal(f.requests.at(-1).target,'app:offline');assert.equal(f.requests.filter(x=>x.command==='set'&&x.target==='master').length,0);}finally{a.close();}});
test('volume bounds and malformed targets are rejected before spawning',async()=>{let spawned=0;const a=new TouchAudio({spawn:()=>{spawned++;throw Error('bad');}});for(const value of [-1,101,NaN,Infinity,'40'])await assert.rejects(a.set('master',{volume:value}),/zwischen/);for(const patch of [{},{muted:'yes'},{volume:4,muted:true},{volume:4,extra:true}])await assert.rejects(a.set('master',patch));await assert.rejects(a.set('app:',{volume:40}));await assert.rejects(a.state(['master\n']));assert.equal(spawned,0);a.close();});
test('slider writes stay in order and invalidate read cache',async()=>{let actual=40;const f=fake(async req=>{if(req.command==='targets')return {ok:true,targets:[target('master',actual)]};await pause(req.volume===20?20:1);actual=req.volume;return {ok:true,value:target('master',actual)};}),a=new TouchAudio({spawn:f.spawn});try{await a.targets();const values=await Promise.all([a.set('master',{volume:20}),a.set('master',{volume:80})]);assert.deepEqual(values.map(x=>x.volume),[20,80]);assert.equal((await a.state(['master'])).master.volume,80);assert.equal(f.requests.filter(x=>x.command==='targets').length,2);}finally{a.close();}});
test('idle helper exits and a later request can restart it',async()=>{let now=0;const f=fake(()=>({ok:true,targets:[target()]})),a=new TouchAudio({spawn:f.spawn,idleMs:20,now:()=>now});try{await a.targets();await pause(45);assert.equal(f.children[0].killed,true);assert.equal(a.child,null);now=1001;await a.targets();assert.equal(f.children.length,2);}finally{a.close();}});
test('broken native read reconnects once while writes are never blindly retried',async()=>{let failed=false;const f=fake((req,child)=>{if(!failed){failed=true;child.emit('exit',1);return null;}return {ok:true,targets:[target()]};}),a=new TouchAudio({spawn:f.spawn});try{assert.equal((await a.targets())[0].available,true);assert.equal(f.children.length,2);}finally{a.close();}const g=fake((_req,child)=>{child.emit('exit',1);return null;}),b=new TouchAudio({spawn:g.spawn});try{await assert.rejects(b.set('master',{muted:true}),/Verbindung/);assert.equal(g.requests.length,1);}finally{b.close();}});
test('unresponsive helper times out and releases pending operations',async()=>{const f=fake(()=>null),a=new TouchAudio({spawn:f.spawn,timeoutMs:15});const keepAlive=pause(70);try{await assert.rejects(a.set('master',{volume:40}),/rechtzeitig/);assert.equal(a.pending.size,0);assert.equal(f.children[0].killed,true);}finally{a.close();await keepAlive;}});
test('closed service rejects further work without launching helper',async()=>{let calls=0;const a=new TouchAudio({spawn:()=>{calls++;}});a.close();await assert.rejects(a.targets(),/geschlossen/);await assert.rejects(a.state(['master']),/geschlossen/);await assert.rejects(a.set('jarvis',{muted:true}),/geschlossen/);assert.equal(calls,0);});
