'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const {TouchDeck,defaultConfig,LIMITS}=require('../src/services/touch-deck.cjs');
const {SESSION_MS}=require('../src/services/touch-mobile.cjs');
const actions=[{id:'listen'},{id:'speech-stop'},{id:'command',text:true},{id:'scene',choices:[{id:'Spiel'},{id:'Pause'},{id:'Start'},{id:'Ende'}],transition:true},{id:'start',choices:[{id:'both'}]},{id:'stop',choices:[{id:'both'}]},{id:'source',choices:[{id:'camera'},{id:'game'}],switch:true},{id:'gaming'},{id:'show'},{id:'jarvis',choices:[{id:'voiceEnabled'}],switch:true},{id:'prepare'},{id:'release'}];
function fixture(t,options={}){
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'batto-touch-')),webRoot=path.join(directory,'web');fs.mkdirSync(webRoot);for(const [file,content]of Object.entries({'index.html':'<title>Batto Touch Deck</title>','client.js':'console.log("touch");','style.css':'body{color:gold}'}))fs.writeFileSync(path.join(webRoot,file),content);
 const calls=[],controls={catalog:()=>({actions}),execute:async value=>{calls.push(value);return {ok:true,completed:value.steps.length};}};
 const deck=new TouchDeck({directory,controls,host:'127.0.0.1',port:0,webRoot,...options});t.after(async()=>{await deck.close();fs.rmSync(directory,{recursive:true,force:true});});return {deck,directory,calls};
}
function request(deck,route,{method='GET',body,token,headers={}}={}){
 const data=body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body);
 return new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port:deck.mobile.port,path:route,method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(data?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}:{}),...headers}},res=>{let text='';res.on('data',chunk=>text+=chunk);res.on('end',()=>{let value;try{value=JSON.parse(text);}catch{value=text;}resolve({status:res.statusCode,headers:res.headers,value});});});req.on('error',reject);req.end(data);});
}
async function pair(deck){const r=await request(deck,'/api/pair',{method:'POST',body:{pin:deck.mobileStatus().pin}});assert.equal(r.status,200);return r.value;}
function sensorConfig(){const c=defaultConfig();c.profiles[0].buttons[0]={id:'cpu-key',type:'sensor',title:'CPU',symbol:'°',sensorId:'private/cpu/temperature'};c.profiles[0].buttons[1]={id:'folder',type:'folder',title:'Ordner',buttons:[{id:'nested',type:'action',title:'Pause',steps:[{action:'scene',target:'Pause',transition:'fade',durationMs:500}]}]};return c;}

test('construction leaves server, files, microphone and sensor polling asleep',t=>{
 let sensorReads=0;const {deck,directory,calls}=fixture(t,{getSensors:()=>{sensorReads++;return [];}});assert.equal(sensorReads,0);assert.equal(deck.mobile.server,null);assert.equal(deck.mobile.pending,null);assert.equal(deck.mobile.assets.size,0);assert(!fs.existsSync(path.join(directory,'touch-deck.json')));assert.deepEqual(calls,[]);assert.equal(deck.snapshot().mobile.running,false);assert.equal(sensorReads,1);
});
test('save preserves an isolated profile, fills grids, strips foreign settings and reloads',t=>{
 const {deck,directory}=fixture(t);const original=path.join(directory,'jarvis-settings.json');fs.writeFileSync(original,'{"voiceEnabled":true}');const config=sensorConfig();config.multiChat={token:'never-copy'};config.profiles[0].buttons[2].settings={password:'never-copy'};let events=0;deck.on('change',()=>events++);const state=deck.save(config);assert.equal(events,1);assert.equal(state.profiles[0].buttons[1].buttons.length,15);assert(!JSON.stringify(state).includes('never-copy'));assert.equal(fs.readFileSync(original,'utf8'),'{"voiceEnabled":true}');assert.equal(fs.readdirSync(directory).filter(x=>x.endsWith('.tmp')).length,0);
 const loaded=new TouchDeck({directory,controls:deck.controls});assert.deepEqual(loaded.config,deck.config);assert.equal(loaded.loadError,'');state.profiles[0].name='mutated';assert.equal(deck.config.profiles[0].name,'Mein Deck');
});
test('invalid save never replaces the last valid deck and corrupt load preserves source',t=>{
 const {deck,directory}=fixture(t);deck.save(defaultConfig());const before=fs.readFileSync(deck.file,'utf8'),bad=defaultConfig();bad.profiles[0].buttons[0].steps=[{action:'exec',command:'anything'}];assert.throws(()=>deck.save(bad),/nicht unterstützt/);assert.equal(fs.readFileSync(deck.file,'utf8'),before);fs.writeFileSync(deck.file,'{broken');const loaded=new TouchDeck({directory,controls:deck.controls});assert.match(loaded.loadError,/nicht geladen/);assert.equal(fs.readFileSync(deck.file,'utf8'),'{broken');
});
test('schema rejects oversized actions, deep folders, duplicate IDs and unsafe pictures',t=>{
 const {deck}=fixture(t);for(const mutate of [c=>c.profiles[0].buttons[0].steps=Array(9).fill({action:'listen'}),c=>c.profiles[0].buttons[0].icon='data:image/svg+xml,<svg/>',c=>c.profiles[0].buttons[1].id=c.profiles[0].buttons[0].id,c=>c.profiles[0].columns=100,c=>c.profiles=Array(21).fill(c.profiles[0]),c=>c.profiles[0].buttons[0].steps=[{action:'scene',target:'Spiel',durationMs:9999}],c=>c.profiles[0].buttons[0].steps=[{action:'command',text:'a'.repeat(501)}]]){const c=defaultConfig();mutate(c);assert.throws(()=>deck.save(c));}
 const c=defaultConfig();let current=c.profiles[0].buttons;for(let depth=0;depth<5;depth++){current[0]={id:'folder'+depth,type:'folder',title:'Folder',buttons:[]};current=current[0].buttons;}assert.throws(()=>deck.save(c),/vier Ebenen/);
});
test('only the saved button executes, folders navigate and sensors return live or unavailable values',async t=>{
 const {deck,calls}=fixture(t,{getSensors:()=>[{id:'private/cpu/temperature',name:'CPU Paket',value:51.5,unit:'°C'}]});deck.save(sensorConfig());assert.equal((await deck.press({profileId:'main',path:[],index:0})).value,51.5);assert.deepEqual(await deck.press({profileId:'main',path:[],index:1}),{ok:true,type:'folder',path:[1]});await deck.press({profileId:'main',path:[1],index:0});assert.deepEqual(calls,[{steps:[{action:'scene',target:'Pause',transition:'fade',durationMs:500}]}]);deck.getSensors=()=>[];assert.equal((await deck.press({profileId:'main',index:0})).value,null);for(const position of [{profileId:'missing',index:0},{profileId:'main',path:[0],index:0},{profileId:'main',path:[1],index:2},{profileId:'main',index:-1},{profileId:'main',index:'0'}])await assert.rejects(deck.press(position));assert.equal(calls.length,1);
});
test('stale action targets remain editable, execution uses the shared control validation',async t=>{
 const {deck}=fixture(t);const c=defaultConfig();c.profiles[0].buttons[0].steps=[{action:'scene',target:'Gelöschte Szene'}];deck.save(c);deck.controls.execute=async()=>{throw Error('Bitte ein vorhandenes Ziel wählen.');};await assert.rejects(deck.press({profileId:'main',index:0}),/vorhandenes Ziel/);assert.equal(deck.snapshot().profiles[0].buttons[0].steps[0].target,'Gelöschte Szene');
});
test('remote state omits control definitions, sensor identifiers, settings and pairing secrets',t=>{
 const {deck}=fixture(t,{getSensors:()=>[{id:'private/cpu/temperature',name:'CPU',value:53,unit:'°C'},{id:'unused/sensor',name:'unused',value:2,unit:'V'}]});deck.save(sensorConfig());const remote=deck.remoteState(),serialized=JSON.stringify(remote);for(const hidden of ['steps','sensorId','private/cpu/temperature','unused/sensor','mobile','pin'])assert(!serialized.includes(hidden),hidden);assert.deepEqual(remote.readings['cpu-key'],{value:53,unit:'°C',name:'CPU'});const revision=remote.revision;assert.equal(deck.remoteReadings().revision,revision);deck.save(defaultConfig());assert.equal(deck.remoteState().revision,revision+1);assert.deepEqual(Object.keys(deck.remoteReadings()).sort(),['readings','revision']);
});
test('explicit mobile start serves only approved assets and pairing protects all device APIs',async t=>{
 const {deck}=fixture(t);const started=await deck.mobileStart();assert(started.running);assert.match(started.pin,/^\d{6}$/);assert.equal(started.urls.length,1);assert.equal((await request(deck,'/')).status,200);assert.equal((await request(deck,'/client.js')).status,200);assert.equal((await request(deck,'/style.css')).status,200);assert.equal((await request(deck,'/touch-deck.json')).status,404);assert.equal((await request(deck,'/../touch-deck.json')).status,404);for(const route of ['/api/state','/api/readings'])assert.equal((await request(deck,route)).status,401);assert.equal((await request(deck,'/api/press',{method:'POST',body:{profileId:'main',index:0}})).status,401);const p=await pair(deck);assert.match(p.token,/^[a-f0-9]{64}$/);assert(!JSON.stringify(p.state).includes(started.pin));assert.equal((await request(deck,'/api/state',{token:p.token})).status,200);const readings=await request(deck,'/api/readings',{token:p.token});assert.equal(readings.status,200);assert(!('profiles'in readings.value));assert.equal(deck.mobileStatus().clients,1);
});
test('mobile requests reject hostile origins, host spoofing, cross-site fetch and body injection',async t=>{
 const {deck,calls}=fixture(t);await deck.mobileStart();const {token}=await pair(deck);for(const headers of [{Origin:'https://evil.example'},{Origin:'null'},{Host:'evil.example:'+deck.mobile.port},{Host:'192.168.123.123:'+deck.mobile.port},{'Sec-Fetch-Site':'cross-site'}])assert.equal((await request(deck,'/api/state',{token,headers})).status,403);const ok=await request(deck,'/api/press',{method:'POST',token,body:{profileId:'main',path:[],index:0}});assert.equal(ok.status,200);assert.deepEqual(calls,[{steps:[{action:'listen'}]}]);assert.equal((await request(deck,'/api/press',{method:'POST',token,body:{profileId:'main',index:0,steps:[{action:'show'}]}})).status,400);assert.equal(calls.length,1);assert.equal((await request(deck,'/api/press',{method:'POST',token,body:'{'})).status,400);assert.equal((await request(deck,'/api/press',{method:'POST',token,body:'x'.repeat(5000)})).status,413);assert.equal((await request(deck,'/api/press',{method:'POST',token,body:{},headers:{'Content-Type':'text/plain'}})).status,415);
});
test('PIN attempts are bounded and rotation revokes all prior sessions',async t=>{
 const {deck}=fixture(t);await deck.mobileStart();const {token}=await pair(deck),wrong=deck.mobile.pin==='000000'?'000001':'000000';for(let i=0;i<5;i++)assert.equal((await request(deck,'/api/pair',{method:'POST',body:{pin:wrong}})).status,401);assert.equal((await request(deck,'/api/pair',{method:'POST',body:{pin:deck.mobile.pin}})).status,429);deck.rotatePin();assert.equal(deck.mobileStatus().clients,0);assert.equal((await request(deck,'/api/state',{token})).status,401);assert((await pair(deck)).token);
});
test('sessions expire, simultaneous clients are bounded, stopping revokes and frees the server',async t=>{
 let now=100000;const {deck}=fixture(t,{now:()=>now});await deck.mobileStart();const {token}=await pair(deck);for(let i=1;i<8;i++)await pair(deck);assert.equal((await request(deck,'/api/pair',{method:'POST',body:{pin:deck.mobile.pin}})).status,409);now+=SESSION_MS+1;assert.equal((await request(deck,'/api/state',{token})).status,401);assert.equal(deck.mobileStatus().clients,0);await pair(deck);const stopped=await deck.mobileStop();assert.equal(stopped.running,false);assert.equal(stopped.pin,'');assert.equal(stopped.clients,0);assert.equal(deck.mobile.assets.size,0);assert.equal(deck.mobile.server,null);await deck.mobileStart();assert.equal((await request(deck,'/api/state',{token})).status,401);
});
test('repeated start/stop has one listener and busy action errors remain readable',async t=>{
 const {deck}=fixture(t);await Promise.all([deck.mobileStart(),deck.mobileStart()]);const server=deck.mobile.server;assert.equal((await deck.mobileStart()).port,server.address().port);deck.controls.execute=async()=>{throw Error('Eine Tastenaktion läuft bereits.');};const {token}=await pair(deck);const result=await request(deck,'/api/press',{method:'POST',token,body:{profileId:'main',index:0}});assert.equal(result.status,400);assert.match(result.value.message,/läuft bereits/);await Promise.all([deck.mobileStop(),deck.mobileStop()]);assert.equal(server.listening,false);
});
test('disconnect revokes only that phone and releases its pairing slot',async t=>{
 const {deck}=fixture(t);await deck.mobileStart();const first=await pair(deck),second=await pair(deck);assert.equal(deck.mobileStatus().clients,2);assert.equal((await request(deck,'/api/disconnect',{method:'POST',token:first.token})).status,200);assert.equal(deck.mobileStatus().clients,1);assert.equal((await request(deck,'/api/state',{token:first.token})).status,401);assert.equal((await request(deck,'/api/state',{token:second.token})).status,200);assert.equal((await request(deck,'/api/disconnect',{method:'POST'})).status,401);
});
